GRIFFINCollaboration/GRSISort

libraries/TGRSIFormat/TFragmentQueue.cxx

Fix mutex issue.

---

include/TCal.h
include/TCalManager.h
include/TEfficiencyCal.h
include/TEnergyCal.h
include/TGainMatch.h
libraries/TGRSIAnalysis/TCal/TCal.cxx
libraries/TGRSIAnalysis/TCal/TCalManager.cxx
libraries/TGRSIAnalysis/TCal/TEfficiencyCal.cxx
libraries/TGRSIAnalysis/TCal/TEnergyCal.cxx
libraries/TGRSIAnalysis/TCal/TGainMatch.cxx
libraries/TGRSIAnalysis/TCal/makefile

- Added a TCal manager for TCals
- It is made to only accept one type of TCal. For example if you put a TEfficiencyCal into it, it will not accept a TEnergyCal Later.
- I still have to write clear and print functions here, etc.
- TCal Manager makes a  copy of the TCal so you have to access the TCal in the manager to change it.

TCal Manager

---

include/TCalManager.h
libraries/TGRSIAnalysis/TCal/TCalManager.cxx
libraries/TGRSILoop/TGRSILoop.cxx

- fixes bug in the event counter when multiple midas files are sorted
- adds a Print and Clear Function to TCalManager

Fixed bug in Event Counter

---

include/TCal.h
libraries/TGRSIAnalysis/TCal/TCal.cxx
libraries/TGRSIAnalysis/TCal/TCalManager.cxx

As mentioned in the last pull request I am changing the TChannel* pointer to a TRef for persistency in the ROOT Streamer facility.

Change from TCalManager's TChannel* to TRef

---

include/TGRSIFit.h
include/TGainMatch.h
include/TPeak.h
libraries/GROOT/GCanvas.cxx
libraries/TGRSIAnalysis/TCal/TCal.cxx
libraries/TGRSIAnalysis/TCal/TCalManager.cxx
libraries/TGRSIAnalysis/TCal/TGainMatch.cxx
libraries/TGRSIAnalysis/TGRSIFit/TGRSIFit.cxx
libraries/TGRSIAnalysis/TGRSIFit/TPeak.cxx

- a little towards the GRIFFIN side of things. But shouldn't be too hard to generalize for anyone who wants this for anything else.
- I will eventually change the Clone() statement in TCalManager to use a Copy constructor, but I have not written that yet.

Bulk of gain matching complete

---

util/MakeMatrices.C

Changed 3D histograms (angular correlations) to have variable binning in angle, and fixed 1keV wide binning in the two energies. Added transfer function to 3D histograms to enable transparency when using drawing options glcol or glcolz. Changed script so that it overwrites the output-file without asking.

updated MakeMatrices.C

---

include/TCal.h
include/TEfficiencyCal.h
include/TGainMatch.h
libraries/TGRSIAnalysis/TCal/TCal.cxx
libraries/TGRSIAnalysis/TCal/TEfficiencyCal.cxx
libraries/TGRSIAnalysis/TCal/TGainMatch.cxx
users/UserFillObj.h

- This is an update to try to debug problems for Andrew.

Starting to introduce TEfficiencyCal

---

libraries/TGRSIAnalysis/TCSM/TCSM.cxx
libraries/TGRSIAnalysis/TCSM/TCSMData.cxx
libraries/TGRSIAnalysis/TCSM/TCSMHit.cxx

No changes outside of CSM stuff.

Added Print command

---

include/TCSM.h
include/TCSMData.h
include/TCSMHit.h
libraries/TGRSIAnalysis/TCSM/TCSM.cxx
libraries/TGRSIAnalysis/TCSM/TCSMData.cxx
libraries/TGRSIAnalysis/TCSM/TCSMHit.cxx

Hi guys, this is the new sorting algorithim I wrote for TCSM.  
Please make sure I am not doing anything stupid and overwriting stuff you have done.  I can't count the number of times I had to do a ```git reset --hard``` before I got things to sync up properly.
I looked through the changes and it only seems to touch the TCSM files which is a good sign.

Big rewrite for TCSM

---

include/TGRSIRunInfo.h
libraries/TGRSIFormat/TGRSIRunInfo.cxx
libraries/TGRSILoop/TGRSILoop.cxx
util/makefile
util/offsetadd.C
util/offsetfind.C

- I updated the makefile so that make util actually uses make in the appropriate way
- Added a time stamp offset utility that acts on FragmentTrees (I'm almost done a better on)
- Fixed a version checking problem during batch Midas sorting

makefile, tree time stamp search

---

makefile

Updated makefile to work on both Centos and Debian.

---

libraries/TGRSIAnalysis/TGRSIFit/TPeak.cxx

I changed a few things in TPeak:
* Set the upper limit of sigma to be related to the width of the window used for the peak fitting
* Changed the upper limit of the ratio to be 100. The units are percentage, so this makes sense, but we can discuss whether it needs to be a little beyond 100 so that the error estimates are correct.
* Set the initial value of sigma to be related to the peak fitting window size.
* Removed the hard-coding of the log-likelihood flag.
* Changed the integration limits for the area calculation to +/- 5 sigma. The previous limits would cause integration problems in some cases because they were so large. 5 sigma gets you 99.9999426697% of the area (thanks, Wikipedia!).

Modified a few TPeak limits and initial guesses for more robust fitting.

---

include/TPacesHit.h
libraries/TGRSIFormat/TChannel.cxx
util/bufferclean.C

- bufferclean is a code meant to clean out the saved buffer in GRIFFIN from run to run. It seems to be working so time to move on to bigger and better things.
- We will probably want to multi thread this at some point to (hopefully) double it's speed

bufferclean working

---

libraries/TGRSIAnalysis/TCSM/TCSM.cxx

Main change is switching from charge to energy in building events.

A few more changes for TCSM

---

include/TGRSIDetector.h
include/TGRSIDetectorHit.h
include/TGRSITransition.h
libraries/TGRSIAnalysis/TGRSIDetector/TGRSIDetector.cxx
libraries/TGRSIAnalysis/TGRSIDetector/TGRSIDetectorHit.cxx
libraries/TGRSIAnalysis/TNucleus/TGRSITransition.cxx
util/bufferclean.C
util/offsetfind.C

- TGRSITransition
- TGRSIDetector

Just come simple HTML comments

---

util/makefile
util/offsetfind.C

- It works to find the correct offsets.
- The SCEPTAR offsets are a little weird.
- Might use a normal Gaussian on GRIFFIN, and figure something else out for SCEPTAR
- Need to think about whether I **want** to line up SCEPTAR with GRIFFIN

Update to offsetfind

---

include/TMidasFile.h
libraries/TMidas/TMidasFile.cxx
util/bufferclean.C

- Must use TMidasFile::FillBuffer to fill a buffer which gets written at closing time, or when TMidasFile::WriteBuffer is called. 
- Might have endian-ness issues, I will deal with that when they occur. (it's a pretty obvious failure mode)

Midas Files Write faster now

---

util/bufferclean.C
util/offsetfix.C

- Offsetfix writes faster now too!

Added buffer writing ability in offsetfix

---

util/offsetfix.C

- had a funky bracket [whoops :( ]
- now has a list of real digitizers, please feel free to add to these.
- now does checks of good events
- will spit out errors in the checks if a hardcoded verbose flag is changed to 1

Fixed offsetfix

---

util/GainMatchGRIFFIN.C
util/GainMatchGRIFFIN_README.txt

I cleaned up the macro I've been using for gain-matching and wrote up a ReadMe for it. The bulk of it was written before I knew about some TCal and TChannel functions, so it could definitely be improved. Thought it might be useful for other people though. I'm open to corrections and suggestions.

new util macro for gain-matching

---

include/TChannel.h
libraries/TGRSIFormat/TChannel.cxx

- These ideas are outlined in #263

TChannel maps work together

---

util/offsetfix.C

- this correction file can be turned off with an n flag on command line
- it uses the corrections to skip the finding stage
- much faster because corrections should not change during subruns
- some name hardcoding right not, shouldnt be a big deal
- added a correction map to remove some confusing code

offsetfix writes a file of corrections

---

include/TChannel.h
include/TTimeCal.h
libraries/TGRSIAnalysis/TCal/TCal.cxx
libraries/TGRSIAnalysis/TCal/TTimeCal.cxx
libraries/TGRSIAnalysis/TCal/makefile
libraries/TGRSIFormat/TChannel.cxx

TTimeCal and quick changes to cal file as per #252

---

include/TChannel.h
libraries/TGRSIAnalysis/TAnalysisTreeBuilder/TAnalysisTreeBuilder.cxx
libraries/TGRSIAnalysis/TCal/TGainMatch.cxx
libraries/TGRSIAnalysis/TGRSIFit/TPeak.cxx
libraries/TGRSIFormat/TChannel.cxx
users/UserFillObj.h
users/UserInitObj.h
util/makefile
util/offsetfix.C
util/timeloop.C

- TAnalysisTreeBuilder has a few small changes
-  2 us moving window
-  Logic to make sure Sceptar is actually a sceptar
- TPeak, and TGainMatch have a couple of fixes that make peak finding a little better when the gains have changed substantially.
- Added timeloop.C (by Peter) for those who want to build the low energy time differences.

WriteToRoot is now very friendly, other changes

---

include/TCSMHit.h
libraries/TGRSIAnalysis/TCSM/TCSMHit.cxx

Added resiiliance to untrustworthy strips.

---

util/exAnalysis.C

- called exAnalysis.C (Based off of MakeMatrices)
- makes basic histograms (gamma-gamma 2D, gamma singles 1D, beta-gamma 1D)
- tried to include many comments to explain how it works

Added an example analysis Script

---

include/TGainMatch.h
libraries/TGRSIAnalysis/TCal/TGainMatch.cxx

- Some new features still pretty buggy, but useful
- NEED TO ADD DOCUMENTATION!!!!! (not straight forward for occasionally changing gains)

Changes to TGainMatch for robustness

---

include/TCal.h
include/TEnergyCal.h
include/TGRSITransition.h
include/TNucleus.h
libraries/TGRSIAnalysis/TCal/TEnergyCal.cxx
libraries/TGRSIAnalysis/TNucleus/TGRSITransition.cxx
libraries/TGRSIAnalysis/TNucleus/TNucleus.cxx
util/MakeMatrices.C
util/MakeTimeDiffSpec.C
util/offsetfix.C

- Get, Remove, Add, Print of transitions within nucleus.
- Can also write out a new source file
- Can't read in a custom source file yet, haven't decided the best way to do this.

Added some nice TNucleus functionality

---

include/GCanvas.h
include/TCal.h
include/TEnergyCal.h
include/TNucleus.h
libraries/GROOT/GCanvas.cxx
libraries/TGRSIAnalysis/TCal/TCal.cxx
libraries/TGRSIAnalysis/TCal/TEnergyCal.cxx

Use 'p' to fit a TPeak...It's pretty boss....

Updates to EnergyCal and GROOT

---

libraries/GROOT/GCanvas.cxx

- fixed an if statement bracket from the last push I made

Fixed if statement

---

include/TGRSIFunctions.h
include/TPeak.h
libraries/GROOT/GCanvas.cxx
libraries/TGRSIAnalysis/TGRSIFit/TGRSIFunctions.cxx
libraries/TGRSIAnalysis/TGRSIFit/TPeak.cxx

- Includes a Popup menu selection in the GCanvas, turns out they are incredibly easy to add!
- Just add in the header `// *MENU* after the declaration of the member function.

Added TPeak background drawing

---

include/TGRSIFit.h
include/TPeak.h
libraries/TGRSIAnalysis/TGRSIFit/TGRSIFit.cxx
libraries/TGRSIAnalysis/TGRSIFit/TPeak.cxx

- Can now draw (error independent) residuals on a TPeak (GUI and Command line)
- Draws the residuals at half the peak height, intended to give shape, not absolute value.
- Last Push of the night... Did too many today....

Can now Draw TPeak Residuals

---

makefile

Can a different mac user try this as well? I want to make sure this isn't dependent on my build.

Made changes to allow compilation on my mac

---

include/Globals.h
libraries/GROOT/GCanvas.cxx
libraries/GROOT/GRootObjectManager.cxx
libraries/TGRSIAnalysis/TGriffin/TGriffin.cxx
makefile

- fixed some printf warnings
- "Major" change was the change of how while loops in GRootObjectManager were working
@pcbend can you check and make sure I did what you were trying to do. Maybe I missed something.

Small warning fixes 

---

include/TAnalysisTreeBuilder.h
include/TCSMHit.h
include/TChannel.h
include/TEpicsFrag.h
include/TGRSIDetector.h
include/TGRSILoop.h
include/TGRSIOptions.h
include/TGRSITransition.h
include/TKinematics.h
libraries/TGRSIAnalysis/TAnalysisTreeBuilder/TAnalysisTreeBuilder.cxx
libraries/TGRSIAnalysis/TCSM/TCSMHit.cxx
libraries/TGRSIAnalysis/TGRSIDetector/TGRSIDetector.cxx
libraries/TGRSIAnalysis/TGRSIFit/TPeak.cxx
libraries/TGRSIAnalysis/TNucleus/TGRSITransition.cxx
libraries/TGRSIFormat/TChannel.cxx
libraries/TGRSIFormat/TEpicsFrag.cxx
libraries/TGRSILoop/TGRSILoop.cxx
libraries/TGRSIint/TGRSIOptions.cxx

A few formatting fixes. Mostly just adding const to the end of Print statements to get inheritance to work properly.
@rbraid just for a heads up I changed a bunch of formatting in TCSM. I also noticed you have a weird if statement (a couple of times) that currently reads 
```c++
else if(!trustVertical && !trustVertical)
```
I'm assuming this should be
```c++
else if(!trustVertical && !trustHorizontal)
```
but I think just an `else` will do here.

Removed some warnings

---

include/Globals.h
include/TXMLOdb.h
libraries/TGRSILoop/TGRSILoop.cxx
libraries/TMidas/TXMLOdb.cxx

Fixed TXMLOdb::GetNodeName scope issue

---

etc/html/ROOT.css
util/bufferclean.C
util/makefile
util/offsetadd.C
util/offsetfind.C
util/offsetfix.C

- helps compatibility with darwin.
- changed location of graphics for html docs

Some final commits before versioning

---

libraries/TDataParser/TDataParser.cxx
libraries/TGRSIFormat/TFragment.cxx
util/MakeMatrices.C
util/MakeTimeDiffSpec.C

I've corrected an issue with the masking of the 4G cfd time and remainder in TFragment::GetTimeStamp_ns and TFragment::Get4GCfd. Also changed the check of the event trailer to be compatible with the new way of writing data.

Small bug fixes

---

include/TGRSIDetector.h
include/TGRSIDetectorHit.h
include/TGriffinHit.h
libraries/TGRSIAnalysis/TCal/TEnergyCal.cxx
libraries/TGRSIAnalysis/TGRSIDetector/TGRSIDetectorHit.cxx
libraries/TGRSIAnalysis/TGriffin/TGriffinHit.cxx

- Didn't do much, just had a few minutes to throw some stuff together.

Moved a bunch of fields and functions TGrifHit -> TGRSIHit

---

include/GCanvas.h
libraries/GROOT/GCanvas.cxx

This change allows the display and removal of peak labels. I'm not attached to the keys "d" and "D", so if anyone has a better, more memorable suggestion, I'd like to hear it.

Added peak label display, currently associated with keys "d" and "D".

---

include/TFragment.h
libraries/TGRSIAnalysis/makefile
libraries/TGRSIFormat/TFragment.cxx
makefile
users/UserFillObj.h

- Usage described in function... IsDetector(start of channel name to match, options)
- Options C for core, S for segments, A for low gain, B for high gain can be used
- Defaults to C and A
- Will return multiples if you give multiple options ie "CAB" will return core, high gain and lowgain.
- Please let me know if you have comments on the functionality/logic

Added an IsDetector Method

---

include/TGriffin.h
include/TPaces.h
include/TPacesHit.h
libraries/TGRSIAnalysis/TPaces/TPaces.cxx
libraries/TGRSIAnalysis/TPaces/TPacesHit.cxx
libraries/TGRSIAnalysis/makefile
src/makefile

Paces has been added using the Griffin format.
- We might want to remove the PPG bitset from Paces (it was there before too)
- Would it make sense to have a PPG branch?

Added Paces to leangrsi

---

util/offsetfix.C

... also checking to make sure I set up everything right on GRSIUser.

Fixed a typo in offsetfix.C

---

include/TDescantData.h
include/TGriffinData.h
include/TPacesData.h
include/TSceptarData.h
libraries/TGRSIAnalysis/TGRSIDetector/TGRSIDetector.cxx
libraries/TGRSIAnalysis/TGRSIDetector/TGRSIDetectorHit.cxx
util/check885.C
util/makefile

- This was done by Ryan. So blame him.

Few running fixes (and real fixes)

---

include/TDescantData.h
include/TDescantHit.h
include/TSceptar.h
include/TSceptarData.h
include/TSceptarHit.h
libraries/TDataParser/TDataParser.cxx
libraries/TGRSIAnalysis/TDescant/TDescantHit.cxx
libraries/TGRSIAnalysis/TSceptar/TSceptar.cxx
libraries/TGRSIAnalysis/TSceptar/TSceptarHit.cxx

DESCANT and SCEPTAR waveform analysis code for upcoming experiments.

DESCANT and SCEPTAR waveform analysis.

---

include/TCrystalHit.h
include/TGRSIDetectorHit.h
include/TTigress.h
include/TTigressHit.h
libraries/TGRSIAnalysis/TAnalysisTreeBuilder/TAnalysisTreeBuilder.cxx
libraries/TGRSIAnalysis/TTigress/TTigress.cxx
libraries/TGRSIAnalysis/TTigress/TTigressHit.cxx

Stuff happened.  Things improved (?).  If it doesn't work; blame Ryan.  If it is nice, give Peter credit.

TTigress leangrsi updates.

---

libraries/GROOT/makefile
libraries/TDataParser/makefile
libraries/TGRSIAnalysis/TAnalysisTreeBuilder/makefile
libraries/TGRSIAnalysis/TBetaDecay/makefile
libraries/TGRSIAnalysis/TCSM/makefile
libraries/TGRSIAnalysis/TCal/makefile
libraries/TGRSIAnalysis/TDescant/makefile
libraries/TGRSIAnalysis/TGRSIDetector/makefile
libraries/TGRSIAnalysis/TGRSIFit/makefile
libraries/TGRSIAnalysis/TGriffin/makefile
libraries/TGRSIAnalysis/TKinematics/makefile
libraries/TGRSIAnalysis/TNucleus/makefile
libraries/TGRSIAnalysis/TPaces/makefile
libraries/TGRSIAnalysis/TSRIM/makefile
libraries/TGRSIAnalysis/TSceptar/makefile
libraries/TGRSIAnalysis/TSharc/makefile
libraries/TGRSIAnalysis/TTigress/makefile
libraries/TGRSIAnalysis/TTip/makefile
libraries/TGRSIAnalysis/TTriFoil/makefile
libraries/TGRSIFormat/TChannel.cxx
libraries/TGRSIFormat/TFragmentQueue.cxx
libraries/TGRSIFormat/makefile
libraries/TGRSILoop/makefile
libraries/TGRSIRootIO/makefile
libraries/TGRSIServer/makefile
libraries/TGRSIint/TGRSIint.cxx
libraries/TGRSIint/makefile
libraries/TGint/makefile
libraries/TMidas/makefile
makefile

Fixes issue #366.  Apparently std::sort requires a comparison operator equivalent to < not <=.

TChannel fix.

---

libraries/GROOT/makefile
libraries/TDataParser/makefile
libraries/TGRSIAnalysis/TAnalysisTreeBuilder/makefile
libraries/TGRSIAnalysis/TBetaDecay/makefile
libraries/TGRSIAnalysis/TCSM/makefile
libraries/TGRSIAnalysis/TCal/makefile
libraries/TGRSIAnalysis/TDescant/makefile
libraries/TGRSIAnalysis/TGRSIDetector/makefile
libraries/TGRSIAnalysis/TGRSIFit/makefile
libraries/TGRSIAnalysis/TGriffin/makefile
libraries/TGRSIAnalysis/TKinematics/makefile
libraries/TGRSIAnalysis/TNucleus/makefile
libraries/TGRSIAnalysis/TPaces/makefile
libraries/TGRSIAnalysis/TSRIM/makefile
libraries/TGRSIAnalysis/TSceptar/makefile
libraries/TGRSIAnalysis/TSharc/makefile
libraries/TGRSIAnalysis/TTigress/makefile
libraries/TGRSIAnalysis/TTip/makefile
libraries/TGRSIAnalysis/TTriFoil/makefile
libraries/TGRSIFormat/makefile
libraries/TGRSILoop/makefile
libraries/TGRSIRootIO/makefile
libraries/TGRSIServer/makefile
libraries/TGRSIint/makefile
libraries/TGint/makefile
libraries/TMidas/makefile

Cleaning up the finished lines in the makefile output.

Cleaning up makefile output

---

include/TGriffin.h
libraries/TGRSIAnalysis/TGriffin/TGriffin.cxx
libraries/TGRSIAnalysis/TGriffin/TGriffinHit.cxx

- moved the this->Charge(0); statement to the end of TGriffinHit::Add(TGriffinHit *hit)
- added ResetAddback() function to TGriffin to reset only the addback vector (instead of using Clear all the time which resets everything)

Bugfix and improvement of addback

---

include/TCrystalHit.h
include/TSharcHit.h
include/TTipHit.h
libraries/GROOT/GCanvas.cxx
libraries/TGRSIAnalysis/TCal/TGainMatch.cxx
libraries/TGRSIAnalysis/TSceptar/TSceptar.cxx
libraries/TGRSIFormat/TFragment.cxx

Fixed a bug in TGainMatch and removed some compiler warnings.

Minor bug fixes

---

include/TGRSIDetectorHit.h
libraries/TGRSIAnalysis/TGRSIDetector/TGRSIDetectorHit.cxx
libraries/TGRSIAnalysis/TTigress/TTigress.cxx

- Fixed Getters to Set to default calculated values if variables weren't already set, and setters to set what the user specifies.
- There are also const getters that get already calculated variables, or calculate on the fly otherwise.

Fixed Getters and Setters

---

include/TGriffinHit.h
libraries/TGRSIAnalysis/TGriffin/TGriffinHit.cxx

Missed this in Yesterdays pull request.

Added Set and Get Crystal

---

include/TTip.h
include/TTipHit.h
libraries/TGRSIAnalysis/TTip/TTip.cxx
libraries/TGRSIAnalysis/TTip/TTipHit.cxx
libraries/TGRSIAnalysis/makefile

- Needs to be tested with TIP data. Currently Compiles and looks good

Added Tip to the code

---

.gitignore
makefile
myanalysis/makefile

- git ignores any new files put into this directory.
- the make all now compiles the Utils and myanalysis directory
-  any file in myanalysis with a .cxx extension is automatically compiles.
- this all needs to be updated once the rest of the detector libraries are ready and we can use grsi-config.
- Can someone please test this on Linux?
I'm doing this as we are heading towards the directory restructuring.

Added myanalysis directory 

---

include/TUserSortInfo.h
users/TUserSortInfo.cxx
users/makefile

- My git ignore worked properly...whoops

Actually added UserInfo

---

include/GCanvas.h
include/GFile.h
include/GHistBrowser.h
include/GRootObjectManager.h
include/TBetaDecay.h
include/TCSM.h
include/TCSMHit.h
include/TCalManager.h
include/TDescantHit.h
include/TEfficiencyCal.h
include/TEnergyCal.h
include/TEpicsFrag.h
include/TFragment.h
include/TGRSIRootIO.h
include/TGRSIRunInfo.h
include/TGRSIStats.h
include/TGRSITransition.h
include/TGainMatch.h
include/TMidasEvent.h
include/TMidasFile.h
include/TNucleus.h
include/TSceptarHit.h
include/TTigress.h
include/TTigressHit.h

Many of these classes do not indeed need virtual dtors. However, this will allow us to not screw up if we inherit from these classes in the future (as we have made this mistake in the past).

Made polymorphic classes have virtual dtors

---

include/TGRSIDetectorHit.h
libraries/TGRSIAnalysis/TGRSIDetector/TGRSIDetectorHit.cxx

- The main issue was that we kept getting when we were supposed to be setting.

Fixed GetPosition Function

---

include/TBGOData.h
include/TCFDCal.h
include/TFragmentSelector.h
include/TSharcData.h
include/TTigressData.h
libraries/TGRSIFormat/TFragmentSelector.cxx

Changed cfd members in Data classed to be stored as int (it's read in as int and used as int later on). Updated the TFragmentSelector.

Change cfd to int, updated TFragmentSelector

---

examples/exAnalysis.cxx
include/TEpicsFrag.h
include/TGRSIRunInfo.h
include/TMidasEvent.h
include/TMidasFile.h
libraries/TGRSIAnalysis/TAnalysisTreeBuilder/TAnalysisTreeBuilder.cxx
libraries/TGRSIAnalysis/TGriffin/TGriffin.cxx
libraries/TGRSIFormat/TEpicsFrag.cxx
libraries/TGRSIFormat/TGRSIRunInfo.cxx
libraries/TMidas/TMidasEvent.cxx
libraries/TMidas/TMidasFile.cxx
util/html_generator.C

- This happened in the Fragment->Analysis step.
- Fixed by checking if "in-memory" run info's file name has a length. During this step of sorting, it should be NULL unless there was a filename input on the command line
- Also updated some HTML docs

Fixed problem where run info file would not be read

---

examples/grsiruninfoexample.info
include/TGRSIRunInfo.h
libraries/TGRSIAnalysis/TAnalysisTreeBuilder/TAnalysisTreeBuilder.cxx
libraries/TGRSIFormat/TGRSIRunInfo.cxx
makefile
myanalysis/makefile

Updated TGRSIRunInfo to be able to set or unset moving window

---

include/TDataParser.h
include/TGRSIRootIO.h
include/TPPG.h
libraries/TDataParser/TDataParser.cxx
libraries/TGRSIFormat/TFragmentQueue.cxx
libraries/TGRSIFormat/TGRSIFormatLinkDef.h
libraries/TGRSIFormat/TPPG.cxx
libraries/TGRSIFormat/makefile
libraries/TGRSIRootIO/TGRSIRootIO.cxx

- still making it a little more useful

Added PPG class for FragmentTrees

---

include/TAnalysisTreeBuilder.h
include/TPPG.h
libraries/TDataParser/TDataParser.cxx
libraries/TGRSIAnalysis/TAnalysisTreeBuilder/TAnalysisTreeBuilder.cxx
libraries/TGRSIFormat/TGRSIFormatLinkDef.h
libraries/TGRSIFormat/TPPG.cxx
libraries/TGRSIRootIO/TGRSIRootIO.cxx

- TPPG writes to analysis tree. If data has no PPG, it is ignored
- PPG iterating can now happen for testing PPG

Made PPG More useful

---

include/TFragment.h
include/TGRSIDetectorHit.h
include/TGriffin.h
include/TTip.h
include/TTipData.h
include/TTipHit.h
libraries/TGRSIAnalysis/TGriffin/TGriffin.cxx
libraries/TGRSIAnalysis/TTip/TTipData.cxx
libraries/TGRSIint/TGRSIint.cxx
scripts/LeanMatrices.cxx

- includes all changes made during the Cd run
- lean TIP updates

Various bug fixes and updates

---

libraries/TGRSIAnalysis/TAnalysisTreeBuilder/TAnalysisTreeBuilder.cxx

...because no one wants all these numbers over the screen.

Removing diagnostic printf statements.

---

include/TAnalysisTreeBuilder.h
include/TS3.h
include/TS3Data.h
include/TS3Hit.h
include/TSiLi.h
include/TSiLiData.h
include/TSiLiHit.h
libraries/TGRSIAnalysis/TAnalysisTreeBuilder/TAnalysisTreeBuilder.cxx
libraries/TGRSIAnalysis/TS3/TS3.cxx
libraries/TGRSIAnalysis/TS3/TS3Data.cxx
libraries/TGRSIAnalysis/TS3/TS3Hit.cxx
libraries/TGRSIAnalysis/TS3/TS3LinkDef.h
libraries/TGRSIAnalysis/TS3/makefile
libraries/TGRSIAnalysis/TSiLi/TSiLi.cxx
libraries/TGRSIAnalysis/TSiLi/TSiLiData.cxx
libraries/TGRSIAnalysis/TSiLi/TSiLiHit.cxx
libraries/TGRSIAnalysis/TSiLi/TSiLiLinkDef.h
libraries/TGRSIAnalysis/TSiLi/makefile
libraries/TGRSIAnalysis/TTigress/TTigressData.cxx
libraries/TGRSIAnalysis/makefile
libraries/TGRSIFormat/TChannel.cxx
libraries/TGRSIFormat/TGRSIRunInfo.cxx
makefile
src/makefile
util/grsi-config

Spice is now added to the master branch of grsisort;
Additionally some small bug fixes are included; the largest was a strict comparision to the TChannels that would cause the Fragment sort to crash at write time if multiple tchannels with the same name existed.

Spice added to GRSISort

---

include/TGRSIRunInfo.h
libraries/TGRSIAnalysis/TAnalysisTreeBuilder/TAnalysisTreeBuilder.cxx
libraries/TGRSIFormat/TGRSIRunInfo.cxx
libraries/TGRSIint/TGRSIint.cxx
util/timeloop.C

* Included a command to read the RunInfo in TGRSIint.cxx.
* Changed "SetInfoFromFile" to "ReadInfoFromFile" for more consistency and updated all uses of it.

Modfications to TGRSIRunInfo

---

thisgrsi.sh

Can now put `source /path/to/GRSISort/thisgrsi.sh` into bash.

Added thisgrsi.sh to source in bashrc

---

include/TGRSIDetectorHit.h
include/TGriffinData.h
include/TGriffinHit.h
libraries/TGRSIAnalysis/TGRSIDetector/TGRSIDetectorHit.cxx
libraries/TGRSIAnalysis/TGriffin/TGriffin.cxx
libraries/TGRSIAnalysis/TGriffin/TGriffinData.cxx
libraries/TGRSIAnalysis/TGriffin/TGriffinHit.cxx

- PUHit of 0 means that it is the first hit. This allows me to use PUHit of 4 for the hits with way too many pileups.

Added bits for pileups.

---

include/TGriffinHit.h
include/TScaler.h
libraries/TGRSIFormat/LinkDef.h
libraries/TGRSIFormat/TPPG.cxx
libraries/TGRSIFormat/TScaler.cxx

First iteration of the precision scalers, wrap-around of scalers not being taken into account yet.

Adding precision scalers, fixed memory leak in TPPG::Copy

---

include/TDecayFit.h
libraries/TGRSIAnalysis/TGRSIFit/LinkDef.h
libraries/TGRSIAnalysis/TGRSIFit/TDecayFit.cxx

- This is how all fitters should eventually be coded!
- Only generates decay curves, no fitting yet.

Initial commit of TDecayFit

---

include/TDecayFit.h
libraries/TGRSIAnalysis/TGRSIFit/TDecayFit.cxx
libraries/TGRSIAnalysis/TGRSIFit/TPeak.cxx
util/EnergyCal.cxx

- decay fit is not the place we will really be doing the fits from. However, it works and I have tested it on monte carlo'ed data.

Fitting is getting closer in decay fit

---

include/TDecayFit.h
libraries/TGRSIAnalysis/TGRSIFit/TDecayFit.cxx

Moving on to building and fitting the total activity of the chain.

Can fit nucleus in a decay chain...well

---

include/TDecayFit.h
include/TGriffinHit.h
libraries/TGRSIAnalysis/TGRSIFit/TDecayFit.cxx
util/TestDecay.C

- I don't think it will fit yet, but very close.
- TestDecay.C in the util directory shows what you can do so far with this class.

Total Activities of chains are included

---

include/TDecay.h
libraries/TGRSIAnalysis/TGRSIFit/TDecay.cxx
util/TestDecay.C

- Summed components of full decay now plots
- Took draw components out of menu, can now fix and limit components and background

New DecayFit features

---

include/TGRSIRootIO.h
libraries/TDataParser/TDataParser.cxx
libraries/TGRSIFormat/TScaler.cxx
libraries/TGRSILoop/TGRSILoop.cxx

Also included PPG and Scaler events in "successfully sorted" counter and percentage.

TScaler bug fixes

---

include/TPeak.h
include/TScaler.h
libraries/TGRSIAnalysis/TGRSIFit/TPeak.cxx
libraries/TGRSIFormat/LinkDef.h
libraries/TGRSIFormat/TScaler.cxx
libraries/TGRSIRootIO/TGRSIRootIO.cxx
scripts/LeanCorrelations.cxx
scripts/LeanMatrices.cxx
util/Root2Rad.cxx

- Also small improvements to TScaler
- Root2Rad improvements was the ability to convert THnSparse histograms
- More robust TH2 conversion
- changed default for TPeak to be log likelihood.
- Turns off writing of scalers until a better streamer can be written

Improved Root2Rad and Made a faster angular correlations script

---

.grsirc
util/CycleFitUtils.C

Fixed the macro path to point at myAnalysis and not myanalysis

Added base utils for fitting lifetimes (in progress)

---

include/TCSM.h
include/TDescant.h
include/TGriffin.h
include/TPaces.h
include/TS3.h
include/TScaler.h
include/TSceptar.h
include/TSharc.h
include/TSiLi.h
include/TTigress.h
include/TTip.h
libraries/TGRSIAnalysis/TCSM/TCSM.cxx
libraries/TGRSIAnalysis/TDescant/TDescant.cxx
libraries/TGRSIAnalysis/TGriffin/TGriffin.cxx
libraries/TGRSIAnalysis/TPaces/TPaces.cxx
libraries/TGRSIAnalysis/TS3/TS3.cxx
libraries/TGRSIAnalysis/TSceptar/TSceptar.cxx
libraries/TGRSIAnalysis/TSharc/TSharc.cxx
libraries/TGRSIAnalysis/TSiLi/TSiLi.cxx
libraries/TGRSIAnalysis/TTigress/TTigress.cxx
libraries/TGRSIAnalysis/TTip/TTip.cxx
libraries/TGRSIFormat/TGRSIRunInfo.cxx
libraries/TGRSIFormat/TScaler.cxx

small cleanups and const correctness

Added exception handling in GetHit functions

---

include/TTigressData.h

I've re-added a SetCoreTime function to TTigressData.h, it seems to have been commented out for some reason during the recent tweaks.

(Re-)Added SetCoreTime() to TTigressData.h

---

include/Globals.h
include/TTigressData.h
libraries/TGRSIAnalysis/TDescant/TDescant.cxx
libraries/TGRSIAnalysis/TGriffin/TGriffin.cxx
libraries/TGRSIAnalysis/TPaces/TPaces.cxx
libraries/TGRSIAnalysis/TS3/TS3.cxx
libraries/TGRSIAnalysis/TSceptar/TSceptar.cxx
libraries/TGRSIAnalysis/TSharc/TSharc.cxx
libraries/TGRSIAnalysis/TSiLi/TSiLi.cxx
libraries/TGRSIAnalysis/TTip/TTip.cxx
src/grsisort.cxx

- Also made a namespace for exit_exceptions (and potentially more) although this may end up being capitalized.

Fixed charge problem in TTigressData

---

include/TDecay.h
libraries/TGRSIAnalysis/TGRSIFit/LinkDef.h
libraries/TGRSIAnalysis/TGRSIFit/TDecay.cxx
util/TestDecay.C

- Can now write and read TDecay, TDecayChain and TSingle Decays to and from files.
- Can now clone them as well.
- Can know right click on a TDecayFit on the on the screen and Choose DrawComponents without a seg fault.

Fixes TDecay bugs

---

include/TDecay.h
libraries/TGRSIAnalysis/TGRSIFit/TDecay.cxx

- Still has a weird bug where the graph doesn't clone properly so after every fit the style of graph goes back to default. I have a feeling the graph has to be a pointer to clone properly. I'm fine with the way it works for now, this really only exists because there was no inflight entertainment to santa fe...

Can draw residual graphs in TDecay

---

include/TDecay.h
libraries/TGRSIAnalysis/TGRSIFit/TDecay.cxx

- Only TSingleDecay, more comments to come

Added comments for TSingleDecay

---

include/TPPG.h
include/TTigressHit.h
libraries/TGRSIAnalysis/TTigress/TTigressHit.cxx
libraries/TGRSIFormat/TPPG.cxx
makefile
util/Root2Rad.cxx

- added more information to TPPG::Print
- changed the makefile so that it compiles on Mac OS using ROOT 6 and on Linux or Mac OS using ROOT 5

Modified TPPG::Print, changed makefile to work with Mac OS and ROOT 6

---

include/TPulseAnalyzer.h
include/TRF.h
include/TS3.h
include/TS3Data.h
include/TS3Hit.h
include/TSiLi.h
include/TSiLiData.h
include/TSiLiHit.h
libraries/TGRSIAnalysis/TPulseAnalyzer/TPulseAnalyzer.cxx
libraries/TGRSIAnalysis/TRF/TRF.cxx
libraries/TGRSIAnalysis/TS3/TS3.cxx
libraries/TGRSIAnalysis/TS3/TS3Data.cxx
libraries/TGRSIAnalysis/TS3/TS3Hit.cxx
libraries/TGRSIAnalysis/TSiLi/TSiLi.cxx
libraries/TGRSIAnalysis/TSiLi/TSiLiData.cxx
libraries/TGRSIAnalysis/TSiLi/TSiLiHit.cxx

Reverts GRIFFINCollaboration/GRSISort#560

Revert "SiLi rewrite relating to issue #559"

---

libraries/TGRSIAnalysis/TRF/LinkDef.h

- Removed .h file and pragma from linkdef.

Fixed library generation for RF

---

include/TGRSIDetectorHit.h
include/TSiLiHit.h
include/TTigressHit.h
include/TTip.h
include/TTipHit.h
libraries/TGRSIAnalysis/TGRSIDetector/TGRSIDetectorHit.cxx
libraries/TGRSIAnalysis/TS3/TS3.cxx
libraries/TGRSIAnalysis/TSiLi/TSiLiHit.cxx
libraries/TGRSIAnalysis/TTip/TTip.cxx
libraries/TGRSIAnalysis/TTip/TTipHit.cxx

Added GetSegment() and associated code to TGRSIDetectorHit, as well as introducing @r3dunlop's fix for the flag problem. Removed conflicts in TSiLi and TS3 which might've resulted otherwise.
I also got TTip working in the multiset format. Everything there seems to be behaving itself.

Multiset -  a load of updates to include GetSegment() and fix Tip

---

include/TTigress.h
libraries/TGRSIAnalysis/TTigress/TTigress.cxx

Fixed error in TTigress.cxx, TFragment doesn't have GetAddress() function. The address has to be grabbed directly.

Fixed small error in TTigress.cxx

---

libraries/TGRSIAnalysis/TDescant/TDescant.cxx

Fixing compiler warning introduced in last merge.

Removing compiler warning

---

include/TFragment.h

(otherwise we get problems with old data).

Added checks for zero-crossing and psd words if requested index is available

---

include/TTigressHit.h
include/TTipHit.h
libraries/TGRSIAnalysis/TPulseAnalyzer/TPulseAnalyzer.cxx
libraries/TGRSIAnalysis/TTigress/TTigress.cxx
libraries/TGRSIAnalysis/TTigress/TTigressHit.cxx
libraries/TGRSIAnalysis/TTip/TTip.cxx
libraries/TGRSIAnalysis/TTip/TTipHit.cxx
util/grsi-config

Tigress and Tip waveform fitting hadn't been merged properly when multiset was merged. Also added TPulseAnalyzer to grsi-config.

Re-added waveform fitting to the Tip and Tigress classes

---

include/TPPG.h
libraries/TGRSIAnalysis/TGRSIFit/TGRSIFunctions.cxx

Fixed OS X compiliation errors.

---

libraries/TDataParser/TDataParser.cxx

Fixing NetworkPacketNumber bug

---

include/TDescant.h
include/TDescantHit.h
include/TGRSIRunInfo.h
libraries/TDataParser/TDataParser.cxx
libraries/TGRSIAnalysis/TDescant/TDescant.cxx
libraries/TGRSIAnalysis/TDescant/TDescantHit.cxx
libraries/TGRSIFormat/TGRSIRunInfo.cxx
libraries/TGRSIFormat/TNewFragment.cxx
libraries/TGRSIFormat/TOldFragment.cxx

- TGRSIRunInfo can now be used to tell DESCANT to analyze waveforms and store the generated waveforms
- --suppress-errors flag now also suppresses warning message about number of pile-up hits
- added check for self-assignment in assignment operator of TOldFragment

Minor bug fixes and improvements

---

README.md
include/GRootGlobals.h
include/TChannel.h
include/TFragment.h
include/TGRSIDetector.h
include/TGRSIDetectorHit.h
include/TGRSIRunInfo.h
include/TPulseAnalyzer.h
include/TS3.h
include/TS3Hit.h
include/TTigress.h
include/TTigressHit.h
libraries/GROOT/GRootGlobals.cxx
libraries/GROOT/LinkDef.h
libraries/TDataParser/TDataParser.cxx
libraries/TGRSIAnalysis/TAnalysisTreeBuilder/TAnalysisTreeBuilder.cxx
libraries/TGRSIAnalysis/TGRSIDetector/TGRSIDetector.cxx
libraries/TGRSIAnalysis/TGRSIDetector/TGRSIDetectorHit.cxx
libraries/TGRSIAnalysis/TGRSIFit/TPeak.cxx
libraries/TGRSIAnalysis/TPulseAnalyzer/TPulseAnalyzer.cxx
libraries/TGRSIAnalysis/TS3/TS3.cxx
libraries/TGRSIAnalysis/TS3/TS3Hit.cxx
libraries/TGRSIAnalysis/TTigress/TTigress.cxx
libraries/TGRSIAnalysis/TTigress/TTigressHit.cxx
libraries/TGRSIFormat/TChannel.cxx
libraries/TGRSIFormat/TGRSIRunInfo.cxx

TChannel:  If one passes an integration parameter in the calfile, it now defaults to use the integration in during the GetEnergy call.
TTigress:  A TVector3 was being created on every default GetDoppler call, changed this to use a default const static fBeamDirection set to (0,0,1) stored in the TGRSIDetectorHIt base.

TChannel Integration and a Tigress Improvment

---

include/TGRSIRunInfo.h
include/TS3.h
include/TS3Hit.h
include/TTigressHit.h
libraries/TDataParser/TDataParser.cxx
libraries/TGRSIAnalysis/TAnalysisTreeBuilder/TAnalysisTreeBuilder.cxx
libraries/TGRSIAnalysis/TS3/TS3.cxx
libraries/TGRSIAnalysis/TS3/TS3Hit.cxx
libraries/TGRSIAnalysis/TTigress/TTigressHit.cxx
libraries/TGRSIFormat/TGRSIRunInfo.cxx

Added BAMBINO. Includes an IsDownstream bool for TS3 which allows for upstream and downstream S3 detectors. Slight change to GetPosition function to allow for variable S3 offset from target as well as the upstream and downstream detectors.
Slight change to TDataParser. TigressDataToFragment now returns a negative result (in line with the equivalent GRIFFIN function) if in error. So now the midas event will be written to the terminal if there is an error. Previously it just returned the number of processed Fragments, which is always >=0.

Added BAMBINO and slight change to DataParser errors

---

include/TChannel.h
include/TFragment.h
include/TGRSIDetector.h
include/TGRSIint.h
include/TReaction.h
include/TSharc.h
include/TSharcHit.h
libraries/TGRSIAnalysis/TSharc/TSharc.cxx
libraries/TGRSIAnalysis/TSharc/TSharcHit.cxx
libraries/TGRSIFormat/TChannel.cxx
libraries/TGRSIFormat/TFragment.cxx
libraries/TGRSIint/TGRSIint.cxx

* added some utility functions to TFragment.
* fixed a bug going from tfragment charge to tgriffinhit charge/energy I introduced a couple weeks ago.
* fixed sharc hit building from multiset update.

add links to $GRSISYS/include by default in the interpreter.

---

include/TAngularCorrelation.h
libraries/TGRSIAnalysis/TAngularCorrelation/TAngularCorrelation.cxx

* Lots of new functions.
* Functionality of non-folded and non-grouped ACs (angular correlations) should remain the same.
* Functions with "Modified" in them are used to fold and group.
* 2D histograms removed from class member list

Including folding and grouping

---

include/TAngularCorrelation.h
libraries/TGRSIAnalysis/TAngularCorrelation/TAngularCorrelation.cxx

Reverts GRIFFINCollaboration/GRSISort#678

Revert "Including folding and grouping"

---

include/TAngularCorrelation.h
libraries/TGRSIAnalysis/TAngularCorrelation/TAngularCorrelation.cxx

This was a bit sloppy, but I think it worked now.

TAngularCorrelation update: folding and grouping

---

libraries/TGRSIAnalysis/TAngularCorrelation/TAngularCorrelation.cxx

* The backgrounds plotted in the fitting visualization now belong to that slice, rather than just the last fit.
* If the area error is less than the Sqrt of the area, the error is fixed to the Sqrt of the area.
* Fixed a bug in UpdatePeak.

Fixed some TAngularCorrelation bugs.

---

include/TDataParser.h
libraries/TDataParser/TDataParser.cxx
libraries/TGRSILoop/TGRSILoop.cxx

Initial implementation of new GRIFFIN DAQ bank GRF3. Some implementation still missing until new fragment class is pushed.

New bank: GRF3

---

libraries/TGRSIAnalysis/TAnalysisTreeBuilder/TAnalysisTreeBuilder.cxx

... in TAnalysisTree builder instead of one fragment per pileup found.
Most of this is intentions.  The useful bits start at line 359 of TAnalysisTreeBuilder.cxx
This commit fixes the problem #700

only one Fragment is inserted into the multiset

---

include/TGRSIRunInfo.h
include/TGainMatch.h
include/TGriffin.h
include/TGriffinHit.h
include/TS3Hit.h
libraries/TGRSIAnalysis/TCal/TGainMatch.cxx
libraries/TGRSIAnalysis/TGRSIFit/TDecay.cxx
libraries/TGRSIAnalysis/TGRSIFit/TLMFitter.cxx
libraries/TGRSIAnalysis/TGRSIFit/TPeak.cxx
libraries/TGRSIAnalysis/TGriffin/TGriffin.cxx
libraries/TGRSIAnalysis/TGriffin/TGriffinHit.cxx
libraries/TGRSIAnalysis/TS3/TS3Hit.cxx
libraries/TGRSIFormat/TGRSIRunInfo.cxx
libraries/TGRSILoop/TGRSILoop.cxx
libraries/TGRSIRootIO/TGRSIRootIO.cxx
users/UserInitObj.h
util/TestDecay.C

- Made GRIFFIN position default to TGRSIRunInfo value.
- Fixes #703

Fix for Griffin position

---

examples/grsiruninfoexample.info
include/TAnalysisTreeBuilder.h
include/TChannel.h
include/TGRSIOptions.h
include/TGRSIRunInfo.h
include/TLaBr.h
include/TLaBrHit.h
include/TTAC.h
include/TTACHit.h
libraries/TGRSIAnalysis/TAnalysisTreeBuilder/TAnalysisTreeBuilder.cxx
libraries/TGRSIAnalysis/TLaBr/LinkDef.h
libraries/TGRSIAnalysis/TLaBr/TLaBr.cxx
libraries/TGRSIAnalysis/TLaBr/TLaBrHit.cxx
libraries/TGRSIAnalysis/TTAC/LinkDef.h
libraries/TGRSIAnalysis/TTAC/TTAC.cxx
libraries/TGRSIAnalysis/TTAC/TTACHit.cxx
libraries/TGRSIFormat/TChannel.cxx
libraries/TGRSIFormat/TFragment.cxx
libraries/TGRSIFormat/TGRSIRunInfo.cxx
libraries/TGRSIint/TGRSIOptions.cxx
libraries/TGRSIint/TGRSIint.cxx
util/grsi-config

- Fixed run info seg fault problem
- now loads run info from root file
- still does not load info from command line on loading. need to look into this.
- can now include a list of bad cycles in run info using `BadCycle:`
- includes run info example
**Should accept LaBr PR first.**

Cycle rejection in TGRSIRunInfo

---

include/TGRSIRunInfo.h
libraries/TGRSIFormat/TGRSIRunInfo.cxx

Left over junk in streamer that wasn't flagged properly during merge. Removed now.

Fixed a streamer issue in run info from merge

---

include/TPPG.h
libraries/TGRSIAnalysis/TGRSIDetector/TGRSIDetectorHit.cxx
libraries/TGRSIFormat/TFragment.cxx
libraries/TGRSIFormat/TPPG.cxx
libraries/TGRSIFormat/TScaler.cxx
libraries/TGRSIRootIO/TGRSIRootIO.cxx

This was done to solve issue #728

Changed TPPG to quasi-singleton

---

include/TAnalysisTreeBuilder.h
include/TGRSIRootIO.h
include/TGRSIRunInfo.h
libraries/TGRSIAnalysis/TAnalysisTreeBuilder/TAnalysisTreeBuilder.cxx
libraries/TGRSIFormat/TChannel.cxx
libraries/TGRSIFormat/TGRSIRunInfo.cxx
libraries/TGRSILoop/TGRSILoop.cxx
libraries/TGRSIRootIO/TGRSIRootIO.cxx
libraries/TGRSIint/TGRSIint.cxx

- Fixes #718 and #724 . 
- Can now easily write run info files
- RunInfo auto loads and auto writes properly.
I have tested this, but of course I can't test every single permutation of things. It might be worth keeping an eye on things for a bit to make sure things are working (not that they were before).

Runinfofix

---

libraries/TGRSIAnalysis/TAnalysisTreeBuilder/TAnalysisTreeBuilder.cxx

Fix for #725 Dante in analysis tree

---

include/TGRSIDetectorHit.h
libraries/TGRSIAnalysis/TGRSIDetector/TGRSIDetectorHit.cxx

- Removed const vs non-const function definitions for transient data members
- Replaced these with mutable declarations
- *should* be easier to maintain and add this way

Added mutable declaration to TGRSIDetectorHit

---

include/Globals.h
include/TAnalysisTreeBuilder.h
include/TChannel.h
libraries/TDataParser/TDataParser.cxx
libraries/TGRSIAnalysis/TAnalysisTreeBuilder/TAnalysisTreeBuilder.cxx
libraries/TGRSIFormat/TChannel.cxx
libraries/TGRSIFormat/TGRSIRunInfo.cxx
scripts/LeanMatrices.cxx
util/ScaleCalibration.cxx

- Mnemonic is in the TChannel now.
- Mnemonic is a more functional structure now and not just a wrapper for a few variables.
- Strings are still public variables but will slowly be closed out as they are corrected in the TGRSIDetector classes.
- Still processing limited, Guelph computers write at 100%
- Fixed name problem with `TChannel::SetName` function

Added enumerations to mnemonics

---

include/TDataParser.h
include/TFragment.h
include/TFragmentMap.h
include/TGRSIDetectorHit.h
include/TS3Hit.h
include/TSiLi.h
include/TSiLiHit.h
libraries/TDataParser/TDataParser.cxx
libraries/TDataParser/TFragmentMap.cxx
libraries/TGRSIAnalysis/TAnalysisTreeBuilder/TAnalysisTreeBuilder.cxx
libraries/TGRSIAnalysis/TGRSIDetector/TGRSIDetectorHit.cxx
libraries/TGRSIAnalysis/TGriffin/TGriffinHit.cxx
libraries/TGRSIAnalysis/TRF/TRF.cxx
libraries/TGRSIAnalysis/TS3/TS3.cxx
libraries/TGRSIAnalysis/TS3/TS3Hit.cxx
libraries/TGRSIAnalysis/TSiLi/TSiLiHit.cxx
libraries/TGRSIFormat/TDiagnostics.cxx
libraries/TGRSIFormat/TFragment.cxx
libraries/TGRSIFormat/TFragmentQueue.cxx
libraries/TGRSILoop/TGRSILoop.cxx
makefile

- made all members of TFragment private (accessible only through getter- and setter-functions)
- updated TDataParser for new GRF4 bank
- fragments of this bank are put into a map until a full set of piled up hits has been found
- minimization for 2 hits implemented, rest still needs implementing
- this hasn't been tested yet!

Fixed TFragment and updated TDataParser for GRF4 banks

---

include/TGRSIDetectorHit.h
libraries/TGRSIAnalysis/TGRSIDetector/TGRSIDetectorHit.cxx
scripts/LeanMatrices.cxx
util/WalkPlot.cxx

- not my favourite since Every GetTimeStamp() call must find a channel and apply an offset. Will think about how to make this better but this should be a working solution for now.

Fixed Timestamp Offsets during analysis tree build

---

histos/MakeTigressHistograms.cxx
thisgrsi.sh
util/AnalyzeDataLoss.cxx
util/WalkPlot.cxx
util/grsi-config

- updated bash script to set library path correctly
- removed obsolete TGRSILoop library from gris-config
- removed compiler warnings (sign mismatch and unused variables)

Some bug fixes

---

include/StoppableThread.h
include/TAnalysisHistLoop.h
include/TAnalysisWriteLoop.h
include/TDataLoop.h
include/TDetBuildingLoop.h
include/TEventBuildingLoop.h
include/TFragHistLoop.h
include/TFragWriteLoop.h
include/TFragmentChainLoop.h
include/TGRSIOptions.h
include/TMidasFile.h
include/TTerminalLoop.h
include/TUnpackingLoop.h
include/ThreadsafeQueue.h
libraries/TGRSIint/TGRSIOptions.cxx
libraries/TGRSIint/TGRSIint.cxx
libraries/TLoops/StoppableThread.cxx
libraries/TLoops/TAnalysisWriteLoop.cxx
libraries/TLoops/TDataLoop.cxx
libraries/TLoops/TDetBuildingLoop.cxx
libraries/TLoops/TEventBuildingLoop.cxx
libraries/TLoops/TFragWriteLoop.cxx
libraries/TLoops/TFragmentChainLoop.cxx
libraries/TLoops/TUnpackingLoop.cxx
libraries/TMidas/TMidasFile.cxx

- added custom queue size
- changed output

Custom queue size and better output

---

histos/MakeTigressHistograms.cxx
include/TGRSIDetectorHit.h
include/TPulseAnalyzer.h
include/TRF.h
include/TS3.h
include/TSiLi.h
include/TSiLiHit.h
include/TTigress.h
libraries/TGRSIAnalysis/TPulseAnalyzer/TPulseAnalyzer.cxx
libraries/TGRSIAnalysis/TS3/TS3.cxx
libraries/TGRSIAnalysis/TS3/TS3Hit.cxx
libraries/TGRSIAnalysis/TSiLi/TSiLi.cxx
libraries/TGRSIAnalysis/TSiLi/TSiLiHit.cxx
libraries/TGRSIAnalysis/TTigress/TTigress.cxx
makefile

Fixed tigress addback
Added SiLi positions
Made  S3 more generic
Added Mohamads waveform fit for SiLi
Added start of addback to SiLi
Added blur option to Tigress, S3 and SiLi positions
Changed  Tigress get functions back to pointers
Made makefile not require git

Merged TTigress TSiLi TS3 changes + fixes + additions

---

histos/MakeTigressHistograms.cxx
include/TGRSIDetectorHit.h
include/TPulseAnalyzer.h
include/TS3.h
include/TS3Hit.h
libraries/TGRSIAnalysis/TPulseAnalyzer/TPulseAnalyzer.cxx
libraries/TGRSIAnalysis/TS3/TS3.cxx
libraries/TGRSIAnalysis/TS3/TS3Hit.cxx
libraries/TGRSIFormat/TMnemonic.cxx

Fixed SPICE mnemonic and finished modifications I started to S3 positions, now mnemonic is used to set positions in TS3Hit correctly for all bambino and SPICE configurations automatically.

SPICE Mnemonic & S3 position

---

include/TDataParser.h
include/TEventBuildingLoop.h
include/TParsingDiagnostics.h
include/ThreadsafeQueue.h
libraries/TDataParser/TDataParser.cxx
libraries/TGRSIFormat/TParsingDiagnostics.cxx
libraries/TGRSIFormat/TSortingDiagnostics.cxx
libraries/TLoops/TEventBuildingLoop.cxx
libraries/TLoops/TFragWriteLoop.cxx
libraries/TLoops/TUnpackingLoop.cxx

- Added more output from loops
- updated the *Diagnostics::WriteToFile functions

Added and updated screen/file outputs

---

GRSIProof/grsiproof.cxx
include/TGRSIDetector.h
include/TGRSIDetectorHit.h
include/TGRSIOptions.h
include/TGriffin.h
include/TGriffinHit.h
include/TS3.h
include/TSharc.h
include/TSiLi.h
include/TSiLiHit.h
include/TTigress.h
include/TTransientBits.h
libraries/TGRSIAnalysis/TGRSIDetector/TGRSIDetector.cxx
libraries/TGRSIAnalysis/TGRSIDetector/TGRSIDetectorHit.cxx
libraries/TGRSIAnalysis/TGriffin/TGriffin.cxx
libraries/TGRSIAnalysis/TGriffin/TGriffinHit.cxx
libraries/TGRSIAnalysis/TS3/TS3.cxx
libraries/TGRSIAnalysis/TS3/TS3Hit.cxx
libraries/TGRSIAnalysis/TSiLi/TSiLi.cxx
libraries/TGRSIAnalysis/TSiLi/TSiLiHit.cxx
libraries/TGRSIAnalysis/TTigress/TTigress.cxx
libraries/TGRSIFormat/LinkDef.h
libraries/TGRSIint/TGRSIOptions.cxx

Template class that allows you to use as many bits as you want.

Added TTransientBits to be used for flags in analysis classes

---

include/TPulseAnalyzer.h
include/TSiLi.h
include/TSiLiHit.h
libraries/TGRSIAnalysis/TGriffin/TGriffinHit.cxx
libraries/TGRSIAnalysis/TPulseAnalyzer/TPulseAnalyzer.cxx
libraries/TGRSIAnalysis/TS3/TS3Hit.cxx
libraries/TGRSIAnalysis/TSiLi/TSiLi.cxx
libraries/TGRSIAnalysis/TSiLi/TSiLiHit.cxx
libraries/TGRSIFormat/LinkDef.h

I found the errors I was having, the bit class that had been used for TTigress hadnt been declared in the dictionary generation and there were some mismatches of TSiLiHit bit check and TGRSIDetector bit checks.
Also some other small tweaks to S3 and SiLi

Fixed HitBit and small additions

---

include/TMnemonic.h
include/TSiLiHit.h
include/TTigress.h
libraries/TGRSIAnalysis/TS3/TS3.cxx
libraries/TGRSIAnalysis/TS3/TS3Hit.cxx
libraries/TGRSIAnalysis/TSiLi/TSiLiHit.cxx
libraries/TGRSIAnalysis/TTigress/TTigress.cxx
libraries/TGRSIAnalysis/TTigress/TTigressHit.cxx

Changes from @jsmallcombe, see also PR #838.

Changes from @jsmallcombe

---

include/TGRSIOptions.h
libraries/TGRSIFormat/TMnemonic.cxx
libraries/TGRSIint/TGRSIOptions.cxx
libraries/TGRSIint/TGRSIint.cxx

Using -b calls TApplication:MakeBatch() similar to ROOT itself.

Added batch mode to grsisort

---

include/TGRSIDetectorHit.h
libraries/TGRSIAnalysis/TGRSIDetector/TGRSIDetectorHit.cxx
libraries/TGRSIFormat/TGRSIRunInfo.cxx

This is important for 32bit systems where Long_t is only 32bit long and not 64bit.

Changed timestamp from Long_t to Long64_t

---

libraries/TLoops/TUnpackingLoop.cxx

Bug fix for last pull request

---

include/TGRSIOptions.h
include/TGRSIint.h
libraries/TGRSIint/TGRSIOptions.cxx
libraries/TGRSIint/TGRSIint.cxx

- updated doxygen comments for TGRSIOptions and TGRSIint. These will be updated on the wiki on Monday.

Updated some documentation (TGRSIOptions, TGRSIint)

---

CONTRIBUTING.md
include/TDataLoop.h
libraries/GROOT/GPeak.cxx
libraries/TGRSIint/TGRSIint.cxx
libraries/TLoops/TDataLoop.cxx
libraries/TMidas/TMidasEvent.cxx

Also added a first test of CONTRIBUTING.md

switched run-start/stop from ODB to midas-time

---

include/TChannel.h
include/TGRSIDetectorHit.h

Also changed TGRSIDetectorHit::ETimeFlag::kNone to kNoneSet to remove shadow warning.

 Fixed TChannel bug #966

---

include/TS3.h
include/TSiLi.h
include/TSiLiHit.h
libraries/TGRSIAnalysis/TS3/TS3.cxx
libraries/TGRSIAnalysis/TSiLi/TSiLi.cxx
libraries/TGRSIAnalysis/TSiLi/TSiLiHit.cxx

Some further improvements to the TSiLi and TS3 classes

TSiLi addback replaced and some general class tidying

---

GRSIProof/grsiproof.cxx
include/TChannel.h
include/TPriorityValue.h
libraries/TGRSIFormat/TChannel.cxx

Fixes an issue where updating CT-parameters deletes energy calibration and vice versa.

Fixed bug in TChannel (see issue #948)

---

libraries/TLoops/TDataLoop.cxx
util/AddToChannelNumber.cxx

Missed some changes in other files due to TChannel setters now taking TPriorityValues as arguments instead of values and priorities.

Missing files from last pull request

---

libraries/TGRSIFormat/TPPG.cxx
libraries/TGRSIint/TAnalysisOptions.cxx
libraries/TGRSIint/TGRSIint.cxx
libraries/TLoops/TAnalysisWriteLoop.cxx
libraries/TLoops/TFragWriteLoop.cxx

This should make errors like in #975 more obvious.

Added checks that file were successfully opened

---

include/TParsingDiagnostics.h
libraries/TDataParser/TDataParser.cxx
libraries/TGRSIFormat/TChannel.cxx
libraries/TGRSIFormat/TParsingDiagnostics.cxx

- Changed TParsingDiagnostics maps to use channel address as keys.
- Added check for channel with single event to TParsingDiagnostics::Print.

TParsingDiagnostics update

---

include/TAnalysisWriteLoop.h
include/TAnalysisWriteLoopClient.h
include/TGRSIOptions.h
include/TParallelFileMerger.h
libraries/TGRSIint/TGRSIOptions.cxx
libraries/TLoops/LinkDef.h
libraries/TLoops/TAnalysisWriteLoop.cxx
libraries/TLoops/TAnalysisWriteLoopClient.cxx
libraries/TLoops/TParallelFileMerger.cxx

This implements a TParallelFileMerger to use multiple threads to write the analysis tree.

Parallel writing

---

include/TAnalysisWriteLoop.h
include/TAnalysisWriteLoopClient.h
include/TSingleton.h
libraries/TLoops/TAnalysisWriteLoop.cxx
libraries/TLoops/TAnalysisWriteLoopClient.cxx
libraries/TLoops/TDataLoop.cxx
libraries/TLoops/TParallelFileMerger.cxx

- Fixed issue when running multiple instances of grsisort
- Fixed problem with TSingleton in grsiproof
- Fixed double reading of cal files
There is still an issue running grsisort through a torque/pbs queue.

Fixed several issues

---

libraries/TLoops/TAnalysisWriteLoopClient.cxx
libraries/TLoops/TEventBuildingLoop.cxx
man/man1/grsisort.1
util/ErrorReport.sh

- Updated ErrorReport.sh for new issue templates
- Added print statement to show how events are built (trigger ID or timestamp)
- Updated grsisort man file
- Removed debugging file created by TAnalysisWriteLoopClient

Smaller changes

---

libraries/TGRSIFormat/TMnemonic.cxx

This also leaves DA in as the mnemonic for legacy

Added LB as mnemonic for LaBr detectors

---

include/TGRSIMap.h
include/TGRSIRunInfo.h
include/TLaBr.h
include/TSiLiHit.h
libraries/TGRSIAnalysis/TGriffin/TGriffin.cxx
libraries/TGRSIAnalysis/TLaBr/TLaBr.cxx
libraries/TGRSIint/TGRSIOptions.cxx

TLaBr is now derived from TSuppressed and has additional functions to get BGO suppressed hits.

 Added BGO suppression to TLaBr

---

include/TBgoHit.h
include/TDescantHit.h
include/TTdrCloverBgo.h
include/TTdrTigressBgo.h
include/TZeroDegreeHit.h
libraries/TGRSIAnalysis/TBgo/TBgoHit.cxx
libraries/TGRSIAnalysis/TBgo/TTdrCloverBgo.cxx
libraries/TGRSIAnalysis/TBgo/TTdrTigressBgo.cxx
libraries/TGRSIAnalysis/TDescant/TDescantHit.cxx
libraries/TGRSIAnalysis/TTdrClover/TTdrClover.cxx
libraries/TGRSIAnalysis/TTdrTigress/TTdrTigress.cxx
libraries/TGRSIAnalysis/TZeroDegree/TZeroDegreeHit.cxx

- added new classes TTdrCloverBgo and TTdrTigressBgo (empty classes inheriting from TBgo)
- removed obsolete GetCorrectedTime functions as well as class-specific GetTime functions

 Forgot to add new TTdr*Bgo classes

---

GRSIProof/grsiproof.cxx
include/TBgo.h
include/TGRSIProof.h

Getting GRSIProof to work with split version

---

include/TMnemonic.h
include/TSuppressed.h
libraries/GROOT/GRootBrowser.cxx
libraries/TDataParser/TFragmentMap.cxx

Also removed some debugging output

 Fixed error in TSuppressed where new hits would be created as TDetectorHits, not the setup specific classes

---

include/TDetectorHit.h
libraries/TAnalysis/TDetector/TDetectorHit.cxx
libraries/TFormat/TFragment.cxx
libraries/TFormat/TPPG.cxx
libraries/TFormat/TParsingDiagnostics.cxx
libraries/TFormat/TScaler.cxx
libraries/TLoops/TEventBuildingLoop.cxx
util/html_generator.C

- modified html_generator.C for split version
- Changed time stamp functions:
- GetTimeStamp() returns raw value as read from file.
- GetTimeStampNs() applies time stamp unit and offset to report time stamp in ns.

Small changes

---

include/TEventBuildingLoop.h
libraries/TAnalysis/TDetector/TDetectorHit.cxx
libraries/TFormat/TChannel.cxx
libraries/TGRSIint/TGRSIint.cxx
libraries/TLoops/TEventBuildingLoop.cxx
thisgrsi.csh
thisgrsi.sh
util/Root2Ascii.cxx
util/grsi-config

This commit adds a new utility Root2Ascii to create ascii files from root histograms and addresses issue #1090:
- Added build window parameter to TEventBuildingLoop constructor.
- Suppressing warnings about missing channels in interactive mode.
- Control-c directly exits in interactive mode (instead of having to press it thrice).
- Added a --<detlib>-libs flag to grsi-config.

Addressing issue #1090

---

include/TSortingDiagnostics.h
libraries/TFormat/TSortingDiagnostics.cxx
makefile

Also fixed issue where pcm files wouldn't get moved using -j flag for make.

Added function TSortingDiagnostics::RemovedHits

---

include/TSortingDiagnostics.h
libraries/TFormat/TSortingDiagnostics.cxx

- Fixed and coloured output of TSortingDiagnostics::Print().
- Updated TSortingDiagnostics version.

Fixed TSortingDiagnostics

---

include/TEventBuildingLoop.h
include/TGRSIOptions.h
include/TParsingDiagnostics.h
libraries/TFormat/TParsingDiagnostics.cxx
libraries/TGRSIint/TGRSIOptions.cxx
libraries/TLoops/TEventBuildingLoop.cxx

- Unified channel address maps to use TParsingDiagnosticsData class as per #1113.
- Added flag to skip sorting input.

Addressing issues #1113 and #1109

---

include/TChannel.h
include/TParsingDiagnostics.h
include/TPriorityValue.h
libraries/TFormat/TChannel.cxx
makefile

- Removed TChannel::UpdateChannelNumberMap to fix #1115.
- Changed -links to -maxdepth for find/gfind command in makefile to fix #1118.

Fixing #1115 and #1118

---

libraries/TFormat/TChannel.cxx

- Fixed mistake in trying to use SetupEnergyNonlinearity in static function.
- Added output of energy nonlinearities to TChannel::Print function. This was preventing the nonlinearities to be saved to the root files.

Fixing issues #1145 & #1147

---

libraries/TGRSIProof/TGRSISelector.cxx

Fixed issue with TChannel not written to proof output file

---

include/Globals.h
include/TChannel.h
include/TPriorityValue.h
libraries/TFormat/TChannel.cxx
util/WriteNonlinearitiesCal.cxx

- Added program to convert root file with nonlinearities into cal-file
with only those nonlinearities.
- Removed duplication of code in TChannel by making Print use
PrintToString.
- Added comparison operators to TPriorityValue for direct comparisons.

New program to write nonlinearities from root file as cal file

---

include/GCube.h
include/GHSym.h
include/TChannel.h
include/TPriorityValue.h
libraries/GROOT/GCube.cxx
libraries/GROOT/GHSym.cxx
libraries/TFormat/TChannel.cxx
libraries/TLoops/TDataLoop.cxx
makefile

Also expanded the usability of TPriorityValue a bit ...

Fix for compiling with ROOT >= 6.20 (issue #1155)

---

include/GCube.h
include/GHSym.h
libraries/GROOT/GCube.cxx
libraries/GROOT/GHSym.cxx
libraries/GROOT/GRootFunctions.cxx
libraries/TFormat/TChannel.cxx
libraries/TGRSIint/TAnalysisOptions.cxx
libraries/TLoops/TAnalysisWriteLoop.cxx

Fixes to compile with ROOT 6.24/00

---

include/GCube.h
include/GHSym.h
libraries/GROOT/GCube.cxx
libraries/GROOT/GHSym.cxx

Fixing issue with latest pull and ROOT < 6.24/00

---

include/GCube.h
include/GHSym.h
libraries/GROOT/GCube.cxx
libraries/GROOT/GHSym.cxx
libraries/GROOT/GRootBrowser.cxx
libraries/TDataParser/TDataParser.cxx
libraries/TLoops/TUnpackedEvent.cxx
makefile

- making v3 compile with ROOT 6.24.
- Updated data parser for multiple CAEN modules.

Small updates

---

thisgrsi.csh
thisgrsi.sh

This should solve #1166 when used in combination with UoG-Nuclear-Physics-Group/ILLData#17

Added bin directories of data parser libraries to PATH

---

include/TMnemonic.h
include/TPriorityValue.h
libraries/TAnalysis/TBgo/TBgo.cxx
libraries/TFormat/TMnemonic.cxx
libraries/TLoops/TUnpackedEvent.cxx
util/grsi-config

- Removed linking to xml libraries if xml isn't present on the system.
- Removed std::move for simple pointers.

Some small changes

---

libraries/GROOT/GPeak.cxx
libraries/TAnalysis/TDetector/TDetectorHit.cxx
libraries/TGUI/TSourceCalibration.cxx

C++14 is required to use auto as an argument for a lambda, so for now I just changed it to explicitly state the type.

Changed lambda to work with older ROOT versions

---

include/TBGSubtraction.h
libraries/TGUI/TBGSubtraction.cxx

Created new frame that contains the label and the slider. Zoomed in range of histogram is now preserved when rebinning. For now (?) the slider only allows binning between 1 and 10, could be added as an argument for the constructor instead?

Added binning label and preserving range when rebinning

---

libraries/TAnalysis/TPeakFitting/TPeakFitter.cxx

Changed check for good covariance matrix to be laxer

---

include/TPPG.h
libraries/TFormat/TPPG.cxx

This allows users to check that the ODB information matches the data, and if not, to re-create the ODB information from the data.

Added TPPG functions to check ODB vs data, and to set ODB from data

---

Examples/checklog.sh
Examples/sort.sh
include/TGRSIOptions.h
libraries/TGRSIint/TGRSIOptions.cxx

Added new "Examples" directory with one scripts for sorting data and one to check how the sorting went.

Example scripts for sorting 

---

GRSIProof/FastTimingHistSelector.C
GRSIProof/FastTimingHistSelector.h

These use GValue-files for settings.

First draft of fast timing hist selector

---

examples/ExampleEventHelper.cxx
include/TCalibrationGraph.h
include/TSourceCalibration.h
libraries/TGUI/TCalibrationGraph.cxx
libraries/TGUI/TSourceCalibration.cxx

Started adding simultaneous zooming of the calibration and residual graph but this isn't yet working. Also fixed a mistake in ExampleEventHelper introduced by merging.

Fixed a number of bugs in TSourceCalibration

---

include/TDetectorHit.h
include/TFragment.h
libraries/TAnalysis/TDetector/TDetectorHit.cxx
libraries/TFormat/TFragment.cxx

Moved GetChannelNumber from TFragment to TDetectorHit

---

examples/DirectoryHelper.cxx
examples/DirectoryHelper.hh
include/GValue.h
libraries/GROOT/GValue.cxx
util/PlotVsRun.cxx
util/checkSort.cxx

I've added a new generalized checkSort program that should work with any detector, no matter what data parser library was used. Also some small improvement and fixed bugs in PlotVsRun, GValue, and DirectoryHelper.

Generalized checkSort, debug/improvement of PlotVsRun, GValue, and DirectoryHelper

---

include/GCanvas.h
include/TLevelScheme.h
include/TSuppressed.h
libraries/GROOT/GCanvas.cxx
libraries/TAnalysis/TLevelScheme/TLevelScheme.cxx
libraries/TFormat/TRunInfo.cxx
libraries/TGRSIFrame/TGRSIFrame.cxx
libraries/TLoops/TAnalysisWriteLoop.cxx

This bug prevented the writing of PPG, TRunInfo, etc. to the analysis file. Also continued work on TLevelScheme.

Fixed bug in analysis write loop

---

CMakeLists.txt
include/TUserSettings.h

Also added some documentation about its usage to TUserSettings.

Found a way to get the c++ standard used to compile the current ROOT installation

---

.gitignore
include/ArgParser.h
include/GCanvas.h
libraries/GROOT/GCanvas.cxx

Added class documentation for ArgParser and GCanvas. Also updated .gitignore to show changes to TUserSettings class.

Adding some doxygen documentation

---

.gitignore
doxygen/DoxygenLayout.xml
include/GCanvas.h
include/TNucleus.h
include/TUserSettings.h
libraries/TAnalysis/TNucleus/TNucleus.cxx

TNucleus: Removed code duplication, removing non-alphanumeric characters from input.
GCanvas: Fixed formatting of doxygen comment.
TUserSettings: Added user settings file format to doxygen comment for the class.
Doxygen: Removed the "#include <....h>" line and moved the graphs to after the declarations.

Some improvements to TNucleus and to the doxygen documentation

---

libraries/TAnalysis/TGRSIFit/TMultiPeak.cxx
libraries/TGUI/TSourceCalibration.cxx

Clarified some warning messages and comments.

Minor changes

---

libraries/TAnalysis/TSRIM/TSRIM.cxx

Adjusted how std::ostringstream works to make TSRIM work now.

Fixing TSRIM
