- include/TCal.h
- include/TCalManager.h
- include/TGainMatch.h
- libraries/TGRSIAnalysis/TCal/TCal.cxx
- libraries/TGRSIAnalysis/TCal/TCalManager.cxx
- libraries/TGRSIAnalysis/TCal/TGainMatch.cxx
- TCal and TCalManager are in a state I am happy with. 
- TCalManager only allows you to put one type of derived TCal in at any given time.
- Each TCal has a `TCal::WriteToChannel()` function that must be created, and defines what part of the TChannel is changed (energy coefs, etc.)
- The `TCalManager::WriteToChannel()` function iterates through every TCal in the manager and calls it's respective `WriteToChannel()` function.
- After calling a `Class::WriteToChannel()` function one must still call the `static TChannel::WriteCalFile("calfile.cal")`
> TCal and TCal Manager

- include/TCal.h
- include/TCalManager.h
- include/TGainMatch.h
- libraries/TGRSIAnalysis/TCal/TCal.cxx
- libraries/TGRSIAnalysis/TCal/TCalManager.cxx
- libraries/TGRSIAnalysis/TCal/TGainMatch.cxx
- libraries/TGRSILoop/TGRSILoop.cxx
- users/UserInitObj.h
I have learned that if you have a pointer as a member of a class, that if you Write or Clone an object of the class, ROOT's Streamer facility makes a copy of the object referenced by that pointer, and then sets the new pointer to point to that new memory. I have gotten around this in this specific case by adding a //! after the Channel pointer in TCalManager. The streamer facility then makes a clone of the TCal, but leaves the TChannel pointer pointing at NULL. I then set the pointer to point at the TChannel of the old TCal. @pcbend, I am sure I am just rediscovering what you have already found with the write speed/memory size when we were writing the analysis tree. However, when I was looking into this stuff I found a Class called TRef that might solve my problem as it creates a …
> Fixed bug where a copy of TChannel would be made

- libraries/TGRSIFormat/TFragmentQueue.cxx
I've moved the locking and unlocking of all fragment queues inside the if-statement. We do not need to lock the fragment queues to check if the one we request exists. We might not need any locking at all, since for the only operations we're using on the fragment map right now (count, insert, and at), accessing and modifying existing elements is safe. 
But this way we're only locking the fragment queues once (when our one and only fragment queue is created), and not every single time we get it.
> Reduced number of locks in TFragmentQueue::GetQueue

- src/main.cxx
- src/makefile
Added OS X compatibility defines for UTMPX. (Needed for black and white splash screen).
Updated src makefile for X11 OS X compatibility.
Removed unused $(LFALGS) variable from grsisort compilation.
> OS X Compatibility changes for UTMPX and X11, also minor makefile change.

- libraries/TGRSIFormat/TFragmentQueue.cxx
There was an error in the last change I did, by moving the lock between the calls to map::count and map::insert, it is possible that another thread inserts the same map again. To keep avoiding locking and un-locking too often, I've added another check that map::count returns zero after the locking.
> TFragmentQueue::GetQueue fixed

- include/TCal.h
- include/TChannel.h
- include/TEfficiencyCal.h
- include/TPeak.h
- libraries/TGRSIAnalysis/TCal/TCal.cxx
- libraries/TGRSIAnalysis/TCal/TEfficiencyCal.cxx
- libraries/TGRSIAnalysis/TCal/TGainMatch.cxx
- libraries/TGRSIAnalysis/TGRSIFit/TPeak.cxx
- libraries/TGRSIFormat/TChannel.cxx
- libraries/TGRSIint/TGRSIint.cxx
- users/UserInitObj.h
- util/autoeffic.C
Fixed multiple bugs in TPeak. I also changes the statement that reads the calibration from a tree to tell you how many channels were read, instead of "This was read if it exists". I would like to make it so we can change the cal written to the fragment/analysis trees at some point, but as of right now this requires copying the entire trees and rewriting them (still better than resorting the midas file I guess).
> Bugs in TPeak.

- libraries/TMidas/TMidasFile.cxx
- Changed the reading of the TMidasFile to read from a pipe.
- Increases the read speed by a factor of 4
- tested this and output fragment trees are equal
> Change to Reading in TMidasFile

- util/bufferclean.C
- util/offsetfix.C
- These *should* in principle work now. 
- Had to do high time stamp shifts based on the first timestamp seen by a digitizer.
- I did this due to the "I failed so I'm going to write a 0 word" mentality that our DAQ currently has.
- If this method also fails. I'll come up with something trickier, but until then....
> Fixed bugs in offset fix and bufferclean

- include/TCFDCal.h
- include/TCal.h
- libraries/TGRSIAnalysis/TCal/TCFDCal.cxx
- libraries/TGRSIAnalysis/TCal/TCal.cxx
- libraries/TGRSIAnalysis/TCal/makefile
- This was meant for CFD, but now all TCal's can be written to all channels.
- for any given TCal that has a WriteToChannel function (all of them), one can call WriteToAllChannels(mnemonic), where mnemonic is a string that chooses which channels to write to. For example "GRG" writes to all channels, while "GRG01" writes to the first clover.
1. To set CFD parameters, set all of the TChannels (TChannel::ReadCalFile)
2. TCFDCal * cal = new TCFDCal
3. cal->AddParameter(parameter1)
4. cal->AddParameter(parameter2) etc.
5. WriteToAllChannels(mnemonic)
6. TChannel::WriteCalFile
> Added a WriteToAllChannels function

- util/makefile
- util/offsetfix.C
It's helpful to be a bit more robust that doing a max bin find when the peak will be a bit broader.
> Modified offsetfix to use TSpectrum for final peak fit

- include/TFragmentSelector.h
- This is for people who use the -s command
- Only reads TChannels out of the tree, I believe it will completely ignore Cal files. We don't use this enough to put the time into fixing the problem any more than this.
> Fixed TChannel reading into TFragmentSelector in current version

- libraries/TGRSIFormat/TChannel.cxx
Previously WriteToRoot reopened all files as UPDATE, then reopened again using the original open type.  This caused a warning with CREATE, as you can't reopen with CREATE.  WriteToRoot now reopens as UPDATE iff it was opened READ only, then returns the file to READ only after updating the calibration.
> Changed WriteToRoot to only reopen read only files.

- include/TPeak.h
- libraries/GROOT/GCanvas.cxx
- libraries/TGRSIAnalysis/TGRSIFit/TGRSIFit.cxx
- libraries/TGRSIAnalysis/TGRSIFit/TPeak.cxx
Being able to access the TPeak area from the histogram has been solved. Now the TPeak is fit, and the last function fit is copied to be this peak. If the option "+" is used when fitting the TPeak, the last two functions are copied, as the + option appends the function to the histogram, but then still writes the current function leaving two copies attached until the last one is overwritten by a new fit. That's just the way ROOT does it.
> Accessing TPeak area from histogram

- libraries/TGRSILoop/TGRSILoop.cxx
- This turned out to be caused by a slew std::string = const char* that clang optimized and did not do the proper casting. I think this is a strict aliasing-like problem (I could be wrong, my comp-sci lingo isn't perfect). I have corrected the code to use only const char*. 
- I assume this problem might carry through into epics and other odb read things,. I'll keep my eye out, but other mac users should as well.
> Fixed Clang -O2 optimization problem

- include/GCanvas.h
- include/GRootGlobals.h
- libraries/GROOT/GCanvas.cxx
- libraries/GROOT/GROOTLinkDef.h
- libraries/GROOT/GRootGlobals.cxx
This will attach the TExec to the individual histograms instead of the TCanvas. This appears to be more stable and to label the histograms immediately upon redraw, rather than waiting for an Update command.
> Switching the method of peak label display to a stabler method

- include/TGRSIRunInfo.h
- libraries/TGRSIAnalysis/TAnalysisTreeBuilder/TAnalysisTreeBuilder.cxx
- libraries/TGRSIAnalysis/TGriffin/TGriffin.cxx
- libraries/TGRSIAnalysis/TTigress/TTigress.cxx
- libraries/TGRSIFormat/TGRSIRunInfo.cxx
- libraries/TGRSIint/TGRSIint.cxx
- util/grsiruninfoexample.info
TGRSIRunInfo now contains a Build Window, AddBack Window and Array distance.
This variables do the obvious. They can be changed with a new file type optionally given at either the fragment-sort phase or the analysis-sort phase.  In order for the Auto-File reader function in TGRSIint to work, the file must have the extension .info
An example of this file has been added:  util/grsiruninfoexample.info
Just like the calfile, it is case insensitive and // starts a comment. 
So far, the parsable data is pretty limited, however the frame work from this point on is pretty easy to expand to include more options.  Thanks to some streamer magic, this up is backwards compatible.   In this case the it uses default windows/distance selected by me.
default build time = 2 us
default addback window = 150 …
> bulid windows / addback windows / detector distance interface added

- libraries/GROOT/GCanvas.cxx
Type 3:  High & low gates subtract gates added.  Requires four markers.  The two subtract gates are created from markers3 and markers4 while the Add gate is from marker1 and marker2.  Add gate size is split between the the two gates (i.e. (Marker3 + AddSize/2) and (Marker4 + AddSize/2))  In the case where the Add gate size is odd, the lower gate has the extra bin.  Gates are inclusive.  
Type 4:  BG subtract gate is set static to marker1 and marker2.  Placing marker1 and marker2 and selecting 'b' places a consent subtract gate between the markers.  One can than go on to place the Add gate.  Gates are inclusive.
> Add two more BG subtraction types to GROOT Project

- util/bufferclean.C
- util/offsetfix.C
Updates to both banks of offsetfix 
- Offset fix now checks if you are using subrun 0. This is important because if you are using firmware with 'bank' problems, timestamps can jump dramatically right at the start of subrun 0. Offsetfix now starts looking at event 1E5 in subrun 0, and at the start of the run for the rest. Please make sure that the 1E5 event doesn't just happen to fall at a bad spot and your time_diff spectra still make sense! 
- Split Mezzanines. Setting the SplitMezz flag within offset fix allows you to split the 4G mezzanines as we notices that the two mezzanines within a single 4G could have different time stamps. 
- Default file name. If you don't put an output file name on the command line, offsetfix defaults to putting the prefix 'fix' on the input file name.
> Offsetfix update for new banks, new firmware problems

- libraries/TGRSIFormat/TChannel.cxx
- libraries/TGRSILoop/TGRSILoop.cxx
- libraries/TGRSIint/TGRSIint.cxx
Previously, stdout redirections methods didn't work with utilities like nohup, since they assumed that stdout pointed to /dev/tty.  I am now storing where stdout points, and restoring it later.
> Change to stdout redirection method

- util/offsetfix.C
- This problem could cause the 0x0000 channel to not be corrected on some machines
- Clang is smart enough to realise I'm dumb and I didn't see the problem until I was on a dumb linux machine with gcc
> Fixed a problem in offsetfix

- include/TDataParser.h
- include/TFragment.h
- libraries/TDataParser/TDataParser.cxx
- libraries/TGRSILoop/TGRSILoop.cxx
Parsing multiple midas events with multiple griifin fragments had a strange failure mode.  Because we are double using the number of fragments found as the number of fragment found (if positive) and the error failure (if negative), recursive calling did funny things when the parsing failed mid stream.
It would subtract the number of the failed datum from the number of fragments extracted so far and there was a bit of a race going on to see if the total event would pass or fail.  This has been fixed.  The recursion call has been moved to the grsiloop, errors again get reported correctly (if run without the --suppress_errors flag) to the command line, recovers of the data stream are also noted here.  The logging of errors to a data file has not yet been updated.
Additional funny things are …
> multiple griffin frags per event + errors

- include/TGriffin.h
- include/TGriffinHit.h
- libraries/TGRSIAnalysis/TGriffin/TGriffin.cxx
- libraries/TGRSIAnalysis/TGriffin/TGriffinHit.cxx
I've added the possibility to use on-the-fly addback to TGriffin. The function that decides which TGriffinHits are put into one addback hit can be user-defined, the default is a simple clover addback.
I've run a quick comparison, and (always creating the same spectra), the times are
without addback: real 35s, user 33s, system 0.6s
with clover addback: real 38s, user 37s, system 0.6s
using position addback: real 44s, user 42s, system 0.6s
The last was done by calling (after each AnalysisTree->GetEntry()):
grif->SetAddbackCriterion([](TGriffinHit& one,TGriffinHit& two) {
return ((one.GetPosition() - two.GetPosition()).Mag() < 105. &&
(std.abs(one.GetTime() - two.GetTime()) < TGRSIRunInfo::AddbackWindow()));
> Added on-the-fly addback functionality into TGriffin.

- include/TGRSIDetectorHit.h
- include/TGriffin.h
- include/TGriffinHit.h
- libraries/TGRSIAnalysis/TGRSIDetector/TGRSIDetectorHit.cxx
- libraries/TGRSIAnalysis/TGriffin/TGriffin.cxx
- libraries/TGRSIFormat/TChannel.cxx
- added SetEnergy(double) to TGRSIDetectorHit, this function sets the energy directly and also sets is_energy_set to true
- modified TGRSIDetectorHit::GetEnergy so that in case is_energy_set is true, it returns the energy instead of re-calculating it from the charge
- made addback_criterion static
- TChannel::CalibrateENG(double charge): instead of calculating charge^0 the return value is set to ENGCoefficients[0] and then all other coefficients are added inside a loop from 1.
> Bug fixes for addback.

- include/TSharc.h
- include/TSharcHit.h
- libraries/TGRSIAnalysis/TSharc/TSharc.cxx
- libraries/TGRSIAnalysis/TSharc/TSharcHit.cxx
- libraries/TGRSIAnalysis/makefile
- src/makefile
- Due to complicated structure, Sharc has all of the old data members plus TGRSIDetectorHit members. Some of these are likely redundant. I will let someone who uses this more decide what they want to do.
> Added TSharc and TSharcHit

- include/TDataParser.h
- include/TEpicsFrag.h
- include/TGRSILoop.h
- include/TGRSIOptions.h
- include/TGRSIRootIO.h
- libraries/TDataParser/TDataParser.cxx
- libraries/TGRSIFormat/TEpicsFrag.cxx
- libraries/TGRSIFormat/TGRSIFormatLinkDef.h
- libraries/TGRSILoop/TGRSILoop.cxx
- libraries/TGRSIRootIO/TGRSIRootIO.cxx
- libraries/TGRSIint/TGRSIOptions.cxx
- libraries/TGRSIint/TGRSIint.cxx
* Added a TSCLRFrag, the class def is done TEpicsFrag.  Contains five UInt_t arrays.  4 four griffin scalars one for the data's associated address. Each Entry also contains a MidasTimStamp and MidasId (MidasSerialNumber).
* Added a SCLR bank parser for event type 2 coming for the griffin experiment type.  Parse the input into 4 UInt_t chucks stored in the TSCLRFrag.
* Added  a TSCLRTree to hold the TSCLRFrag.  Data is in parallel to the TFragments (same as epics).
> TSCLRTree and Parser added for Griffin SCLR events.

- include/TGRSIDetectorHit.h
- include/TSceptar.h
- include/TSceptarHit.h
- libraries/TGRSIAnalysis/TCal/TGainMatch.cxx
- libraries/TGRSIAnalysis/TGRSIDetector/TGRSIDetectorHit.cxx
- libraries/TGRSIAnalysis/TSceptar/TSceptar.cxx
- libraries/TGRSIAnalysis/TSceptar/TSceptarHit.cxx
- Data is reused by trees to save time.
- our flags become useless in this mode.
- I have left the relevant code commented out in case we do want to use it in the future
- Maybe we can convince the rooters that this is a good idea?
> Changed to always calculating transient members on the fly... :(

- include/TGriffin.h
- include/TGriffinHit.h
- libraries/TGRSIAnalysis/TGriffin/TGriffin.cxx
- libraries/TGRSIAnalysis/TGriffin/TGriffinHit.cxx
This drops (a particular) analysis tree file size down from 744 MB to 622 MB. There is still some clean up to do with the PPG (like how to implement it), but we will figure that out once it is figured out ont he hardware side.
> Changed TBits to UChar for PPG status

- include/TGRSIDetectorHit.h
- include/TGriffinHit.h
- include/TPacesHit.h
- include/TTigressHit.h
- libraries/TGRSIAnalysis/TGriffin/TGriffinHit.cxx
- libraries/TGRSIAnalysis/TPaces/TPacesHit.cxx
- libraries/TGRSIAnalysis/TTigress/TTigressHit.cxx
So we have 4 allocated bits in the TGRSIDetectorHit. My gut feeling is that the rest of the 4 bits should be open to individual detectors. We can write the enum to have the last 4 bits be called kOBitFlag1, kOBitFlag2 etc. and then have the derived classes set these bits themselves with functions that have sensible names for whatever that detector needs. This also has opened up the required 4 bits for ppg (although we technically only need two and some smartness) on a per hit level...just sayin' that this is now an option... 
Should be last pull request for today...sorry for the emails!
> Added subdetector bit, ie crystal in Griffin and Tigress

- libraries/TGRSIint/TGRSIint.cxx
- makefile
- All calfiles are read in
- Order of cal reading is Trees, cal files left-to-right
- Each successive cal file overwrites the information it holds of the channel to the "left"
- The tree still sorts and automatically writes the **FIRST** cal file input on the command line. The rest of the cal files are loaded after the sort.
- All of the cal files are read before the `--work_harder` flag is called.
- This goes as far as being able to make a `grsisort mycal.cal` call and it will load the TChannels into the current sesh.
- This solves #378 .
> Can now read Calfile from command line always.

- libraries/TDataParser/TDataParser.cxx
Currently, the code only checks for the first word (charge) and assumes the second word is present. One error mode is to have an odd number of charge/cfd words.
-Vinzenz, Jenna
> Adding check for charge/cfd word PAIR

- include/TGRSIFit.h
- include/TGRSIRunInfo.h
- include/TPPG.h
- include/TSceptar.h
- libraries/TGRSIAnalysis/TGRSIFit/TGRSIFit.cxx
- libraries/TGRSIAnalysis/TGriffin/TGriffin.cxx
- libraries/TGRSIAnalysis/TSceptar/TSceptar.cxx
- libraries/TGRSIFormat/TGRSIRunInfo.cxx
- libraries/TGRSIFormat/TPPG.cxx
- libraries/TGRSIRootIO/TGRSIRootIO.cxx
- scripts/LeanMatrices.cxx
- util/AddToChannelNumber.cxx
- util/makefile
- TPPG can now calculate the cycle length: it creates a map with the time difference between consecutive ppg events of the same status and uses the time difference with the maximum counts as cycle length (so far we've seen a loss of about 7% of our ppg events)
- TGRSIRunInfo now includes a run start and stop time in s. For this the fragment trees GetMinimum and GetMaximum is used on the TMidasTimeStamp. This allows us to determine the length of a sub-run without being influenced by "buffer dumps"
- the counting of the fragments in a GRIFFIN addback missed the starting entry, causing it to crash
- Ryan started on adding the option to select a fit function to TGRSIFit
- the LeanMatrices script has been updated for the August 2015 Cd/In decay experiments
> Various bug fixes and improvements.

- include/TGRSIDetectorHit.h
- include/TGRSIRunInfo.h
- include/TPPG.h
- libraries/TGRSIAnalysis/TAnalysisTreeBuilder/TAnalysisTreeBuilder.cxx
- libraries/TGRSIFormat/TGRSIRunInfo.cxx
- libraries/TGRSIFormat/TPPG.cxx
- libraries/TGRSIRootIO/TGRSIRootIO.cxx
- libraries/TGRSIint/TGRSIint.cxx
- scripts/LeanMatrices.cxx
- util/grsi-config
- Added run start,stop and length to TGRSIRunInfo
- Added TGRSIRunInfo Merge function to calculated entire run length for summed up matrix files
- Added PPG Merge and Add functions for summed up matrix files
- Fixed bugs in TPPG Copy, Clear, and dtor
- Added TPPG::Correct function to fix missing and bad PPG words
- Fixed File autodetect to warn of missing input files
- Updated LeanMatrices to work with addback
- PPG in fragment tree currently needs to look for PPG in fragment tree subrun -1 unless it is subrun 0. This might get annoying, and might get changed.
- Removed CSM from grsi-config until CSM makes it into leangrsi
> Updates made during 128,129,130,131,132Cd run

- include/TGRSIFit.h
- include/TPeak.h
- libraries/GROOT/GCanvas.cxx
- libraries/TGRSIAnalysis/TGRSIFit/TGRSIFit.cxx
- libraries/TGRSIAnalysis/TGRSIFit/TPeak.cxx
- libraries/TGRSIFormat/TPPG.cxx
- Ability to turn on/off log-likelihood in TPeak.
- Shift-M/N removes background fits.
- Fixed bug in parameters of TPeak fit...can now do x^2 in background
- Removed warnings from PPG print strings
- Fixed bugs when root does it's garbage collection on TF1's. Apparently root automatically adds ALL TF1's to a global TF1 list, and deletes them from the list when .q is typed. This becomes a problem, when a class inheriting from TF1 contains a TF1, and then deletes that TF1. Root might delete these in the wrong order....
> TPeak Upgrades

- include/TGRSIFit.h
- libraries/TGRSIAnalysis/TGRSIFit/TGRSIFit.cxx
- libraries/TGRSIAnalysis/TGRSIFit/TPeak.cxx
- overwrote delete statement to check the list and remove the current TGRSIFit
- overwrote new[] operator because apparantly the new[] operator on TF1's cause root to die on .q unless one calls delete[] on that TF1 array first. The new[] statment has all of the old functionality with the addition that it yells at you in red to tell you to call delete[].
> Fixed some bugs with the global TF1 list

- include/TGRSIDetectorHit.h
- include/TGriffin.h
- include/TGriffinHit.h
- include/TPaces.h
- include/TPacesData.h
- include/TPacesHit.h
- include/TTigressHit.h
- libraries/TGRSIAnalysis/TGRSIDetector/TGRSIDetectorHit.cxx
- libraries/TGRSIAnalysis/TPaces/TPaces.cxx
- libraries/TGRSIAnalysis/TPaces/TPacesData.cxx
- libraries/TGRSIAnalysis/TPaces/TPacesHit.cxx
- Took away PPG from any mother classes that had them
- removed ppg data member from a few classes which should save completely unused data space
- This works by loading the gDirectory version of "TPPG". I couldn't think of a better way to do this, so this is how it currently is. If someone else has a better idea of where the static TPPG pointer of TGRSIDetectorHit should point, please let me know. 
- There is also currently no direct functionality to change where this pointer points to once it has been set. This can be changed, but for this version I don't really see a reason to do it. If it stops someone from doing something that they want to do, a static SetPPGPtr function can easily be created.
> Added ability to get PPG status and Timestamp in cycle for hits

- .gitignore
- include/TGRSIFit.h
- include/TGRSIFunctions.h
- include/TMultiPeak.h
- include/TPeak.h
- libraries/TGRSIAnalysis/TGRSIFit/TGRSIFit.cxx
- libraries/TGRSIAnalysis/TGRSIFit/TGRSIFunctions.cxx
- libraries/TGRSIAnalysis/TGRSIFit/TMultiPeak.cxx
- libraries/TGRSIAnalysis/TGRSIFit/TPeak.cxx
- libraries/TGRSIAnalysis/TGRSIFit/makefile
- makefile
- Can fit multiple peaks at the same time.
- Uses a vector of centroids as input.
- One can clear all of the parameters of a TGRSIFit using `TGRSIFit::ClearParameters()`. Note that `TGRSIFit::Clear()` nor `TF1::Clear()` do this for you.
Future work:
- Will add a draw that will show deconvolution of the various peaks and background.
- will add a "click-click-(click*n_peaks)-fit" or search fit function
- Will add a residuals draw drop down option
The above will make TPeak more of a container than the actual fitter like we have been using it (although that functionality will remain).
> Initial Push of TMultiPeak

- libraries/TGRSIAnalysis/TGriffin/TGriffinHit.cxx
There were no breaks in the SetCrystal switch statement. This caused the crystals to always be set as white.
> Fixed a mistake in TGriffinHit.cxx

- libraries/TGRSIAnalysis/TGriffin/TGriffinHit.cxx
This would impact the position, time, and address assignments for addback events.
> Fixed incorrect parentheses placement in CompareEnergy function

- include/TAnalysisTreeBuilder.h
- include/TDetector.h
- libraries/TGRSIAnalysis/TAnalysisTreeBuilder/LinkDef.h
- libraries/TGRSIAnalysis/TAnalysisTreeBuilder/TAnalysisTreeBuilder.cxx
- libraries/TGRSIAnalysis/TDetector/TDetector.cxx
- makefile
This was strange.  Changing the EventQueue/WriteQueue from static memebrs to normal memebers in a singleton has taken care of the problem.  Evidently, some of the recent switches caused the linking to change and the linking was controling the delete order on exit.
> Fixed double free corruption error on quit.

- .gitignore
- include/TGRSIRunInfo.h
- libraries/TGRSIFormat/TGRSIRunInfo.cxx
- libraries/TGRSIint/TGRSIint.cxx
This is written in order to read the run info from the gDirectory if there is run info in the gDirectory. You can also pass a pointer to a file, such as `TGRSIRunInfo::ReadRunInfo(_file1);` The old function that @SmithJK changed has been changed to `SetRunInfo(TGRSIRunInfo*);`
I believe the last fragment, or analysis file processed is the RunInfo that is automatically loaded. It works the same as the TChannels except that you never "load in" the run info into a standard session as it is mostly used during sorting time. I'm not sure which run info would be loaded if you put a few analysis files on the command line, and then also sorted a fragment tree. However, I think that in that scenario you can print the runinfo and see which run it is using. Also I don't think it would ever be useful …
> Read RunInfo from file.

- include/TGriffin.h
- include/TGriffinHit.h
- libraries/TGRSIAnalysis/TGriffin/TGriffin.cxx
- libraries/TGRSIAnalysis/TGriffin/TGriffinHit.cxx
- makefile
Once can make the html docs in the directory using `make html`. This might be bad practice... but html has the "all" target meaning the entire program and all scripts must be compiled before the docs are built. The THtml class uses the libraries of the classes, so this needs to take place before the docs are made.
I have also cleaned up Griffin a bit in terms of outdated, commented, code. And I added a couple more html comments into Griffin.
> Updated Makefile for Html Docs

- include/TDecay.h
- libraries/TGRSIAnalysis/TGRSIFit/TDecay.cxx
These can be used in TDecay and a specific Id. For example a TDecay named decay can have all of it's id = 3 decays to  a halflife of 19.1->19.5 set like:
```c++
decay->SetHalfLife(3, 19.3); //Anything between 19.1 and 19.5 will do here.
decay->SetHalfLifeLimits(3,19.1,19.5);
```
FYI @mrdunlop
> Added new limits for halflives

- makefile
- Didn't work on linux mint because order of --no-as-needed matters... sometimes....
http://stackoverflow.com/questions/45135/why-does-the-order-in-which-libraries-are-linked-sometimes-cause-errors-in-gcc
> Fixed order of --no-as-needed linker flag to work on all distros

- util/ErrorReport.sh
This script will help us to find the error you are reporting on the issue tracker. Just use `sh $GRSISYS/util/ErrorReport.sh` We could maybe make this into something that could be executed in grsi-config, I just wanted something quick and dirt for now. When the script is run you get an output like this:
```
SYSTEM = Darwin
GRSISYS = /Users/rdunlop/Programs/GRSISort
ROOTSYS = /usr/local/root_v5.34.30
ROOT Version = 5.34/30
Computer and Path to File that failed:
GRSISort Branch = master
Last Commit:
commit 479204ae1385a874abda8f32bc41eef354e0f20e
Author: Ryan Dunlop <rdunlop@uoguelph.ca>
Date:   Wed Oct 21 11:04:20 2015 -0400
Fixed error reporting script
Put Error Here:
Last Working Commit: Put commit here
What I have tried so far
```
This will help us identify easy to solve problems, and …
> Added error reporting script

- include/Globals.h
- include/TGriffin.h
- libraries/TGRSIAnalysis/TDescant/TDescant.cxx
- libraries/TGRSIAnalysis/TGriffin/TGriffin.cxx
- libraries/TGRSIAnalysis/TPaces/TPaces.cxx
- libraries/TGRSIAnalysis/TS3/TS3.cxx
- libraries/TGRSIAnalysis/TSceptar/TSceptar.cxx
- libraries/TGRSIAnalysis/TSharc/TSharc.cxx
- libraries/TGRSIAnalysis/TSiLi/TSiLi.cxx
- libraries/TGRSIAnalysis/TTip/TTip.cxx
- libraries/TGRSIFormat/TGRSIRunInfo.cxx
- libraries/TGRSIFormat/TScaler.cxx
- src/grsisort.cxx
@pcbend and @VinzenzBildstein can you let me know what you think about this? What I have done is to create an exit exception that should be thrown when we want to quit the program. If you want to exit any compiled script safely you should put a try block around your entire main function code. You can then throw an exit exception whenever you feel like you should abort, catch that in the main, and then choose to do things like close TFiles etc using gROOT. This forces the code to also call the proper dtors as it moves backwards and to clear the heap at the very end. 
The exit_exception I have added checks to see if you have searched beyond the end of your hit vector. You really want to know if you did this because you could have bad results if you do so, so this is not a case of just catch …
> Added custom exception for more transparent error handling

- include/Globals.h
If someone could test this and let me know that would be great.
> Fixes error in exceptions on pre c++11 stds

- include/TDataParser.h
- include/TGRSILoop.h
- include/TGRSIRootIO.h
- include/TScaler.h
- include/TScalerQueue.h
- libraries/TDataParser/TDataParser.cxx
- libraries/TGRSIFormat/LinkDef.h
- libraries/TGRSIFormat/TScaler.cxx
- libraries/TGRSIFormat/TScalerQueue.cxx
- libraries/TGRSILoop/TGRSILoop.cxx
- libraries/TGRSIRootIO/TGRSIRootIO.cxx
- we now throw out events if we see an extra header
- if we encounter an odd number of charge/cfd words we search for the next trailer and throw the error there (effectively throwing out the following fragment which has a corrupt address)
- added a new tree for rate scalers
> Updated to TDataParser, added rate scalers

- include/TDescantHit.h
- include/TGRSIDetectorHit.h
- include/TGriffinHit.h
- include/TPacesHit.h
- include/TSceptarHit.h
- include/TSharcHit.h
- include/TTigressHit.h
- include/TTipHit.h
- libraries/TGRSIAnalysis/TDescant/TDescant.cxx
- libraries/TGRSIAnalysis/TDescant/TDescantHit.cxx
- libraries/TGRSIAnalysis/TGRSIDetector/LinkDef.h
- libraries/TGRSIAnalysis/TGRSIDetector/TGRSIDetectorHit.cxx
- libraries/TGRSIAnalysis/TGriffin/TGriffinHit.cxx
- libraries/TGRSIAnalysis/TPaces/TPacesHit.cxx
- libraries/TGRSIAnalysis/TSceptar/TSceptar.cxx
- libraries/TGRSIAnalysis/TSceptar/TSceptarHit.cxx
- libraries/TGRSIAnalysis/TSharc/TSharcHit.cxx
- libraries/TGRSIAnalysis/TTigress/TTigressHit.cxx
- This makes GRSIDetectorHit members private. I fixed other code that did not assume that.
- Fixes position calls so that they do not recalculate
This works by forcing the user to call GetPosition of the GRSIDetectorHit, which then calls the private virtual GetChannelPosition of the derived detector hit. GetPosition SHOULD NEVER BE OVERRIDDEN for this method to work properly. One can make their own sub-detector checks in their detector classes if they wish.
- @pcbend I was not sure what to do for the sharc position. I am not sure it was ever working. All it did was return fposition which may not have been set. Can you please take a look at this and fix it?
> Fixes position recalculation of GRSIDetectorHits

- include/TBGOData.h
- include/TCrystalHit.h
- include/TGRSIDetectorHit.h
- include/TTigressData.h
- include/TTigressHit.h
- libraries/TGRSIAnalysis/TTigress/TCrystalHit.cxx
- libraries/TGRSIAnalysis/TTigress/TTigress.cxx
- libraries/TGRSIAnalysis/TTigress/TTigressData.cxx
- libraries/TGRSIAnalysis/TTigress/TTigressHit.cxx
- Was that the core was being ignored.
- About to change the charge data member to be an Int_t rather than a Float_t and fix associated issues with this
- Currently in possession of a new Tigress format that will get rid of the need for special subclasses of bgos and segments instead making them separate DetectorHits within the tigress_hits.
> Fixed Tigress energy and charge issues

- include/TChannel.h
- libraries/TGRSIFormat/TChannel.cxx
- Usage for all channels `TChannel::SetUseCalFileIntegration("",true);`
- Usage for a particular mnemonic `TChannel::SetUseCalFileIntegration("TIG",true)` which would set all tigress detectors
or 
`TChannel::SetUseCalFileIntegration("TIG02",true);` which would only due tigress 2
or 
`TChannel::SetUseCalFileIntegration("TIG1",true);` which would only due tigress 10 through 19,
Basically it changes anything with that string within it's mnemonic. It is also strictly case sensitive.
> Added a static SetUseCalFileIntegration to change all channels

- include/TGRSIRunInfo.h
- include/TS3Hit.h
- include/TSiLiHit.h
- include/TTigressData.h
- include/TTigressHit.h
- include/TTip.h
- include/TTipData.h
- include/TTipHit.h
- libraries/TGRSIAnalysis/TPulseAnalyzer/TPulseAnalyzer.cxx
- libraries/TGRSIAnalysis/TSiLi/TSiLi.cxx
- libraries/TGRSIAnalysis/TTigress/TTigress.cxx
- libraries/TGRSIAnalysis/TTigress/TTigressHit.cxx
- libraries/TGRSIAnalysis/TTip/TTip.cxx
- libraries/TGRSIAnalysis/TTip/TTipHit.cxx
- libraries/TGRSIFormat/TGRSIRunInfo.cxx
I've added the SFU waveform fitting to both Tigress and Tip, as needed for the upcoming Tip experiment. I also updated the Tip format (required for it to work) into what I think is the nominal style - hits are now predominantly constructed from the TFragment, rather than the DetData, in the same style as TS3 and TSiLi.
Since the fitting is such a slow process, I have made it optional in the runinfo (default: false). It can be set to be true (or explicitly false) with:
WaveformFit:  1  (or 0)
I also removed a couple of SetEnergy and SetTime functions in the TSiLiHit and TS3Hit classes which were screwing things up.
> Added waveform fitting to Tigress and Tip, added fitting option to runinfo

- include/TGRSIDetectorHit.h
- libraries/TGRSIAnalysis/TGRSIDetector/TGRSIDetectorHit.cxx
- The next little bit we should work on getting the flags forced to 0
- We also need to change the position calls in the hits. This may have been done in a parallel PR, I just haven't looked at it yet.
- This fix only works if the transient members are not being set during build (as per the first bullet point)
> Fixed bug where SetPosition(TVector) set energy flag

- include/TPPG.h
- libraries/TGRSIFormat/TPPG.cxx
- util/offsetfind.cxx
- util/offsetfix.cxx
Changed TPPG::Print to print (short) overview of the ppg, use all as options to print all ppg data. Also changed printf formatting warning in offsetfix/offsetfind, keeping the old format for OS_DARWIN.
> Changed TPPG::Print and removed printf formatting warnings

- include/TAnalysisTreeBuilder.h
- include/TBGOData.h
- include/TCSM.h
- include/TDecay.h
- include/TDescant.h
- include/TDetector.h
- include/TDetectorData.h
- include/TFragmentQueue.h
- include/TGRSIDetector.h
- include/TGRSIDetectorData.h
- include/TGRSILoop.h
- include/TGriffin.h
- include/TGriffinData.h
- include/TPaces.h
- include/TRF.h
- include/TS3.h
- include/TScalerQueue.h
- include/TSceptar.h
- include/TSceptarData.h
- include/TSiLi.h
- include/TTigress.h
- include/TTigressHit.h
- include/TTip.h
- include/TTipData.h
- include/TTriFoil.h
- libraries/TGRSIAnalysis/TDetector/TDetectorData.cxx
- libraries/TGRSIAnalysis/TGRSIDetector/TGRSIDetectorData.cxx
- libraries/TGRSIAnalysis/TGriffin/TGriffinData.cxx
- libraries/TGRSIAnalysis/TSceptar/TSceptarData.cxx
- libraries/TGRSIAnalysis/TTip/TTipData.cxx
The error we had using ROOT 6 on Mac OS was due to the fact that __CINT__ isn't defined anymore in ROOT 6 which made the std::tuple lines in TTigressHit.h visible to rootcint/rootcling. For some reason this is no issue on Linux, but on Mac OS it crashes rootcint. 
So I've replaced the 
#ifndef __CINT__
lines with
#if !defined(__CINT__) && !defined(__CLING__)
Now the code not only compiles on Mac OS, but runs as well. Note that changing the lines in all files might have removed more code from dictionaries when using ROOT 6 than strictly necessary (changing the two lines with std::tuple in TTigressHit.h would have been enough), but this way it's consistent.
> Mac OS and ROOT 6 compatibility

- include/TChannel.h
- libraries/TGRSIAnalysis/TRF/LinkDef.h
- libraries/TGRSIFormat/TChannel.cxx
- libraries/TGRSIFormat/TFragmentSelector.cxx
- libraries/TGRSIRootIO/TGRSIRootIO.cxx
- libraries/TGRSIint/TGRSIint.cxx
- TRFFitter was not being generated, lead to linking error
- Not sure if this was meant to be removed
- This is commonly used for gain matching so it's frustrating to load cal file
- Shouldn't affect anything else
This is to help work being done by @AndrewMac1 and @mrdunlop
> TRF Dict fix, plus hist TChannel Support

- include/TGRSIFunctions.h
- include/TPulseAnalyzer.h
- include/TTipHit.h
- libraries/TGRSIAnalysis/TGRSIFit/TGRSIFunctions.cxx
- libraries/TGRSIAnalysis/TPulseAnalyzer/TPulseAnalyzer.cxx
- libraries/TGRSIAnalysis/TTip/TTip.cxx
- libraries/TGRSIAnalysis/TTip/TTipHit.cxx
Added SFU CsI pulse-shape analysis code to TPulseAnalyzer and set up TTip sensibly so as not to duplicate expensive waveform fitting unnecessarily. Added the CsIFitFunction to TGRSIFunctions so we can draw the fit when needed. Fitting works well and gives lovely PID plots, see below (for a single channel):
> Added SFU CsI pulse-shape analysis code to TPulseAnalyzer

- include/TRFFitter.h
- include/TS3.h
- include/TS3Hit.h
- include/TSiLi.h
- include/TSiLiHit.h
- libraries/TGRSIAnalysis/TS3/TS3.cxx
- libraries/TGRSIAnalysis/TS3/TS3Hit.cxx
- libraries/TGRSIAnalysis/TSiLi/TSiLi.cxx
- libraries/TGRSIAnalysis/TSiLi/TSiLiHit.cxx
This brings TS3 and TSiLi up to date with the changes I made on the master branch.
However TS3 is currently using a building method that may not be approved, but they previous way of doing it on the multiset branch doesnt work.
I am all in favour of getting rid of the data classes, but TS3 cant be built in the AddFragment(), at least not in the way it had been implemented. That way didnt allow for double hits correctly.
As you need to have loaded all fragments before doing even construction I have had to move some of the code back into BuildHits()
I'm collecting the fragments in TS3 members 	std::vector<TFragment*> fS3_RingFragment
and std::vector<TFragment*> fS3_SectorFragment 
I'm doing it with pointers to save on needless copying but I dont know enough about event construction to know …
> TS3 and TSiLi manual merge and changes

- include/TGRSIDetectorHit.h
- libraries/TGRSIAnalysis/TGRSIDetector/TGRSIDetectorHit.cxx
- libraries/TGRSIAnalysis/TGriffin/TGriffin.cxx
- libraries/TGRSIAnalysis/TGriffin/TGriffinHit.cxx
- Makes it so we can't screw up the transient flags.
- IsFlagsSet are const functions and making them public makes debugging easier.
> Fixed flags to write to 0, always. and Made IsFlagSet functions public

- include/TS3.h
- libraries/TGRSIAnalysis/TS3/TS3.cxx
There seemed to be some concern over leaving the TS3 Analysis tree with multiplicity duplicates (as it has been thus far). Anyway I have knocked up something quick as a place holder, it can be improved upon later but it's better than nothing so should make some people happy.
The gates need tweaking and I may add a flags to TS3Hit later to allow people to selectively reject or use the shared strip events depending on the experiment.
> Added some multiplicity filters to TS3

- include/TLMFitter.h
- libraries/TGRSIAnalysis/TGRSIFit/LinkDef.h
- libraries/TGRSIAnalysis/TGRSIFit/TDecay.cxx
- libraries/TGRSIAnalysis/TGRSIFit/TLMFitter.cxx
- util/TestDecay.C
- This is a modified Levenberg-Marquardt non-linear least squares fitter. The base is from numerical recipes with a few changes to be able to approximately reproduce Weighted likelihood fits of poisson distributed data.
- TDecay can now be fitted with the fitter with the option "G" included
- ROOT's weighted likelihood and this method seem to agree now when they did not before (Maybe a root 6 fix?)
- This mean it is worthwhile fitting with both methods. ROOT may yell at you about integration if you don't give it reasonable guesses, so it can help to use the other method anyway.
- Might need a bit of cleanup and expansion to be a true class, such as verbosity arguments, precision, etc., but it works (fairly well).
- This was straight from numerical recipes so I apologize for the overboard …
> Added TLMFitter

- libraries/TDataParser/TDataParser.cxx
the new meaning is NewPPG = requested PPG, OldPPG = read back PPG, trailer = old PPG value (not stored in TPPGData right now)
> Removed check that trailer of PPG repeats the "new" status

- libraries/TGRSIAnalysis/TDescant/TDescant.cxx
- libraries/TGRSIAnalysis/TGriffin/TGriffin.cxx
- libraries/TGRSIAnalysis/TGriffin/TGriffinHit.cxx
- libraries/TGRSIAnalysis/TPaces/TPaces.cxx
- libraries/TGRSIAnalysis/TRF/TRF.cxx
- libraries/TGRSIAnalysis/TSceptar/TSceptar.cxx
- libraries/TGRSIAnalysis/TTigress/TTigress.cxx
- For future reference, no one should touch SetTime, SetEnergy, SetDetector etc (transient members) unless absolutely necessary
- For future reference, bits that are used to set transient members should be set to 0 in the Copy function to force root to write the flags as 0 to disk.
> Fixed setting time and a few flags

- include/TGriffinHit.h
- libraries/TGRSIAnalysis/TGriffin/TGriffinHit.cxx
- This was done in case you wanted to print to screen. There is really no reason to force the return to be a char, even though we want to store it in a single byte.
> PUHit and NPileUps now return shorts instead of char

- include/TAngularCorrelation.h
- libraries/TGRSIAnalysis/TAngularCorrelation/LinkDef.h
- libraries/TGRSIAnalysis/TAngularCorrelation/TAngularCorrelation.cxx
- libraries/TGRSIAnalysis/TGRSIFit/TPeak.cxx
First full push of the angular correlation class. Also first push of an angular correlation wiki page [here](https://github.com/GRIFFINCollaboration/GRSISort/wiki/Angular-Correlations).
I've implemented this assuming an input of a THnSparse populated with 3 axes of angular index, gamma energy, and gamma energy. This object will only be <1 GB if there are ~2.3e8 (or fewer) bins filled.
So we might want to discuss the idea of a wrapper class that wraps a vector to two-dimensional THnSparses.
> Angular Correlation class, version 1.0

- include/TAngularCorrelation.h
- libraries/TGRSIAnalysis/TAngularCorrelation/TAngularCorrelation.cxx
New function lets you use a TObjArray of TH2 or THnSparse (2-dimensional) of gamma-gamma matrices to create angular correlations.
> Angular correlation bug fix and new function

- include/TAngularCorrelation.h
- include/TGRSIDetectorHit.h
- libraries/TGRSIAnalysis/TGRSIDetector/TGRSIDetectorHit.cxx
- libraries/TGRSIAnalysis/TGRSIFit/TGRSIFunctions.cxx
- libraries/TGRSIAnalysis/TPulseAnalyzer/TPulseAnalyzer.cxx
- libraries/TGRSIFormat/TFragment.cxx
- removed a few compiler warnings
- KValues were always copied complete in the TFragment copy constructor, even if a single hit was copied, fixed that
- changed non-transient members of TGRSIDetectorHit from private to protected (so that they can be used in derived classes)
> Various small bug fixes

- include/TAngularCorrelation.h
- libraries/TGRSIAnalysis/TAngularCorrelation/TAngularCorrelation.cxx
- libraries/TGRSIAnalysis/TGRSIFit/TMultiPeak.cxx
I think the default initialization for TMultiPeak should force the peaks to be positive. That's the way I see us regularly using this class.
> Modify TMultiPeak initialization

- libraries/TDataParser/TDataParser.cxx
Fixed bug in data parser, fragment has to be passed first to the diagnostics, then be put in the queue. Otherwise the separate thread emptying the queue might delete the fragment before diagnostics is done with it.
> Fixed bug in data parser

- libraries/TGRSIAnalysis/TAngularCorrelation/TAngularCorrelation.cxx
- libraries/TGRSIAnalysis/TGRSIFit/TMultiPeak.cxx
Some simplifications. Also, expanded integration range for TMultiPeak to 10*width.
> Cleaning up TAngularCorrelations code

- include/TPeak.h
- libraries/TGRSIAnalysis/TGRSIFit/TPeak.cxx
Including new functions in TPeak to let you:
- Calculate the area above the background function, rather than the area of the peak.
- Compare those two calculations of the area.
> New functions in TPeak

- include/TGRSIRootIO.h
- include/TGRSIRunInfo.h
- libraries/TGRSIFormat/TGRSIRunInfo.cxx
- libraries/TGRSIRootIO/TGRSIRootIO.cxx
- libraries/TGRSIint/TGRSIint.cxx
These flags can now be set either in a run-info file, or via command-line. The descant data flag is now the same as the already existing descant flag in TGRSIRunInfo.
> Moved flags for old fragment and descant data to TGRSIRunInfo.

- Deadtime.cxx
The analysis tool "Deadtime" can be used to calculate the channel-by-channel deadtime and the associated uncertainty limits in any GRIFFIN or SCEPTAR channel, or any detector channel for which scaler data is recorded using the precision deadtime scalers. 
"Deadtime" interprets the scaler data recorded during runs where a pulser signal is injected into the detector at different frequencies to test the response. Note that this is not currently a permanent setup of the experiment, and the tests must be setup if and when required. Scaler histograms are produced directly from the ScalerTree in sorted fragments. A list of fragments (separate or merged) and ODB files must be provided. The histograms are analysed and the deadtime results are outputted to a text file (RESULTS.txt). Histograms are …
> Added an analysis tool Deadtime.cxx.

- libraries/TGRSIAnalysis/TPulseAnalyzer/TPulseAnalyzer.cxx
Uncommented the line which called the CsIPID function. Originally commented out because it resulted in an unused variable warning, so I added a (minimal) chi-squared condition so the resulting variable is actually used.
> Uncommented PID line in TPulseAnalyzer added chisq condition

- include/TS3.h
- include/TS3Hit.h
- libraries/TGRSIAnalysis/TS3/TS3.cxx
- libraries/TGRSIAnalysis/TS3/TS3Hit.cxx
In order to give the user a bit more flexibility in their S3 front-back coincidence conditions, we've changed the style of S3 hit construction.
Now, during the analysis tree building stage, we just create RingHits and SectorHits and don't attempt to correlate them. 
Pixels are then constructed by the user, in an analogous method to how we deal with addback in TIGRESS and GRIFFIN. 
This means that users can easily vary their front-back energy/time conditions, should they feel the need, and also means that they actually have access to both the rings and sector energies (previously they only had ring energies). 
Obviously this is less efficient in terms of the file sizes, but I think the benefits outweigh the costs.
New setters:
SetFrontBackEnergy() sets the fractional energy difference …
> Changed S3 hit construction - pixels not built during analysis stage (similar to addback)

- include/TAngularCorrelation.h
- libraries/TGRSIAnalysis/TAngularCorrelation/TAngularCorrelation.cxx
* Changing area error assignment to be chi^2/NDF*sqrt(area) if fit is suspect.
* Fixing indexing bug in `ScaleSingleIndex` function.
* Including "o" option in THnSparse Projection calls.
* Fixed integer casting error in `ScaleSingleIndex` function.
> TAngularCorrelation bug fixes

- examples/grsiruninfoexample.info
- include/TGRSIRunInfo.h
- libraries/TGRSIFormat/TGRSIRunInfo.cxx
changed TGRSIRunInfo::BuildWindow() to return the stored value divided by 10 (to be compared to timestamp differences).
> Fixed default addback window and build window to be in ns

- libraries/TDataParser/TDataParser.cxx
This got somehow dropped (or we never pushed it before), but the 26bit signed integer charge is now correctly converted to a 32bit signed integer (including sign extension).
> Charge is now correctly interpreted as a signed integer

- include/TAnalysisTreeBuilder.h
- include/TChannel.h
- include/TLaBr.h
- include/TLaBrHit.h
- include/TTAC.h
- include/TTACHit.h
- libraries/TGRSIAnalysis/TAnalysisTreeBuilder/TAnalysisTreeBuilder.cxx
- libraries/TGRSIAnalysis/TLaBr/LinkDef.h
- libraries/TGRSIAnalysis/TLaBr/TLaBr.cxx
- libraries/TGRSIAnalysis/TLaBr/TLaBrHit.cxx
- libraries/TGRSIAnalysis/TTAC/LinkDef.h
- libraries/TGRSIAnalysis/TTAC/TTAC.cxx
- libraries/TGRSIAnalysis/TTAC/TTACHit.cxx
- libraries/TGRSIFormat/TChannel.cxx
- libraries/TGRSIFormat/TFragment.cxx
- Requires a `make clean` (or removal of TGRSIAnalysis library), need to figure out why
- I have added a TLabr and TTAC class
- ZDS may or may not work. Is not set up with TAC's yet. This should be a discussion point.
- Both are created when Dante is set to true in run info
- I have a time stamp offset that is set in TChannel now, and TFragment can access. This might slow `GetTimeStamp()` down a bit, but I'll worry about it when it becomes a problem.
- The TimeStampOffset is a double. Not sure if we need this precision, but `TFragment::GetTimeStamp()` still returns an int, so I do not see the harm if we want more precision for `TFragment()::GetTime()` down the road.
- There are no positions in the LaBr, someone may have to add these
- There are no positions for TTAC (kind of nonsensical) …
> LaBr addition

- include/TAnalysisTreeBuilder.h
- include/TChannel.h
- include/TGRSIDetector.h
- libraries/TGRSIAnalysis/TAnalysisTreeBuilder/TAnalysisTreeBuilder.cxx
- libraries/TGRSIAnalysis/TGriffin/TGriffin.cxx
- libraries/TGRSIFormat/TChannel.cxx
Removed mnemonic parsing fro event building. There are still a couple of mnemonic statements in the event building. These will be cleaned out at some point. The performance gain doesn't seem to be huge on our computer at Guelph, but it is being used to sort other data right now, so it is hard to tell. The main change here is that mnemonics only get parsed once per channel, and set in the TChannel.
> Use TChannel to build events

- include/TBgoHit.h
- include/TTigress.h
- include/TTigressHit.h
- libraries/TGRSIAnalysis/TS3/TS3.cxx
- libraries/TGRSIAnalysis/TS3/TS3Hit.cxx
- libraries/TGRSIAnalysis/TTigress/LinkDef.h
- libraries/TGRSIAnalysis/TTigress/TBgoHit.cxx
- libraries/TGRSIAnalysis/TTigress/TTigress.cxx
- libraries/TGRSIAnalysis/TTigress/TTigressHit.cxx
I've (re-)added reasonably flexible BGO suppression to the TTigress class. This required the recreation of the TBgoHits and their storage within TTigress (rather than TTigressHits) to allow for suppression from BGOs belonging to neighbouring detectors. 
Suppression is now done on the fly during GetAddbackMultiplicity(), and is evaluated much in the same way as addback. I've also included a fairly basic suppression as a default. I've tested it with data and it does a good job without oversuppressing good events (I see no loss of events for a 1564-keV gamma-ray in the data I tested).
Suppression is considered on by default, but can be toggled using the SetDoSuppression function, which also resets the addback.
Additionally I fixed a bug in TS3 where the fitted times weren't being copied …
> Add flexible BGO suppression to TTigress

- libraries/TGRSIAnalysis/TGriffin/TGriffinHit.cxx
Not sure if this is correct, but I add up all pileups from the fragments that make up a piled up hit.
> Changed pileup calculations in Addback

- util/gen_version.sh
I was having a problem with compilation arising from the GVersion.h creation on the current master on belodon (CentOS7):
"fatal: No annotated tags can describe 'a4125b4fd59d275ab047ee7c2a75c9b5589ef6aa'.
However, there were unannotated tags: try --tags.
fatal: ambiguous argument '': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
fatal: ambiguous argument '': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
usage: git cat-file (-t|-s|-e|-p|<type>|--textconv) <object>
or: git cat-file (--batch|--batch-check) < <list_of_objects>
<type> can be one of: blob, tree, commit, tag
-t …
> GVersion.h creation fix for CentOS

- include/TDataParser.h
- include/TDescant.h
- libraries/GROOT/GCanvas.cxx
- libraries/GROOT/GRootCommands.cxx
- libraries/GROOT/LinkDef.h
- libraries/TDataParser/TDataParser.cxx
- libraries/TGRSIAnalysis/TDescant/TDescant.cxx
- libraries/TGRSIAnalysis/TZeroDegree/TZeroDegree.cxx
- libraries/TGRSIint/TGRSIOptions2.cxx
- libraries/TLoops/TUnpackingLoop.cxx
- scripts/Deadtime.cxx
- scripts/DescantMatrices.cxx
- both were copying the waveform the wrong way (from the new hit to the fragment), this might be an issue in other classes as well
- TZeroDegree was using the fragments timestamp as address
- both now use TGRSIOptions2::ExtractWaves() instead of their own SetWaves. Maybe at some point we need to separate these out again to have different command line options depending on which detectors waveforms should be analyzed.
- small fixes for compiler warnings and such
> Fixed errors in TDescant and TZeroDegree

- libraries/TGRSIint/TGRSIint.cxx
- libraries/TLoops/TEventBuildingLoop.cxx
This removes the condition that there needs to be a fragment->hist sorting occurring in order to do any other sorting.
> Fixed sorting fragment->analysis

- libraries/TGRSIAnalysis/TGriffin/TGriffin.cxx
- libraries/TGRSIint/TGRSIint.cxx
- Ignoring low-gain griffin events with output sensor "B"
- Renamed fragment and analysis chains to FragmentChain/AnalysisChain so that one can still access the different
fragment/analysis trees of individual files
> Fixes for upcoming experiment

- include/TCSM.h
- include/TDescant.h
- include/TDetector.h
- include/TFragWriteLoop.h
- include/TGRSIOptions.h
- include/TGriffin.h
- include/TLaBr.h
- include/TPaces.h
- include/TS3.h
- include/TSceptar.h
- include/TSiLi.h
- include/TTAC.h
- include/TTigress.h
- include/TTip.h
- include/TTriFoil.h
- include/TZeroDegree.h
- libraries/TGRSIAnalysis/TGRSIDetector/TGRSIDetectorHit.cxx
- libraries/TGRSIint/TGRSIOptions.cxx
- libraries/TGRSIint/TGRSIint.cxx
- libraries/TLoops/TAnalysisWriteLoop.cxx
- libraries/TLoops/TFragWriteLoop.cxx
- we are now copying the fragments/events before writing them, so that we can call ClearTransients on the copy w/o having another thread setting the bit-flags again
- to this effect all detectors that have a collection of hits (i.e. all expect TTriFoil) have now a custom ClearTransients function
> Making sure transients are zero when writing

- makefile
This is an (ugly) way of solving the problem of loading all libraries in the right order. Now we create one single library (called libGRSI.so) that contains the information from all .o files within .build/libraries.
This library ends up being quite large, but it allows us to just load this single library without worrying about the right order to load the individual libraries in.
> Added creation of general libGRSI.so library

- libraries/TGRSIint/TGRSIint.cxx
These loops caused missing events in the analysis stage as fragments were being
removed by the frag_term_loop before they could be built into events.
I'm not sure what these loops were there for in the beginning, so I'm not sure
what kind of behaviour might have been broken by removing them.
> Removed *_term-loops

- .grsirc
- GRSIProof/grsiproof.cxx
- include/TGRSIOptions.h
- include/TGriffin.h
- libraries/TGRSIAnalysis/TGriffin/TGriffin.cxx
- libraries/TGRSIAnalysis/TGriffin/TGriffinHit.cxx
- libraries/TGRSIint/TGRSIOptions.cxx
- There are now calls to functions such as `GetLowGainMultiplicity()`
- All of the old functions still exist ie `GetMultiplicity()`
- The old functions call the default gain type which defaults to `kLowGain` but can be changes with `TGriffin::SetDefaultGainType(kHighGain)` or kLowGain.
- If you try to set it to a type that doesn't exist, you get a warning and nothing changes.
- The vector members written to the tree are now called `fGriffinHighGainHits, fGriffinLowGainHits, fAddbackHighGainHits, fAddbackLowGainHits` so use those appropriately when accessing them directly.
- This breaks griffin analysis trees and the tag index will be incremented appropriately during the next tag. 
- The flag accessors should be written in such a way to allow the fGriffinBits to be moved into TObject.
- …
> Added Low- and High-gain GRIFFIN hits to TGriffin

- include/TFragmentChainLoop.h
- libraries/TGRSIAnalysis/TDetector/TDetector.cxx
- libraries/TGRSIAnalysis/TGRSIDetector/TGRSIDetectorHit.cxx
- libraries/TGRSIFormat/TFragment.cxx
- libraries/TLoops/TFragmentChainLoop.cxx
As long as we only do this in the classes directly derived from TObject, this should work in root6 as well. 
Tested this with root 6.06/04 on run 7270_000 and the file size changed from 51 MB to 45 MB.
> Removed ROOT 6 ifdefs for IgnoreTObjectStreamer

- include/TDescantHit.h
- include/TGRSIDetectorHit.h
- include/TGriffinHit.h
- include/TSceptarHit.h
- include/TZeroDegreeHit.h
- libraries/TGRSIAnalysis/TDescant/TDescantHit.cxx
- libraries/TGRSIAnalysis/TGriffin/TGriffinHit.cxx
- libraries/TGRSIAnalysis/TSceptar/TSceptarHit.cxx
- libraries/TGRSIAnalysis/TZeroDegree/TZeroDegreeHit.cxx
- libraries/TGRSIint/TGRSIOptions.cxx
- libraries/TGRSIint/TGRSIint.cxx
- Fixed compiler warnings in TGriffinHit
- Fixed (cint) compiler warnings in TGriffinHit, TSceptarHit, TZeroDegreeHit, and TDescantHit. This (adding a Copy(TObject&, bool) function) probably has to be done for all the other detectors as well.
- Incremented class version of TGRSIDetectorHit (due to updated fBitflags). Without out this the wrong streamer gets forwarded from an old fragment-tree to a new analysis-tree when re-sorting from fragment-tree.
- Added option to suppress the detailed status messages, leaves a single line of updating progress bars.
> Small fixes for compiler warnings and class version

- include/TAnalysisWriteLoop.h
- include/TEventBuildingLoop.h
- include/TGRSIOptions.h
- include/TGriffinHit.h
- libraries/TGRSIint/TGRSIOptions.cxx
- libraries/TGRSIint/TGRSIint.cxx
- libraries/TLoops/StoppableThread.cxx
- libraries/TLoops/TAnalysisWriteLoop.cxx
- libraries/TLoops/TEventBuildingLoop.cxx
- libraries/TLoops/TFragWriteLoop.cxx
Using the option --separate-out-of-order creates a TTree OutOfOrder in the analysis file. Any fragments that appear out of order (be it timestamp or trigger ID), are not put into an event, but directly send to the OutOfOrder tree.
> Added option to write out-of-order fragments to separate tree in analysis file

- include/TPulseAnalyzer.h
- include/TS3.h
- include/TSiLi.h
- include/TTigress.h
- libraries/TGRSIAnalysis/TPulseAnalyzer/TPulseAnalyzer.cxx
- libraries/TGRSIAnalysis/TS3/TS3.cxx
- libraries/TGRSIAnalysis/TS3/TS3Hit.cxx
- libraries/TGRSIAnalysis/TSiLi/TSiLi.cxx
- libraries/TGRSIAnalysis/TTigress/TTigress.cxx
Mostly changes to the TPulseAnalyzer and a little bit of tidying up.
I was having trouble with the sort speed of my `GetSiliShape()` which calls our older (stolen from SFU)  `fit_newT0()`, the latter was taking exceedingly long time to process so I've patched around, to partially satisfying results.
For one 1GB Midas file -> AnalysisTree sort time:
With `fit_newT0()`, 1:35
Without `fit_newT0()`, 11:03
It's only this noticeable when I'm sorting SiLi singles data, where the entire file is data that needs waveform fitting.
> TPulseAnalyzer patching

- libraries/TGRSIFormat/TGRSIRunInfo.cxx
- libraries/TGRSIint/TGRSIint.cxx
- SetRunInfo(run#, subrun#) only sets the numbers if they are not the defaults (0 and -1, respectively). TGRSIint however called SetRunInfo(0,0). Changed this to SetRunInfo(0, -1).
- I've also added a warning in SetRunInfo if non-default run# or subrun# are overwritten.
> Fixed bug that set all sub-run numbers in analysis file to zero

- GRSIProof/grsiproof.cxx
- include/TGRSIDetectorHit.h
- include/TGRSIOptions.h
- libraries/GROOT/GValue.cxx
- libraries/TGRSIAnalysis/TGRSIDetector/TGRSIDetectorHit.cxx
- libraries/TGRSIFormat/TPPG.cxx
- libraries/TGRSIProof/TGRSISelector.cxx
- libraries/TGRSIint/TGRSIOptions.cxx
- GRSIProof now writes log-files, default is grsisort.log, but that can be changed using --log-file. It also writes the run-info to the histogram file.
- Fixed return value of TGRSIDetectorHit::GetCycleTimeStamp.
- TGRSIDetectorHit now uses TPPG::Get instead of an fPPG member.
- Fixed GValue so that it can read values on single lines as well as those that span multiple lines.
> GRSIProof writes log-file, bug fixes

- GRSIProof/grsiproof.cxx
- include/TDataParser.h
- include/TUnpackingLoop.h
- libraries/TDataParser/TDataParser.cxx
- libraries/TLoops/TUnpackingLoop.cxx
grsiproof only starts the number of threads needed
- if a number of workers has been selected, the argument is directly passed to TProof::Open
- else the normal TProof::Open("") is used, unless --selector-only is being used, in which case 1 worker is used (maybe this should be changed to 0?)
Updated unpacking queue status for lst files 
In the case of lst files, only one event is being read, leading to the situation that the status always showed the unpacking to work on 1/1 events. I've changed this to be the actual number of fragments created out of the number of fragments calculated from the size of the raw event.
> Better unpacking status, grsiproof only starts limited amount of workers

- include/TGRSIDetectorHit.h
- include/TTigressHit.h
- include/TTransientBits.h
- libraries/TGRSIAnalysis/TGRSIDetector/TGRSIDetectorHit.cxx
- libraries/TGRSIAnalysis/TGriffin/TGriffin.cxx
- libraries/TGRSIAnalysis/TGriffin/TGriffinHit.cxx
- libraries/TGRSIAnalysis/TTigress/TTigress.cxx
- libraries/TGRSIAnalysis/TTigress/TTigressHit.cxx
The addback hits where being copied into the addback vector using the copy constructor.  By default this sets the transient bits to zero.  However for a summed addback hit, both the kIsTimeSet and kIsEnergySet flags and coorisponding values must be set.  This pull request fixes this problem for griffin, haven't looked into tigresss yet...
> small griffin addback bug

- include/GHSym.h
- libraries/GROOT/GHSym.cxx
- libraries/GROOT/LinkDef.h
Created base class GHSym and the two derived classes GHSymF and GHSymD. The derived classes use arrays of floats (GHSymF) and doubles (GHSymD) to store the data.
Function GetMatrix() returns a TH2F/TH2D matrix, and function GHSym::Projection(name, firstBin, lastBin, option) projects out a TH1D histogram, similar to TH2::ProjectionX(name, firstBin, lastBin, option).
Drawing the symmetric matrix itself doesn't work yet. It creates a set-fault on the statistics, and if those are not enabled, it draws the bins in a weird order and not symmetric (kind of hard to explain).
I've attached an example plot of a matrix filled with x*y (using the centre of the bins). On the top left the matrix one gets using GHSymD::GetMatrix(), on the top right a standard TH2D matrix. On the bottom one can see the …
> Symmetric matrices

- util/Root2Rad.cxx
- Only applies to 2D-histograms with more than 4096 bins on the x-axis.
- Assumes that the 2D-histograms are symmetric in the x- and y-axis.
- Program checks for -s (split) and -c (compress) flags.
- If both splitting and compression is selected, one matrix with original binning from bin 0 to 4096, and a compressed one with the full range are produced.
- If only compression is selected, the histogram is rebinned so that it has no more than 4096 bins.
- If only splitting is selected, the histogram is split into 4096x4096 matrices. E.g. if the original matrix has 8192x8192 bins, three matrices are created: both x and y from bins 1-4096, both x and y from bins 4097-8192, and one with x from 4097-8192 and y from 1-4096.
> Added GHSym and option to split/compress large matrices to Root2Rad

- libraries/TGRSIFormat/TChannel.cxx
- libraries/TLoops/TUnpackingLoop.cxx
- libraries/TMidas/TMidasEvent.cxx
- scripts/GateBG.C
- scripts/GriffinCTFix.cxx
- TChannel::GetSegmentNumber() assumed that the name of the channel would always be
10 characters long. This lead to a std::out_of_range error when TChannel were written
with names less than 10 characters (like "Empty").
- TChannel::GetSegmentNumber() now sets and returns zero as segment number if the name
has less than 10 characters.
- This fixes the issue #837.
- Also fixed compiler warnings about unused variables.
> Fixed error in TChannel::GetSegmentNumber() 

- libraries/TLoops/TUnpackingLoop.cxx
- libraries/TMidas/TMidasEvent.cxx
- This call was made from TUnpackingLoop::Process which only deals with
raw files. Moving it made a lot of checks easier or unnecessary.
> TMidasEvent::Process calls TMidasEvent::Print on parsing error

- GRSIProof/grsiproof.cxx
- include/GHSym.h
- include/TBadFragment.h
- include/TDataParser.h
- include/TDataParserException.h
- include/TFragWriteLoop.h
- include/TFragment.h
- include/TGRSIDetectorHit.h
- include/TGRSIOptions.h
- include/TGRSIProof.h
- include/TUnpackingLoop.h
- libraries/TDataParser/TDataParser.cxx
- libraries/TDataParser/TDataParserException.cxx
- libraries/TGRSIAnalysis/TGRSIDetector/TGRSIDetectorHit.cxx
- libraries/TGRSIFormat/LinkDef.h
- libraries/TGRSIFormat/TBadFragment.cxx
- libraries/TGRSIFormat/TFragment.cxx
- libraries/TGRSIint/TGRSIOptions.cxx
- libraries/TLoops/TFragWriteLoop.cxx
- libraries/TMidas/TMidasEvent.cxx
- After encoutering an error in parsing, the reason and which word this occured on are stored, but instead of ending here we continue to try and parse the event until the next header is found.
- Bad fragment are stored in their own class, derived from fragments, but with two additional members. The raw data for this fragment up to and including the next header, and the word the parser failed on. These bad fragments have a print-statement that also prints the raw data with the failed word highlighted.
- When the parser fails a TDataParserException is thrown which holds the state of the parser, i.e. why it failed, and the which word it failed on. The exception provides a message with this information.
- Fixed an error in the processing of the midas event where the wrong word was highlighted …
> Improve GRIFFIN data parser

- GRSIProof/grsiproof.cxx
- include/ArgParser.h
- include/GHSym.h
- include/TAnalysisOptions.h
- include/TGRSIOptions.h
- include/TGRSIRunInfo.h
- include/TGRSISelector.h
- include/TGRSIint.h
- libraries/TDataParser/TDataParser.cxx
- libraries/TGRSIAnalysis/TFipps/TFipps.cxx
- libraries/TGRSIAnalysis/TGriffin/TGriffin.cxx
- libraries/TGRSIAnalysis/TS3/TS3.cxx
- libraries/TGRSIAnalysis/TSiLi/TSiLi.cxx
- libraries/TGRSIAnalysis/TTigress/TTigress.cxx
- libraries/TGRSIAnalysis/TTip/TTipHit.cxx
- libraries/TGRSIFormat/LinkDef.h
- libraries/TGRSIFormat/TGRSIRunInfo.cxx
- libraries/TGRSIProof/TGRSISelector.cxx
- libraries/TGRSIint/ArgParser.cxx
- libraries/TGRSIint/LinkDef.h
- libraries/TGRSIint/TAnalysisOptions.cxx
- libraries/TGRSIint/TGRSIOptions.cxx
- libraries/TGRSIint/TGRSIint.cxx
- libraries/TLoops/TAnalysisWriteLoop.cxx
- libraries/TLoops/TEventBuildingLoop.cxx
- libraries/TLoops/TFragWriteLoop.cxx
- src/grsisort.cxx
- util/offsetfix.cxx
- The analysis options are now written to the root files, and read at the start of grsisort. Commandline options overwrite anything in the analysis options that were read from file.
- This also required some changes to the argument parser:
- Moved the definition of the output streamer into a (new) source file.
- Created two different versions of the member function parse, one takes the original int argc, char** argv as arguments, and puts  any unknown flags (and their arguments) into a vector of strings. The second one takes that vector of strings as argument and does throw exceptions if unknown flags are encountered.
- Still need to make sure this works for the PROOF selectors.
- Moved the stopwatch to grsisort.cxx itself, this eliminated the double "bye.bye" message and guarantees …
> Moved Analysis Options from TGRSIRunInfo to TGRSIOptions

- libraries/GROOT/GPeak.cxx
- will investigate this at a later time
This reverts back to the old way of making a copy of GPeak for uncertainty calculations. Still not sure why using the copy ctor would cause this to seg fault. Likely something to do in TF1 constructor calls, and TF1's being drawn/deleted from the pad.
> Fixed weird copy ctor issue in GPeak.

- include/TGRSIFit.h
- include/TMultiPeak.h
- libraries/GROOT/GPeak.cxx
- libraries/GROOT/GValue.cxx
- libraries/TGRSIAnalysis/TGRSIFit/TMultiPeak.cxx
- libraries/TGRSIAnalysis/TNucleus/TNucleus.cxx
- libraries/TGRSIAnalysis/TSRIM/TSRIM.cxx
- libraries/TGRSIFormat/TChannel.cxx
- libraries/TGRSIFormat/TGRSIRunInfo.cxx
- util/gadd.cxx
Changed the `good()` calls to `!fail()` calls.
Got TMultiPeak into a nicer form using functors. It does, however, make some initial guesses on sigma right now which can work really well, or take some manual manipulation. Will fix this soon, needed to get this PR in so that TChannel regained basic functionality.
> Fixes TChannel Parsing issue, TMultiPeak upgrade

- libraries/TGRSIAnalysis/TGRSIDetector/TGRSIDetectorHit.cxx
- Fixes order in which energy calibration occurs. One needs to check if we are forcing the kvalue before we decide to use the one we have in the data.
- We also don't want to calibrate the energy twice if this is the case 😜
> Fixed GetEnergy for use with defined cal file integrations

- include/GCube.h
- include/GHSym.h
- include/TGRSIRunInfo.h
- libraries/GROOT/GCube.cxx
- libraries/GROOT/GHSym.cxx
- libraries/TGRSIFormat/TGRSIRunInfo.cxx
- TGRSIRunInfo now correctly merges the run length
- the run number is only kept if the added files are from the same run
- the start and stop times are only kept if the files are subsequent sub-runs
- also removed shadow-warnings when using GRSIProof by removing code for ROOT 5
> Fixed issues with merging TGRSIRunInfo

- include/TGRSIFunctions.h
- libraries/TGRSIAnalysis/TGRSIFit/TGRSIFunctions.cxx
Added a function to TGRSIFunctions that is the convolution of a gaussian and an exponential decay. This is useful, for example, when you have a TAC with a long half-life. I have already succesfully fitted the 1.4 ns lifetime in Eu-152 with this function
> Convolution (gaussian+decay) function

- include/TAB3Peak.h
- include/TABPeak.h
- include/TPeakFitter.h
- include/TRWPeak.h
- include/TSinglePeak.h
- libraries/TGRSIAnalysis/TGRSIFit/LinkDef.h
- libraries/TGRSIAnalysis/TPeakFitting/LinkDef.h
- libraries/TGRSIAnalysis/TPeakFitting/TAB3Peak.cxx
- libraries/TGRSIAnalysis/TPeakFitting/TABPeak.cxx
- libraries/TGRSIAnalysis/TPeakFitting/TPeakFitter.cxx
- libraries/TGRSIAnalysis/TPeakFitting/TRWPeak.cxx
- libraries/TGRSIAnalysis/TPeakFitting/TSinglePeak.cxx
This is just some stuff I've been working on here and there. It improves how we fit peaks and is a large step up from TPeak and TMultiPeak. This lets you add different types of peak fit functions to the same fit routine, and then easily alter the peak parameters and refit. It also takes care of the covariance matrix properly for every type of peak in the fit as long as you define what is the background portion properly. The impetus of this was getting an "Addback" style peak into the fitting routines. This new method also allows much much easier (not implemented) cross parameter correlation and limiting. It should in principle also allow easier interfacing with a GUI if that ever gets built. There are still a few bugs in using it (you need to have the peak in the range you are fitting or …
> Improved peak fitting

- include/TBgo.h
- libraries/TGRSIAnalysis/TBgo/LinkDef.h
- libraries/TGRSIAnalysis/TBgo/TBgo.cxx
- libraries/TGRSIAnalysis/TBgo/TBgoHit.cxx
- util/grsi-config
Added TBgo class. This class uses the already existing TBgoHits (used to store BGO data in TTigress) to store BGO data. The plan is to add a method than can be used to check if a TGriffinHit or a TLaBrHit is suppressed by the BGO (and whose condition for suppressing can be changed). Not sure yet whether this is the right way to do it (all BGO hits in a single vector), or if we should split the BGO hits up into two vectors, one for "primary" suppressors (aka GRIFFIN suppressors), and one for ancillary suppressors (aka LaBr suppressors).
The advantage of the latter would be an easy implementation of the suppression condition (GRIFFIN detector suppressed by GRIFFIN-BGO of same detector number, and LaBr detector suppressed by LaBr-BGO of same detector number). But it would add a second vector …
> Added TBgo class

- GRSIProof/AngularCorrelationSelector.h
- GRSIProof/ExampleEventSelector.h
- include/TBgo.h
- libraries/TGRSIAnalysis/TBgo/TBgo.cxx
Also change default status width from 80 to 120 characters. This enables the user to see the output of 6 threads, which is the number of threads used for sorting a midas file into fragment and analysis tree.
In addition I've updated the example selector to deal with missing branches, see issue #930.
>  Removed compiler warning from TPeakFitter

- libraries/TGRSIAnalysis/TGRSIDetector/TGRSIDetectorHit.cxx
One line fix. Shouldn't really bother anyone that is using data where they didn't have to force integration parameters, ie GRIFFIN circa 2014.
> Fixed an energy/charge calculation issue when using cal file integration Parameter

- libraries/TDataParser/TDataParser.cxx
- libraries/TDataParser/TFragmentMap.cxx
- libraries/TGRSIFormat/TBadFragment.cxx
This error was introduced with a commit from April 29th 2017 and caused data to be sorted very slow (hours instead of minutes). The resulting fragment file would have many fragments in the BadFragmentTree with failed word -1, because the same fragments would be written again and again (but never deleted from the fragment map).
The changes in TDataParser.cxx are only formatting changes, and in TBadFragment.cxx the failed word for fragments copied into the bad-fragment queue was changed from the default -1 to -2.
> Fixed error where "dropped" fragments weren't removed from the map

- libraries/TGRSIFormat/TChannel.cxx
This allows users to set FileInt to false, which might be necessary due to PR #944.
> Allow un-setting of FileInt

- include/TBGSubtraction.h
- libraries/TGUI/TBGSubtraction.cxx
- Added second background for TBGSubtraction
- Ability to turn different background gates on and off
- Added Update check box to BGSubtraction 
- This increases speed when not interested in performing gating-on-the-fly 
- Default is on-the-fly is off 
- Fitting, and writing is disabled when you are not updating the gates. 
- Allows faster window expansion, gate setting etc, especially with multiple backgrounds 
- This was implemented because I'm not sure it's possible to connect to histogram range expansion without also connection to the window being expanded.
> Added second BG + performance tweaks in TBGSubtraction

- .gitignore
- GRSIProof/grsiproof.cxx
- include/TPPG.h
- libraries/TGRSIAnalysis/TGRSIDetector/TGRSIDetectorHit.cxx
- libraries/TGRSIint/TGRSIOptions.cxx
- util/ErrorReport.sh
Fixes #960 and #884 
- Updated ErrorReport.sh to contain a guess of the OS.
- Updated .gitignore to exclude any ROOT 6 style dictionaries (*.pcm).
- TGRSIOptions now uses the program name (from argv[0]) to check which options are added to the rgParser object.
> TGRSIDetectorHit::GetTime now uses TChannel::CalibratedCFD

- .grsirc
- makefile
- util/gen_grsirc.sh
The new util/gen_grsirc.sh script also creates an error if ROOT versions lower than 6 are being used.
> Change .grsirc prompt color based on root version. Fixes #958

- include/TSiLiHit.h
- libraries/TGRSIFormat/TChannel.cxx
Took me far longer than it should have to work out what had happened to my gamma spectra.
I have quadratic calibration terms that are ~1E-8 which were being zeroed by WriteCalFile.
I've put an exception in as I understand that generally its easier to read things not in scientific notation when it isnt needed.
This might only be a problem for tigress with the different standards for charge integration, but give we deal with numbers on a wide scale, this is something to keep an eye on, make sure we aren't formatting away precision elsewhere.
> Write Cal File format exception

- include/TChannel.h
- include/TPriorityValue.h
- libraries/TGRSIFormat/TChannel.cxx
- Added explicit copy constructor
- Changed std::vector<TChannel> in WriteCalFile and WriteCTCorrections
functions to std::vector<TChannel*>
- Added call to Clear() at beginning of all constructors
- Simplified loops over channel map using auto and range for-loops
- Removed some commented out code
Added reset functions to TPriorityValue and removed check for default priority when setting values.
> More fixes to make TChannel work with TPriorityValues

- util/WriteCalToRoot.cxx
New call of the program is:
WriteCalToRoot <update/replace> <calfile.cal> <root file(s)>
> Added option for WriteCalToRoot program to update calibration instead of replacing them

- libraries/TGRSIint/TGRSIint.cxx
When trying to run a macro by calling ```grsisort <name>.C``` the macro would fail to execute. This was solved by removing the trailing semi-colon of the command line sent to ROOT.
> Fixed bug when executing macros from command line

- GRSIProof/grsiproof.cxx
- include/TGRSIRunInfo.h
- include/TPPG.h
- include/TParsingDiagnostics.h
- include/TSingleton.h
- include/TSortingDiagnostics.h
- libraries/TGRSIFormat/LinkDef.h
- libraries/TGRSIFormat/TEpicsFrag.cxx
- libraries/TGRSIFormat/TGRSIRunInfo.cxx
- libraries/TGRSIFormat/TPPG.cxx
- libraries/TGRSIFormat/TParsingDiagnostics.cxx
- libraries/TGRSIFormat/TSortingDiagnostics.cxx
- libraries/TGRSIProof/TGRSISelector.cxx
- libraries/TGRSIint/TGRSIint.cxx
- libraries/TLoops/StoppableThread.cxx
- libraries/TLoops/TAnalysisWriteLoop.cxx
- libraries/TLoops/TDataLoop.cxx
- libraries/TLoops/TFragWriteLoop.cxx
- libraries/TMidas/TMidasEvent.cxx
- New class TSingleton<T> provides templated base-class for singletons
that are written to file. The Get() function automatically reads
from the current file, keeping the information updated even in a
loop over input files (such as used with grsiproof).
- Adding a new class involves
- including the TSingleton.h header,
- changing the base to TSingleton<T>,
- adding TSingleton<T> as a friend class (might not be needed?),
- removing old Get() function and static pointer to instance,
- updating class definition version,
- adding ```#pragma link C++ class TSingleton<T>-;``` to
libraries/TGRSIFormat/LinkDef.h,
- constructors must now call TSingleton<T> constructor instead of
TObject constructor, and
- existing static WriteToRoot functions must be modified to be
in the right directory before …
> Working version of TSingleton

- GRSIProof/grsiproof.cxx
- include/TGRSIOptions.h
- include/TGRSIRunInfo.h
- include/TPPG.h
- include/TSingleton.h
- libraries/TGRSIFormat/LinkDef.h
- libraries/TGRSIFormat/TEpicsFrag.cxx
- libraries/TGRSIFormat/TGRSIRunInfo.cxx
- libraries/TGRSIFormat/TPPG.cxx
- libraries/TGRSIProof/TGRSISelector.cxx
- libraries/TGRSIint/TAnalysisOptions.cxx
- libraries/TGRSIint/TGRSIOptions.cxx
- libraries/TGRSIint/TGRSIint.cxx
- libraries/TLoops/TAnalysisWriteLoop.cxx
- libraries/TLoops/TDataLoop.cxx
- libraries/TLoops/TFragWriteLoop.cxx
- libraries/TMidas/TMidasEvent.cxx
- util/AddToChannelNumber.cxx
- New class TSingleton<T> provides templated base-class for singletons
that are written to file. The Get() function automatically reads
from the current file, keeping the information updated even in a
loop over input files (such as used with grsiproof).
- Adding a new class involves
- including the TSingleton.h header,
- changing the base to TSingleton<T>,
- adding TSingleton<T> as a friend class (might not be needed?),
- removing old Get() function and static pointer to instance,
- updating class definition version,
- adding ```#pragma link C++ class TSingleton<T>-;``` to
libraries/TGRSIFormat/LinkDef.h,
- constructors must now call TSingleton<T> constructor instead of
TObject constructor, and
- existing static WriteToRoot functions must be modified to be
in the right directory before …
> merge of TSingleton class branch

- include/TS3.h
- include/TS3Hit.h
- libraries/TGRSIAnalysis/TS3/TS3.cxx
- libraries/TGRSIAnalysis/TTigress/TTigress.cxx
The BGO data for TTigress wasnt being saved to analysis tree.
This may have been intentional as the useful part (setting BGO hit on TTigressHit) is done during event construction.
It's easy enough to comment out the line I've added if someone wants to save that bit of disk space.
Also added a function to reset the S3 ring & sector numbers. Saves unnecessary resort in the case of mnemonic corrections.
> BGO saving and S3 mnemonic

- libraries/TGRSIAnalysis/TGRSIFit/TPeak.cxx
When I run my GRSISort function, it may attempt to fit a TPeak to an empty range (for some datafiles). Instead of the expected bahavior (return false to indicate a failed fit), the TPeak->Fit function segfaults.
Output:
```
Warning in <ROOT::Fit::FillData>: fit range is outside histogram range, no fit data for xaxis
Warning in <Fit>: Fit data is empty 
Warning in <ROOT::Fit::FillData>: fit range is outside histogram range, no fit data for xaxis
Warning in <Fit>: Fit data is empty 
Error in <TFitResultPtr>: TFitResult is empty - use the fit option S
*** Break *** segmentation violation
```
Using the fit option S does not fix the issue, the same errors are dislpayed.
I fixed the error by checking if the premininary fits in TPeak->Fit exited successfully (they are the source of the first 4 …
> Fix TPeak segfault when attempting to fit a range with no data

- include/TS3Hit.h
- libraries/TGRSIAnalysis/TTigress/TTigress.cxx
A line in the tigress code for checking B vs A core had a case issue.
`if(hit->GetName()[9] == 'a')`
It seems at some point in the past a/b were lowercase, and this line got missed during iterations.
The result was that ~10% of data replaced the A core with B core, which is a problem as often the B core is un-calibrated/set to 0.
I've checked with some recent 2017 erbium data and @jhenderson88 looked at some older Mg data. We both found this had cause a ~10% data loss, which does not appear to be energy correlated.
This could still be a problem for other TIGRESS analysis as presumably there may be some correlations with combinations of events in the DAQ as to which core A or B is processed first.
I have updated the section to centralise things to the mnemonic class …
> Tigress B core case mistake

- include/TTigress.h
- libraries/TGRSIAnalysis/TS3/TS3.cxx
- libraries/TGRSIAnalysis/TS3/TS3Hit.cxx
- libraries/TGRSIAnalysis/TTigress/TTigress.cxx
There was some confusion during the setting up for the upcoming TIGRESS experiment regarding the S3 position codes, this caused some delays while double checking detector mapping problems.
I've added some additional comments which should hopefully reduce the problem in the future.
I've also changed the way the TIGRESS position function works in order to add some extra debugging functionality (which turned out not to be needed ...)
I'm doubt there is any computational advantage to having the vectors built once rather than every time they are called as I have it done now, but it seemed neat at the time.
> S3 comments and modifications to TIGRESS position

- include/TBgo.h
- include/TGriffinBgo.h
- include/TGriffinBgoHit.h
- include/TLaBrBgo.h
- include/TLaBrBgoHit.h
- include/TTdrCloverBgo.h
- include/TTdrCloverBgoHit.h
- include/TTdrTigressBgo.h
- include/TTdrTigressBgoHit.h
- libraries/TDataParser/TDataParser.cxx
- libraries/TGRSIAnalysis/TBgo/LinkDef.h
- libraries/TGRSIAnalysis/TBgo/TBgoHit.cxx
- libraries/TGRSIAnalysis/TBgo/TGriffinBgo.cxx
- libraries/TGRSIAnalysis/TBgo/TGriffinBgoHit.cxx
- libraries/TGRSIAnalysis/TBgo/TLaBrBgo.cxx
- libraries/TGRSIAnalysis/TBgo/TLaBrBgoHit.cxx
- libraries/TGRSIAnalysis/TBgo/TTdrCloverBgo.cxx
- libraries/TGRSIAnalysis/TBgo/TTdrCloverBgoHit.cxx
- libraries/TGRSIAnalysis/TBgo/TTdrTigressBgo.cxx
- libraries/TGRSIAnalysis/TBgo/TTdrTigressBgoHit.cxx
- libraries/TGRSIAnalysis/TGriffin/TGriffin.cxx
- libraries/TMidas/TMidasEvent.cxx
New detector specific BgoHit classes overwrite the GetArrayNumber function. The detector specific Bgo classes themselves add new fragments as such hits.
Also fixed some compiler warnings and a potential bug in TMidasEvent::IterateBank32.
> New detector specific BgoHit classes

- GRSIProof/CrossTalk.C
- util/GriffinCTFix.cxx
In CrossTalk.C, changed histogram binning and ranges from `7000,0,7000` to `1500,0,1500` and changed TH2F to TH2I.
In GriffinCTFix.cxx, added `delete cmat` and added detector number to name of `pxfit` histograms.
Both of these will decrease memory usage and fix memory leak warnings.
> CrossTalk Memory Updates

- .gitignore
- include/TDetectorHit.h
- include/TGRSIint.h
- libraries/TGRSIAnalysis/TDetector/TDetectorHit.cxx
- libraries/TGRSIint/TGRSIint.cxx
- libraries/THistogramming/DynamicLibrary.cxx
Now the path and version of the library get printed whenever grsisort is started with a library provided via command line argument or .grsirc (whether raw data files are processed or not).
>  Added TGRSIint::OpenLibrary and calling it at start of grsisort

- include/TChannel.h
- include/TDetectorHit.h
- libraries/TGRSIAnalysis/TDetector/TDetectorHit.cxx
- libraries/TGRSIFormat/TChannel.cxx
- libraries/TGRSIFormat/TRunInfo.cxx
- libraries/TGRSIint/TAnalysisOptions.cxx
- libraries/TGRSIint/TGRSIOptions.cxx
- libraries/TGRSIint/TGRSIint.cxx
- libraries/TLoops/TAnalysisWriteLoop.cxx
- libraries/TLoops/TFragWriteLoop.cxx
- new function TChannel::FindChannelByRegEx returns vector of channels
that match the supplied regular expression (see #1051)
- changed default GetArrayNumber function to return detector number.
This function is overwritten by detectors that have cyrstals/segments.
>  Changed names of objects written to file not to be class names

- include/TChannel.h
- include/TGRSIint.h
- include/TMnemonic.h
- libraries/TGRSIAnalysis/TDetector/TDetectorHit.cxx
- libraries/TGRSIFormat/TChannel.cxx
- libraries/TGRSIFormat/TMnemonic.cxx
- libraries/TGRSIint/TGRSIint.cxx
See also GRIFFINCollaboration/GRSIData#9.
- Added LibraryInit function that sets the mnemonic class for the
TChannel to the appropriate choice for the library. This function is
called immediately after opeing the library.
- The parser libraries EnumerateDigitizer now produces warning message
if string is not recognized.
- Instead of taking a string and returning the digitizer enum class
EnumerateDigitizer now takes the name and type of the digitizer as
TPriorityValue references as arguments (return value is void).
- EDigitizer is not part of the TMnemonic namespace anymore and is
defined only within the data parser library.
>  Fixed issues with digitizer type

- include/TFragment.h
- include/TGRSIOptions.h
- libraries/TDataParser/TFragmentMap.cxx
- libraries/TGRSIAnalysis/TPeakFitting/TPeakFitter.cxx
- libraries/TGRSIFormat/TParserLibrary.cxx
- Fixed mistake in TFragmentMap where the charge/k-value were set wrong in the case where only two correct charges were found for two piled-up hits (should only affect a very small fraction of data if any at all).
- Changed fNumberOfPileups in TFragment from UShort_t to Short_t. The negative numbers are used in the TFragmentMap to distinguish different cases of pileups.
- Added check to TPeakFitter::Fit if any peaks have been added (instead of just seg-faulting).
> Small bug fixes

- GRSIProof/CrossTalk.C
- include/TGRSIOptions.h
- libraries/TGRSIint/TGRSIOptions.cxx
- Changed CrossTalk.C to use suppressed data as per issue #1058
- Added new flag 'ignore-odb-channels'
- This flag ignores any channel information in the ODB.
- Unlike the '--ignore-odb' flag, this flag still reads the run information and the EPICS settings from the ODB.
- This should solve an issue with old/wrong settings in the ODB creating a lot of output along the lines 'Warning, digitizer type '' not recognized ...'.
> Using suppressed data in CrossTalk.C and new flag --ignore-odb-channels

- GRSIProof/grsiproof.cxx
- include/GCanvas.h
- include/TGRSISelector.h
- libraries/GROOT/GCanvas.cxx
- libraries/TGRSIProof/TGRSISelector.cxx
- GRSIProof reads cuts from all supplied "cut files". The cut files are determined by TGRSIOptions::InputCutFiles which returns all files with extension .cuts provided on the command line.
Don't know what these files were originally intended for, but now those are just re-named root-files.
- TGRSISelector tries to open all files provided by GRSIProof as "cut files" and reads any TCutG object from them. These are stored in a map, mapping the TCutG pointer to the name of the cut.
- GCanvas now has three more short cuts:
- i: initialize cut, prompting for a name, using single clicks to add points, and double click to finish/close the cut.
- c: create the cut, using the previously initialized object "CUTG".
- s: save cuts, prompting for a file name, default is CutFile.cuts.
> Added capability to create cuts and use them in GRSIproof

- include/TGRSIOptions.h
- include/TPeakFitter.h
- include/TSinglePeak.h
- libraries/GROOT/GCanvas.cxx
- libraries/TAnalysis/TPeakFitting/TAB3Peak.cxx
- libraries/TAnalysis/TPeakFitting/TABPeak.cxx
- libraries/TAnalysis/TPeakFitting/TPeakFitter.cxx
- libraries/TAnalysis/TPeakFitting/TRWPeak.cxx
- libraries/TAnalysis/TPeakFitting/TSinglePeak.cxx
- libraries/TFormat/TChannel.cxx
- libraries/TGRSIint/TGRSIOptions.cxx
- Saving cuts updates the file instead of overwriting and preserves the directory root is in.
- Removed double printing of cfd parameters in TChannel.
- TChannel now uses %e instead of %f only for parameters with small absolute values instead of all negative values.
- Added check to peaks if parameters were set by user, should fix #1096.
- Renamed fInputCutsFiles to fInputCutFiles in TGRSIOptions.
> Several small bug fixes

- libraries/TAnalysis/TPeakFitting/TABPeak.cxx
- libraries/TAnalysis/TPeakFitting/TPeakFitter.cxx
- thisgrsi.csh
- thisgrsi.sh
- TPeakFitter::Fit stores the current zoom of the histogram, then
changes the zoom to its own range, fits the histogram, and zooms back
to the original zoom at the end. Also added a check if the fit result
is good to prevent seg faults.
- Fixed mistake in TABPeak where parameters were initialized wrong
(introduced in PR #1097).
- Also changed thisgrsi.sh and thisgrsi.csh to automatically add detector libraries to LD_LIBRARY_PATH (thisgrsi.csh not tested!).
> Fixing #1098

- GRSIProof/grsiproof.cxx
GRSIProof now also uses the .grsirc file to determine the parser library to use.
> Fixing issue #1101

- include/TChannel.h
- include/TDetectorHit.h
- libraries/TAnalysis/TDetector/TDetectorHit.cxx
- libraries/TAnalysis/TGRSIFit/TMultiPeak.cxx
- libraries/TFormat/TChannel.cxx
- util/html_generator.C
- Added TEmma to html generator.
- Added message that TMultiPeak is deprecated.
- Moved energy nonlinearity to TChannel (see #874 and GRIFFINCollaboration/GRSIData#25).
- Nonlinearity is now stored as TGraph in the TChannel and written as a single line with alternating x and y values to the cal-file.
- Uses linear interpolation for points between minimum and maximum x-value, otherwise (or if no points were provided) returns zero.
> Small improvements

- include/TRuntimeObjects.h
- libraries/THistogramming/TCompiledHistograms.cxx
- libraries/THistogramming/TRuntimeObjects.cxx
- libraries/TLoops/TAnalysisWriteLoop.cxx
- libraries/TLoops/TAnalysisWriteLoopClient.cxx
- Removed dynamic casting by only letting the fObjects list get filled with directory names. The histograms are then found by searches within a TDirectory. In principle, a crash can occur if you fill a directory with a TH1 and TH2 of the same name. However, as of right now, I'd prefer the crash (maybe add a warning?) compared to the alternative of quietly doing the wrong thing that a dynamic cast may allow for. The removal of dynamic casts significanlty improved the performance of the code.
-Removed directory cd'ing. Not sure what it did other than take up a lot of time.
> Speeds up Analysis tree writing.

- include/TChannel.h
- include/TParsingDiagnostics.h
- include/TSortingDiagnostics.h
- libraries/TAnalysis/TCal/TCal.cxx
- libraries/TFormat/TChannel.cxx
- util/AddToChannelNumber.cxx
- util/ScaleCalibration.cxx
- This should speed up first-time channel lookups.
- Impact is likely minor on most data sets, but could be larger when dealing with a couple though thousand BGO channels. 
- map lookup complexity is O(logN), unordered map is optimally O(1) with worst-case O(N). Our use should be close to optimal for hashing.
- **UPGRADING TO THIS VERSION MEANS DETECTOR LIBRARIES MUST BE UPDATED!**
- Quickly tried to implement for TGRSIMap, but failed due to something strange with templating.
> updated TChannel to hold an unordered_map rather than map

- include/GCanvas.h
- libraries/GROOT/GCanvas.cxx
- libraries/TGUI/TBGSubtraction.cxx
Changed GMarker to not store independent x/y coordinates and bins but
use values from the TLines instead.
This means that changing the TLines (by dragging them on the canvas)
changes the GMarker values now, e.g. when fitting a histogram. It also
means that one has to provide the histogram the marker refers to either
via the constructor, or afterwards via the GMarker::SetHist function.
Failure to do so results in a segmentation violation if e.g. asking for
the position of the marker in bins (these functions do not yet check if
the histogram pointer has been set).
> Fixing #1124

- include/TDetector.h
- include/TDetectorHit.h
- libraries/TAnalysis/TDetector/TDetector.cxx
- libraries/TFormat/TChannel.cxx
- libraries/TLoops/TUnpackedEvent.cxx
This also has the (preliminary) fix for issue #1123.
> Deep copy & destructor fixed for TDetector

- GRSIProof/grsiproof.cxx
- include/TGauss.h
- libraries/GROOT/GCanvas.cxx
- libraries/TAnalysis/TPeakFitting/LinkDef.h
- libraries/TAnalysis/TPeakFitting/TGauss.cxx
- libraries/TFormat/TChannel.cxx
- libraries/TGRSIProof/TGRSISelector.cxx
- libraries/TLoops/TAnalysisWriteLoopClient.cxx
- util/Spe2TBrowser/load_spe.C
- Removed obsolete warning from grsiproof that cal-files can't be used.
- Fixed a bug in GCanvas where toggling the z-axis to or from logscale
would change the range of the y-axis.
1D-histograms can now be toggled to logscale using the y key as well
(and not just the l key).
- TChannel::WriteToRoot returns 0 if no channels are found instead of
trying to write them (and crashing).
- TGRSISelector writes TChannel to the output file (not working yet!).
- Fixed some bugs in load_spe.C script.
- Added simple gaussian peak.
> Changes from S1602 and simple gaussian peak

- GRSIProof/CrossTalk.C
- GRSIProof/CrossTalk.h
- GRSIProof/grsiproof.cxx
- include/Globals.h
- include/TGRSIMap.h
- include/TGRSIProof.h
- libraries/TFormat/TChannel.cxx
- @AndrewMac1 fixed the cross talk selector, it hadn't been tested after changing it to use suppressed hits.
- Added checks in grsiproof to avoid some crashes or at least give a clearer message instead.
- Changed TGRSIMap to use std::map instead of inheriting from it (apparently STL containers do not have virtual destructors, so inheriting from them is a bad idea). Might want to change this to an unordered_map?
- Added a global function PrintBacktrace to do just that. It takes an ostream and number of frames as arguments, default are std::cout and 63.
> Updates to grsiproof and fixed cross-talk selector

- libraries/TFormat/TChannel.cxx
We need to check whether the class of the object the key is referring to inherits from TGraph, not the class of the key itself.
> Fixed bug in TChannel::ReadEnergyNonlinearities

- include/TAnalysisOptions.h
- libraries/TFormat/TChannel.cxx
- libraries/TGRSIProof/TGRSISelector.cxx
- libraries/TGRSIint/TAnalysisOptions.cxx
- libraries/TGRSIint/TGRSIOptions.cxx
- makefile
- This should fix issue #1154.
- Also added targets to makefile which compile single or all present parser libraries from the $GRSIYS directory (need update to the library makefiles!).
- Disabling of word count check (```--word-count-offset=-1```) is now part of the ```--recommended``` flag.
- Updated the TAnalysisOptions::WriteToFile and TChannel::WriteToRoot functions. No functional change (I hope), just adding a few checks and changing printf to std::cout.
> Fixed issue with cross talk correction in grsiproof

- include/Globals.h
- libraries/TAnalysis/TDetector/TDetector.cxx
This bug was found because TDescantHits read from file would have fCcShort set to zero even though non-zero values should have been written to file. The issue was traced back down to the way we copied the hits of a detector in the TDetector::Copy function. Using the virtual TDetectorHit::Copy function instead of the assignment operator solved this issue.
This might also solve issue #1142, but I still have to test that.
> Fixing issue with copying detector hits

- GRSIProof/GriffinKValueSelector.C
- GRSIProof/GriffinKValueSelector.h
- GRSIProof/grsiproof.cxx
- include/TDetectorHit.h
- include/TGRSIMap.h
- libraries/TDataParser/TFragmentMap.cxx
- util/PlotGriffinKValue.C
- util/Root2Rad.cxx
- Calling AtExitHandler at the end of grsiproof explicitly in case the program crashes on exiting.
- Added ability to traverse directories in root-files to Root2Rad.
- Removed the fix to check for nullptr channels from TDetectorHit since it's not necessary anymore after #1182.
- TFragmentMap now uses the k-values for minimized pile-up charges (first one for the first hit, second one for the second hit, and so on) as discussed in #973. Also added selector and a simple plot script to check the k-values as discussed in that thread.
> Number of small improvements

- include/GCanvas.h
- include/GPeak.h
- include/TGRSIFunctions.h
- include/TPeakFitter.h
- libraries/GROOT/GCanvas.cxx
- libraries/GROOT/GGaus.cxx
- libraries/GROOT/GPeak.cxx
- libraries/TAnalysis/TGRSIFit/TGRSIFunctions.cxx
- libraries/TAnalysis/TGRSIFit/TPeak.cxx
- libraries/TAnalysis/TPeakFitting/TPeakFitter.cxx
TPeakFitter, TPeak, GPeak, and GGaus now all check if any parameter got close to its limits by comparing the parameter error with the square root of the corresponding diagonal element of the covariance matrix. If a parameter is close, the peak will be fit again using the "E" option to use the minos technique for error estimation. If this also fails and the option "retryfit" has been passed along, the fit will be repeated again without any parameter limits.
I also updated the wiki page about fitting to reflect these changes.
Went over the wiki page about interactive analysis and updated the list of GCanvas hotkeys and cleaned up the GCanvas code a bit.
> Fixing issue #1197

- libraries/TAnalysis/TDetector/TDetector.cxx
- libraries/TAnalysis/TDetector/TDetectorHit.cxx
- libraries/TAnalysis/TNucleus/TGRSITransition.cxx
- libraries/TFormat/TBadFragment.cxx
- libraries/TFormat/TFragment.cxx
- libraries/TGRSIint/TAnalysisOptions.cxx
- libraries/TGRSIint/TGRSIint.cxx
- makefile
This bug was introduced when ROOT version 6.24.00 changed how gDirectory behaves. I added a check for the ROOT version with two different checks, either ```gDirectory == nullptr``` (older versions) or ```!gDirectory``` (newer versions). This now allows the analysis options to be written to file again.
Also changed all uses of MAJOR_ROOT_VERSION to use standard ROOT_VERSION_CODE instead.
> Fixed issue with AnalysisOptions not being written to file

- include/TBGSubtraction.h
- libraries/TGUI/TBGSubtraction.cxx
- Increased default maximum range for binning slider from 10 to 20 and added it as an input parameter to the constructor.
- Now also fixing the y-axis range when rebinning, using the range the old histogram was zoomed into relative to it's maximum values. This ensures that the changing bin values when re-binning are taken into account.
> Fix for issue #1223

- GRSIProof/CrossTalk.C
- libraries/GROOT/GGaus.cxx
- libraries/TAnalysis/TDetector/TDetectorHit.cxx
- libraries/TAnalysis/TGRSIFit/TGRSIFunctions.cxx
- libraries/TAnalysis/TGRSIFit/TMultiPeak.cxx
- libraries/TAnalysis/TGRSIFit/TPeak.cxx
- libraries/TAnalysis/TPeakFitting/TPeakFitter.cxx
- libraries/TGUI/TBGSubtraction.cxx
- Added a reset of the peak parameters before fitting a peak in TBGSubtraction, should fix the problems @bolaizol reported at the end of #1223.
- Added checks that the covariance matrix is good for TPeakFitter and TGRSIFunctions::CheckParameterErrors.
- Removed an unnecessary ```*  1``` in TDetectorHit::GetTimeStampNs.
- Removed commented out code.
- The default k-value in CrossTalk.C selector is now set via a single global variable instead of being hard-coded in two places.
> Bug fix for fitting in TBGSubtraction (see #1223) and other small changes

- include/TChannel.h
- include/TMnemonic.h
- libraries/TAnalysis/TDetector/TDetectorHit.cxx
- libraries/TFormat/TChannel.cxx
- libraries/TFormat/TMnemonic.cxx
TChannel::GetTime in turn calls the GetTime function of the fMnemonicClass. This way the TDetectorHit class can apply the CFD algorithm the right way for the type of digitizer this channel belongs to without knowing anything about the digitizers. This together with the corresponding changes in the parser libraries solves issue #1209.
ATTENTION: Using this commit means that the parser libraries have to be updated as well!
> TDetectorHit::GetTime now uses TChannel::GetTime

- include/TGauss.h
- libraries/TAnalysis/TPeakFitting/TGauss.cxx
- libraries/TAnalysis/TPeakFitting/TPeakFitter.cxx
- libraries/TGRSIint/TGRSIOptions.cxx
After fitting a peak in a sub-range of the histogram, changing that range to fit another peak would give an error
```
Warning in <ROOT::Fit::FillData>: fit range is outside histogram range, no fit data for xaxis
Warning in <Fit>: Fit data is empty
```
This was because the fit function was created with a specific range (the first sub-range to be fitted), so trying to fit anything outside that range would fail. This was solved by simply always setting the range of the fit function to the current sub-range of the histogram.
Also removed the overwriting of the TSinglePeak::Print function in TGauss and improved the description of ```--max-events``` option.
> Fixed bug in TPeakFitter when changing range after fitting

- libraries/TAnalysis/TGRSIFit/TPeak.cxx
Now one can use ```TPeak::GetLastFit()``` after using 'F' to fit a peak to access the fit function (same as is already implemented in GPeak). This means the background function can now also be accessed (using ```TPeak::GetLastFit()->Background()```).
> Setting fLastFit member at end of TPeak::Fit, so that TPeak::GetLastFit() works

- include/TGRSISelector.h
- libraries/TGRSIProof/TGRSISelector.cxx
This issue came up again in #1252. We now check the size of objects after they have been created (this aims mostly for histograms), after the worker is done (first check for trees), and before trying to write them (final check for trees).
Objects that are too big are removed from the output list (and then no longer processed for sending and writing them), but not deleted. This means the selector will continue to fill the large histogram without issues (and use the memory for it!), the histogram will just not be written.
> Added check of objects sizes to TGRSISelector

- include/TCalGraph.h
- include/TDetector.h
- include/TDetectorHit.h
- include/TEfficiencyCal.h
- include/TEfficiencyGraph.h
- include/TEnergyCal.h
- include/TFragment.h
- include/TNucleus.h
- libraries/GROOT/GHSym.cxx
- libraries/TAnalysis/TCal/TEfficiencyGraph.cxx
- libraries/TAnalysis/TDetector/TDetector.cxx
- libraries/TAnalysis/TDetector/TDetectorHit.cxx
- libraries/TAnalysis/TNucleus/TNucleus.cxx
- libraries/TFormat/TFragment.cxx
The streaming operator calls a Print(std::ostream&) function that does the actual printing. This function can and should be overloaded by each child class. Since the streaming operator does not know about options, the Print function does not take any options either at the moment. If we want to have options again, we could change it so that the streaming operator simply uses an empty options string.
Changes to suppress compilation warnings:
- Removed unused variable in GHSym.
- Added conditions for ROOT versions 6.24 and 6.26 to use TGraph::Scale and TGraph::AddPoint.
- Changed TNucleus::SortName to return std::string instead of const char* as the latter was just a dangling pointer to deleted memory. Doesn't look like this function is used anywhere anyways?
Changed …
> Added threadsafe streaming operator to detector and detector hit classes

- GRSIProof/grsiproof.cxx
- include/TBgo.h
- include/TBgoHit.h
- include/TPPG.h
- include/TSingleton.h
- include/TSortingDiagnostics.h
- libraries/TAnalysis/TBgo/TBgo.cxx
- libraries/TAnalysis/TBgo/TBgoHit.cxx
- libraries/TFormat/TChannel.cxx
- libraries/TFormat/TPPG.cxx
- libraries/TFormat/TRunInfo.cxx
- libraries/TFormat/TSortingDiagnostics.cxx
- libraries/TGRSIProof/TGRSISelector.cxx
- Added Print(std::ostream) to TBgo and TBgoHit and silenced warnings when compiling selectors from shadowed functions.
- Made TRunInfo::Print threadsafe and removed extra newlines after dates.
- Fixed some of the "class already in TClassTable" messages when running grsiproof.
- Fixed a bug in TPPG that caused it to fail to get the right cycle information from the TPPG events in the data.
- TSortingDiagnostics: fixed version number and added check for nullptr.
- TSingleton: fixed Get() in case of multiple keys (e.g. when updating a key), also made the function be quiet by default. Get(true) will get the old verbosity (printing the filename the current instance was read from).
> Bug fixes and small improvements

- util/SetOdbFromData.cxx
This program takes any root file with a TPPG saved in it (e.g. fragment,
analysis, or selector output files), and try to set the ODB cycle
information from the PPG data.
If the ODB information in TPPG already matches the PPG data the program
won't do anything, otherwise it will try to determine the durations of
the stages of the cycle from the PPG data and write the updated TPPG to
file.
There are different colors for the output:
- dark yellow: file was not found.
- dark red: failed to find a TPPG in the file, this might happen for
source runs.
- blue: ODB matches PPG data, file is skipped.
- dark blue: PPG data is empty, most likely a source run, file is
skipped.
- red: ODB doesn't match the PPG data after setting it from the data.
This is a weird state to get in (not sure if it's even …
> New program to set ODB cycle information from PPG data

- include/TFragment.h
- include/TUnpackedEvent.h
- libraries/TAnalysis/TPeakFitting/TPeakFitter.cxx
- libraries/TFormat/TChannel.cxx
- libraries/TLoops/TDetBuildingLoop.cxx
Instead of looping over the vector of fragments and adding the fragments one at a time, we now simply set the vector.
> Using new TUnpackedEvent::SetRawData function

- libraries/TAnalysis/TGRSIFit/TGRSIFunctions.cxx
Fixes a minor compile error on CentOS 7.  
Compiler output following `make -j`:
```
Compiling .build/libraries/TAnalysis/TGRSIFit/TGRSIFunctions.o[ERROR]
Compiling TBgoHit.o                                                   [OK]
libraries/TAnalysis/TGRSIFit/TGRSIFunctions.cxx: In function ‘Double_t TGRSIFunctions::PhotoPeakBG(Double_t*, Double_t*)’:
libraries/TAnalysis/TGRSIFit/TGRSIFunctions.cxx:129:20: error: ‘isfinite’ was not declared in this scope
if(isfinite(result)) return result;
^
libraries/TAnalysis/TGRSIFit/TGRSIFunctions.cxx:129:20: note: suggested alternative:
In file included from /data1/jwilliams/GRSISort/include/TGRSIFunctions.h:11:0,
from libraries/TAnalysis/TGRSIFit/TGRSIFunctions.cxx:1:
/usr/include/c++/4.8.2/cmath:596:5: note:   ‘std::isfinite’
isfinite(_Tp __x)
^ …
```
> Fix compile error on CentOS 7

- GRSIProof/ExampleTreeSelector.h
- GRSIProof/grsiproof.cxx
- doxygen/Makefile
- include/Globals.h
- include/TCalibrationGraph.h
Put the functionality for printing the gdb stacktrace into a condition that it's not a Mac, and added a const cast for basename function in grsiproof.cxx.
All other changes are just to make doxygen happy (and cleaning up the doxygen makefile).
This should solve #1275?
> Compiling on MacOs 12.4 Monterey and some changes for doxygen

- include/TPulseAnalyzer.h
- libraries/TAnalysis/TPulseAnalyzer/TPulseAnalyzer.cxx
This adds some additional CsI fit types to TPulseAnalyzer, matching the SFU code [here](https://github.com/e-j-w/TIPsort/blob/master/current/utils/waveform_analyzer.c).  It's mostly a copy/paste from the SFU code, with slight modifications to match the GRSISort coding conventions.
Under this scheme, CsI waveforms are fit using 4 fit types (two component, slow component only, fast component only, and a shape representing gamma interactions with the PIN diode), and the fit type with the best chisq value is retained.  Previously only the two component type was used.  Of course this makes it take longer to fit each waveform, but when combined with the earlier [changes](https://github.com/GRIFFINCollaboration/GRSIData/pull/77) to allow waveform fits when building the analysis tree, this isn't …
> Pulse analyzer updates to match latest SFU code

- Examples/sort.sh
- GRSIProof/grsiproof.cxx
- include/GValue.h
- include/TGRSIOptions.h
- include/TGRSISelector.h
- libraries/GROOT/GCanvas.cxx
- libraries/TFormat/TPPG.cxx
- libraries/TGRSIProof/TGRSISelector.cxx
- libraries/TGRSIint/TGRSIOptions.cxx
- Improved sort.sh example script by adding "-maxdepth 1" to find command to exclude sub-directories.
- Added option to grsiproof to set the name of the input tree (e.g. to create histograms from a tree created by grsiproof).
- Added code to allow the grsiproof file prefix to be changed during the execution of the workers (e.g. to change the file name based on g-values passed to the selector).
- Added more verbosity to 2D-histogram hotkeys for cuts.
- Added null pointer check to TPPG::Add.
- Fixed a compiler warning.
> Small improvement and bug fixes

- GRSIProof/grsiproof.cxx
- include/TGRSIOptions.h
- libraries/TAnalysis/TDetector/TDetector.cxx
- libraries/TGRSIint/TGRSIOptions.cxx
New grsiproof options:
- ```--average-rate``` use average rate instead of current rate for progress bar.
- ```--parallel-unzip``` use parallel unzipping of input files.
- ```--cache-size``` set the tree cache size (default = -1 = off).
- ```--sub-mergers``` use sub mergers to merge results from workers (default = -1 = off, 0 = automatic number of mergers, everything else = this many mergers are used).
- ```--proof-stats``` enable proof stats.
> Added more grsiproof options

- examples/ExampleEventHelper.cxx
- examples/ExampleEventHelper.hh
- makefile
Changed the makefile to only use the ```-Wshadow``` flag for linux machines (this flag causes a **lot** of output on Macs) and simplified some of the other ways we set flags.
Changed slot arguments for CreateHistograms function in ExampleEventHelper to be called "slot" instead of "i" (which could easily clash with loop variables).
> Cosmetic changes in makefile and ExampleEventHelper

- examples/AngularCorrelationHelper.cxx
- examples/AngularCorrelationHelper.hh
- examples/ExampleEventHelper.cxx
- include/TDetector.h
- include/TSourceCalibration.h
- libraries/TGUI/TSourceCalibration.cxx
- TSourceCalibration: Fixed bug when using only one source and set default verbosity to zero, see #1295.
- AngularCorrelationHelper: Fixed bug so that it works with more than one helper.
- ExampleEventHelper: Only print messages for the first worker.
- TDetector: Added option to Add a hit directly. This means we can also add hits directly to all detector classes that inherit from TDetector and use it's fHits vector.
> Small updates and a bug fix

- libraries/TGRSIFrame/TGRSIFrame.cxx
- libraries/TGRSIFrame/TGRSIHelper.cxx
The template version of ```TFile::Get``` doesn't exist in older versions, as well as ```ROOT::GetThreadPoolSize()```. So we use the old version of ```TFile::Get``` and use the max-worker option directly (which is what the pool size is set to anyway).
> More changes in TGRSIFrame/Helper for older ROOT versions

- include/TPPG.h
- include/TScaler.h
- include/TScalerQueue.h
- libraries/TFormat/TPPG.cxx
- libraries/TFormat/TScaler.cxx
- libraries/TLoops/TAnalysisWriteLoop.cxx
- libraries/TLoops/TFragWriteLoop.cxx
Main change is that ```TFragWriteLoop``` now writes the ```TDeadtimeScalerQueue``` and ```TRateScalerQueue``` into trees in the fragment file (so far these two queues would get filled by the data parsers but nothing was done with the data afterwards).
Also made some small changes like cleaning up code and comments.
> Writing scaler trees to fragment file

- libraries/TGRSIFrame/TGRSIFrame.cxx
- libraries/TGRSIint/TGRSIint.cxx
- Added check to TGRSIint for open raw files. Otherwise we would try to access the first raw file, even if that one failed to open. So having a problem opening a raw file doesn't lead to a crash but the program exits normally (with an error messages on the terminal).
- TGRSIFrame: read "PPG" instead of "TPPG" from root files. This should fix issues with reading the PPG in grsiframe (same as was done before for grsiproof). Not sure if this poses an issue for older versions (which maybe wrote the PPG as "TPPG"?). If that is the case we would have to change the read to try and read "TPPG" if reading "PPG" fails.
> Small changes

- examples/AlphanumericHelper.hh
- examples/AngularCorrelationHelper.hh
- examples/CrossTalkHelper.hh
- examples/DirectoryHelper.cxx
- examples/DirectoryHelper.hh
- examples/ExampleEventHelper.cxx
- examples/ExampleFragmentHelper.hh
- examples/ExampleTreeHelper.cxx
- examples/ExampleTreeHelper.hh
- examples/GriffinKValueHelper.hh
- examples/TimeWalkHelper.hh
- include/TGRSIFrame.h
- include/TGRSIHelper.h
- include/TPeakFitter.h
- include/TSourceCalibration.h
- libraries/TAnalysis/TPeakFitting/TPeakFitter.cxx
- libraries/TGRSIFrame/TGRSIFrame.cxx
- libraries/TGRSIFrame/TGRSIHelper.cxx
- libraries/TGUI/TSourceCalibration.cxx
- To address the issue of writing histograms to separate directories in grsiframe the return type was changed from a TList to a map of TLists which maps the TLists to the path they are written to. This path is taken from the key used in the histogram maps in the ```CreateHistograms``` and ```Exec``` functions of the helper. Everything before the last ```/``` is used as a path, if no path is found the main directory of the file is used.
- TSourceCalibration now zooms the y-axis of the residuals when the range of the y-axis of the calibration graph is changed and vice versa.
- Also changed TPeakFitter::Fit to return the FitResultPtr used internally so that users can access it.
> Improvements for grsiframe and TSourceCalibration

- README.md
- libraries/TFormat/TDataFrameLibrary.cxx
- src/grsisort.cxx
This allows users to have their own history of commands, even when using a GRSISort installation shared with other users. Simply add a .grsirc file to your home directory with this content:
```
Rint.History: $(HOME)/.grsi_history
```
Of course any of the other settings of GRSISort (or ROOT) can also be overwritten in this file.
> Now also reading $(HOME)/.grsirc for user specific settings

- include/Globals.h
- include/TRunInfo.h
- libraries/TFormat/Globals.cxx
- libraries/TFormat/TRunInfo.cxx
- libraries/TGRSIFrame/TGRSIFrame.cxx
- src/grsisort.cxx
- util/PlotVsRun.cxx
- util/ReadCalFromRoot.cxx
- PlotVsRun plots histograms (1D or projection of 2D) vs the file index. The x-axis is also labeled by the run and sub run number (created by the new function ```TRunInfo::CreateLabel(bool quiet = false)```). First tests seem to work.
- ReadCalFromRoot does essentially the reverse of WriteCalToRoot. It takes a list of input root-files (which are expected to have a ```TChannel``` called "Channel" and a ```TRunInfo``` called "RunInfo" in them), and writes a cal-file for each one of them  (using the run number and sub run number as a name with a ```.cal``` suffix). This is mainly meant to create a backup of an existing calibration (on a file-by-file level) before new calibrations are applied, especially when a group of people is collaborating on analyzing the same files.
- In order to …
> PlotVsRun and ReadCalFromRoot added

- include/TLevelScheme.h
- libraries/TAnalysis/TLevelScheme/LinkDef.h
- libraries/TAnalysis/TLevelScheme/TLevelScheme.cxx
Fixes #1345 in about the worst way possible, by just disabling the entire TLevelScheme class for older gcc versions.
There's probably a better way to handle this, if you have any ideas, I can test them on my machine.
> Disable TLevelScheme class in older gcc versions, to avoid compile errors

- include/TAB3Peak.h
- include/TABPeak.h
- include/TGauss.h
- include/TLevelScheme.h
- include/TRWPeak.h
- include/TSinglePeak.h
- libraries/GROOT/GCanvas.cxx
- libraries/TAnalysis/TLevelScheme/LinkDef.h
- libraries/TAnalysis/TLevelScheme/TLevelScheme.cxx
- libraries/TAnalysis/TPeakFitting/TAB3Peak.cxx
- libraries/TAnalysis/TPeakFitting/TABPeak.cxx
- libraries/TAnalysis/TPeakFitting/TRWPeak.cxx
- libraries/TAnalysis/TPeakFitting/TSinglePeak.cxx
- Added function to find all gammas parallel to given gamma to TLevelScheme.
- Added consistent access functions to Sigma and FWHM to peaks.
- Added check to not use TLevelScheme if the standard is less than c++17 to GCanvas.
> Bug fixes and improvements for TLevelScheme and TPeakFitter peaks

- include/TABPeak.h
- include/TSinglePeak.h
- libraries/TAnalysis/TCal/LinkDef.h
This should fix issue #1361. I suppose it is a global problem, but somehow Mac doesn't care about the missing symbols?!
> Fix for Debian 11 compilation issues

- libraries/GROOT/GCanvas.cxx
- libraries/TAnalysis/TPulseAnalyzer/TPulseAnalyzer.cxx
Kris S recently found a math error (wrong sign for certain terms when computing matrix determinants) in the linear equation solver code he uses to fit TIP waveforms, which was adapted into the TPulseAnayzer class in GRSISort some time ago.  Thankfully, this didn't have a major effect on past analyses, but he found that this caused issues when he tried to adapt his code for different detector types/pulse shapes at SFU.  I've added Kris's fix here (looks good to me when testing it with some of my own TIP data).
Also, I was getting yet another CentOS 7 / gcc 4.x compilation error:
```
Compiling .build/libraries/GROOT/GCanvas.o    [ERROR]
libraries/GROOT/GCanvas.cxx: In member function ‘bool GCanvas::StorePosition(Int_t, Int_t, Int_t)’:
libraries/GROOT/GCanvas.cxx:482:5: error: ‘strcmp’ is …
```
> Fix math error in TPulseAnalyzer linear equation solver

- examples/CrossTalkHelper.cxx
- examples/EfficiencyHelper.cxx
- examples/EfficiencyHelper.hh
- include/TABPeak.h
- include/TCalibrationGraph.h
- include/TChannel.h
- include/TEfficiencyCalibrator.h
- include/TGRSIOptions.h
- include/TNucleus.h
- include/TSinglePeak.h
- include/TTransition.h
- libraries/GROOT/GCanvas.cxx
- libraries/TAnalysis/TCal/LinkDef.h
- libraries/TAnalysis/TCal/TEfficiencyCalibrator.cxx
- libraries/TAnalysis/TDetector/TDetectorHit.cxx
- libraries/TAnalysis/TPeakFitting/TSinglePeak.cxx
- libraries/TFormat/TMnemonic.cxx
- libraries/TGRSIFrame/TGRSIFrame.cxx
- libraries/TGRSIint/grsixx.cxx
- libraries/TGUI/TCalibrationGraph.cxx
- libraries/TGUI/TSourceCalibration.cxx
- util/PlotVsRun.cxx
- util/grsiframe.cxx
- CrossTalkHelper: Set pile-up rejection to false and changed default k-value to 379.
- EfficiencyHelper: Corrected output message in EndOfSort.
- TABPeak: Removed FWHM function, we're using the default one defined in TSinglePeak.
- TCalibrationGraph: Added functions to set marker style, line color and style, and axis title.
Also added function to marker and line color together, fixed definition of Print function, and
fixed setting the verbose level of all graphs contained in graph set to the same value. Added
option to use "same" as plotting option. Changed a lot of instances of "auto" to "auto&".
- TChannel: Changed comments of members to be included in class documentation.
- TEfficiencyCalibrator: Put contents of header and source file inside preprocessor condition to
only be active …
> Bunch of accumulated changes

- examples/sort.sh
- include/TAB3Peak.h
- include/TABPeak.h
- include/TEfficiencyCalibrator.h
- include/TGauss.h
- include/TNucleus.h
- include/TPeakFitter.h
- include/TRWPeak.h
- include/TSinglePeak.h
- include/TTransition.h
- libraries/GROOT/GCanvas.cxx
- libraries/TAnalysis/TCal/TEfficiencyCalibrator.cxx
- libraries/TAnalysis/TNucleus/TNucleus.cxx
- libraries/TAnalysis/TNucleus/TTransition.cxx
- libraries/TAnalysis/TPeakFitting/TAB3Peak.cxx
- libraries/TAnalysis/TPeakFitting/TABPeak.cxx
- libraries/TAnalysis/TPeakFitting/TGauss.cxx
- libraries/TAnalysis/TPeakFitting/TPeakFitter.cxx
- libraries/TAnalysis/TPeakFitting/TRWPeak.cxx
TPeakFitter: Using range of fit as limits for centroid
- Added option to include the range when initializing parameters, which uses the provided range as limits for the centroid.
- TPeakFitter uses the range selected to initialize the parameters.
- Fixed bug in TPeakFitter when re-using one TPeakFitter instance by adding and removing peaks from it.
TEfficiencyCalibrator: Added static members (with setters and getters) for range, threshold, background parameters, peak type, degree of fit function, calibration uncertainty, and flag whether to show removed fits. This allows setting them before initializing the class.
Nucleus can now list transitions sorted by energy or intensity. To this effect TNucleus now keeps two lists of transitions, one sorted by intensity, the other sorted by energy. …
> Improvement for TPeakFitter, TNucleus, and TEfficiencyCalibrator

- libraries/TAnalysis/TLevelScheme/TLevelScheme.cxx
The header file was checking for c++ standards 2017 and up, but the source file was only checking for c++ standards 2014 and up. This means if someone used c++14, the header file would look empty but the source file would still be there, creating compiler errors.
> Fixed issue with TLevelScheme compiler version mismatch

- include/TCalibrationGraph.h
- libraries/TGUI/TCalibrationGraph.cxx
- Added function to completely remove a graph from the set.
- Added option to use non-continuous scaling of graphs, meaning if there is a gap between the graphs, only those that have overlaps are scaled to each other (instead of not doing anything if there is a gap between graphs).
> Improved functionality of TCalibrationGraphSet

- libraries/TGRSIFrame/TGRSIFrame.cxx
This shouldn't change anything for older ROOT versions, for ROOT 6.30.02 however it will use the builtin progress bar of ROOT instead of the one implemented via lambda. The new progress bar includes time estimates, the rate at which events are processed and the number of files and events currently processed (including some colour formatting).
> Added ROOT's progress bar for ROOT versions >= 6.30.00

- include/TGRSIMap.h
- libraries/TGRSIint/TGRSIOptions.cxx
This fixes #1378 and also sets the word count flag to -1 as default (instead of +1) not just when the ```--recommended``` flag is used but in general.
> Fix for #1378 and correcting default word count

- examples/AngularCorrelationHelper.cxx
- examples/AngularCorrelationHelper.hh
- include/TGRSIHelper.h
- libraries/TGRSIFrame/TGRSIHelper.cxx
- Uses the new TGriffinAngles class to get the angles and store them in the output root file. For this the option to write anything inheriting from TObject to file was added to TGRSIHelper.
- Only creates the bare minimum of histograms (prompt, time random, and mixed for each angle), plus the versions for all angles of these matrices.
- Automatically handles folding, grouping, and addback based on the three boolean flags.
- Properly handles event mixing for 10 events per slot/thread. 10 is right now hard-coded into the .cxx file, but that could be changed to a user-set variable.
- Possible improvements:
- Change the helper to read the settings (the three flags, # of mixed events, and distance of detectors from center of array) from a settings file. Need a new class that handles reading …
> Reworked angular correlations helper

- examples/AngularCorrelationHelper.cxx
- examples/AngularCorrelationHelper.hh
- examples/AngularCorrelationSettings.par
- include/TUserSettings.h
- libraries/TFormat/TUserSettings.cxx
- Vectors in TUserSettings are recognized by being a list of comma
separated values. This means commas can't be used in the values for
strings, and if a setting is supposed to be a vector it has to have a
comma, even if there is only one value in the vector.
- Added an example of this to the AngularCorrelationSettings.par file.
- Added option to exclude detectors or crystals via user settings in AngularCorrelationsHelper.
> Added option to have vectors in TUserSettings

- libraries/TGUI/TCalibrationGraph.cxx
This is a segfault when running TSourceCalibration, zooming in on spectra and using Find Peaks (fast) before accepting all. 
It seems to have something to do with pushing back the new objects. This could be because we're out of memory, but for now I changed this to emplace_back (which should be better anyway) to see if that might fix it as well.
The lines below might hint at the cause of the crash. If you see question
marks as part of the stack trace, try to recompile with debugging information
enabled and export CLING_DEBUG=1 environment variable before running.
You may get help by asking at the ROOT forum https://root.cern/forum
preferably using the command (.forum bug) in the ROOT prompt.
Only if you are really convinced it is a bug in ROOT then please submit a
report at …
> Changed push_back to emplace_back due to segfault

- libraries/TDataParser/TFragmentMap.cxx
- libraries/TGRSIint/FullPath.cxx
The change from `int64_t` to `auto` was necessary for macOS. Apparently `Long_t` is `int64_t` on ubuntu but not on macOS?
> Fixed bug from last PR

- .github/workflows/cmake-multi-platform.yml
- .github/workflows/ubuntu-binary-ROOT.yml
- libraries/TFormat/TDataFrameLibrary.cxx
- util/grsi-config
- The makefile now checks if proof is available (via `root-config --has-proof`) and only compiles grsiproof if that is the case.
- grsi-config uses lists of library names, and checks if the corresponding shared object files exist before adding the corresponding flags. This is necessary because some libraries (like TGRSIint) do not exist anymore as separate libraries when using cmake.
- TDataFrameLibrary doesn't use linker flags in the compilation step, only does the compilation once (instead of repeating it during the linking step), and also includes the libraries of the parser library in the linking.
> Improved functionality of makefile and grsi-config if TProof class is missing and/or if cmake is used

- include/TRunInfo.h
- libraries/TAnalysis/TGRSIFit/LinkDef.h
- libraries/TAnalysis/TGRSIFit/TDecay.cxx
- libraries/TFormat/TParserLibrary.cxx
- libraries/TFormat/TRunInfo.cxx
- libraries/TGUI/LinkDef.h
- libraries/TGUI/TCalibrationGraph.cxx
The doxygen documentation for TRunInfo was improved, adding examples of how the information looks for different scenarios. TRunInfo now also stores and reports (via `TRunInfo::PrintVersion()`) the version and date of GRSISort used to sort the data, as well as the version and path of the parser library used.
Also removed some custom streamers that did the same thing as the default streamers.
> TRunInfo improvements

- include/TRunInfo.h
- libraries/TFormat/TGRSIFrame.cxx
- libraries/TFormat/TRunInfo.cxx
Using grsiframe with a single run resulted in a long list of "missing runs" because it thought the first run was run 0 (and thus listed all runs between 0 and the current run number). 
These changes were made:
- TGRSIFrame only reads the run info from file if it's the first file of the list of files, and adds all other run infos to this one. Before we added all run infos to the existing empty one.
- TRunInfo does not add the current run number and subrun number to the run list if a new run is added. This might not be needed anymore/mess things up in other situations!
- ListOfMissingRuns by default prints at most 20 missing runs (with "... and more" added if more than 20 are missing). This doesn't fix the issue, it's just for cosmetics.
- ListOfMissingRuns also check if the run list …
> Fixing bug in TRunInfo and TGRSIFrame

- include/TGRSIFunctions.h
- libraries/TAnalysis/TGRSIFit/TGRSIFunctions.cxx
Changed the pre-processor fence to be inside the function (returning a default value and giving an error message when mathmore is missing) instead of suppressing the function completely.
> Fixing #1467

- libraries/TFormat/TGRSIFrame.cxx
- util/grsiframe.cxx
With the new creation of a log-file, we need to read the run info from all input files before we try and open the log-file.
> Fixing bug in grsiframe

- CMakeLists.txt
- include/GH2D.h
- include/GH2I.h
- include/TEfficiencyCalibrator.h
- libraries/GROOT/GCanvas.cxx
- libraries/GROOT/GH2D.cxx
- libraries/GROOT/GH2I.cxx
- libraries/GROOT/GRootCommands.cxx
- libraries/TAnalysis/TCal/TEfficiencyCalibrator.cxx
- libraries/TAnalysis/TNucleus/TGRSITransition.cxx
- libraries/TFormat/TBadFragment.cxx
- libraries/TFormat/TDetectorHit.cxx
- libraries/TFormat/TFragment.cxx
- libraries/TGRSIint/TGRSIint.cxx
- Added check for python version around include statement for TPython.h, should also catch cases where TPython.h is missing?
- Removed old code for support of ROOT 5 (we're not supporting ROOT 5 anymore anyway, so this code is unnecessary).
- Fixed a bug when using the `g` key without setting markers first.
> Various small changes

- include/GH1D.h
- include/Globals.h
- include/TCalibrationGraph.h
- include/TEfficiencyCalibrator.h
- include/TSourceCalibration.h
- libraries/GROOT/GH1D.cxx
- libraries/TAnalysis/TCal/TEfficiencyCalibrator.cxx
- libraries/TGUI/TCalibrationGraph.cxx
- libraries/TGUI/TSourceCalibration.cxx
- thisgrsi.sh
Also changed those classes that do already use a `VerboseLevel` to implement that as a static member (with static setters and getters) using said enum.
Added more static parameters (like window width and height) to `TSourceCalibration` to have less hard-coded numbers in the code.
> Defining global enum for verbosity level

- CMakeLists.txt
- include/TGRSIUtilities.h
- include/TSourceCalibration.h
- libraries/GROOT/TLevelScheme.cxx
- libraries/TAnalysis/TSRIM/TSRIM.cxx
- libraries/TFormat/TDataFrameLibrary.cxx
- libraries/TFormat/TGRSIUtilities.cxx
- libraries/TFormat/TParserLibrary.cxx
- libraries/TGRSIint/TGRSIint.cxx
- libraries/TGUI/TSourceCalibration.cxx
This should fix #1493.
CMakeLists.txt now copies the SRIMData directory to the build directory and TSRIM checks if the directory `$GRSISYS/libraries/TAnalysis/SRIMData` exists and if not tries to use `$GRSISYS/SRIMData` instead.
Also added some small changes to TSourceCalibration.
> Adding SRIMData to cmake build directory

- CMakeLists.txt
Fixes issue when compiling with cmake on macOS.
> Added TFormat dependency for TSRIM

- makefile
Also removed duplicate `-lTreePlayer -lX11 -lXpm` from LINKFLAGS. Tested on macOS 15.1.1 and ubuntu 22.04.5.
> Added  to ROOT_LIBFLAGS

- include/TCalibrationGraph.h
- include/TPeakFitter.h
- include/TSinglePeak.h
- include/TSourceCalibration.h
- libraries/TAnalysis/TPeakFitting/TPeakFitter.cxx
- libraries/TGUI/TCalibrationGraph.cxx
- libraries/TGUI/TSourceCalibration.cxx
- makefile
- Overriding Draw function to call DrawCalibration (which is the actual
function to draw the TCalibrationGraphSet).
- Added function to sort the whole set.
- Fixed how RemovePoint and RemoveResidualPoint work. They now both call
RemovePoint, providing the graph to work on (data or residuals),
removing code duplication. The emitted signal now isn't just repeating
the coordinates (making it necessary to again find the right peak
based on these), but the index of the removed point and the index of
the graph this point belonged to.
- Not releasing fixed parameters anymore when using retryfit, only those
with parameter limits.
- Added static VerboseLevel functions to control verbosity of debuggin
messages.
- Added check for missing fit functions when evaluating the fit
function.
- Added …
> Various improvements around TSourceCalibration

- include/TCalibrationGraph.h
- include/TPeakFitter.h
- include/TRedirect.h
- include/TSinglePeak.h
- include/TSourceCalibration.h
- libraries/TAnalysis/TPeakFitting/TPeakFitter.cxx
- libraries/TGUI/TCalibrationGraph.cxx
- libraries/TGUI/TSourceCalibration.cxx
- Fixed almost all bugs in `TSourceCalibration`, only ones left are some graphics bugs that can easily be fixed by the user.
- Fixed a bug in `TRedirect` where the redirect would not get closed at the end, increasing the number of open files with every call to it.
- `TPeakFitter`: fit functions name now includes the range of the fit, and added access functions for the individual peaks.
- Fixed bug in `TSinglePeak` where `SetLineStyle` would actually set the colour, not the style of the line and added getters for both the colour and the style of the fit function.
> Improved TSourceCalibration

- libraries/TFormat/TDetectorHit.cxx
The parentheses were places wrong so that any time offset of a channel would be multiplied into the timestamp.
> Fixed bug in GetTimeStampNs with time offset

- examples/AngularCorrelationHelper.cxx
- examples/AngularCorrelationHelper.hh
- examples/ExampleEventHelper.cxx
- include/TDataParser.h
- include/TRawFile.h
- include/TUserSettings.h
- util/GainDrift.cxx
**GainDrift**
Introduced the option to add energy uncertainties and fixed a bug where any bad fit would cause the corresponding graph to have a data point at 0, 0.
Added a minimum FWHM for fits to be accepted as good, and the option to change the degree of the polynomial fitted.
Updated what is read from the user settings file to add (almost?) all command line parameters.
**Linter**
Added a function to `TUserSettings` to get a string with a provided default `const char*`, before these calls would see the pointer get converted to a boolean and then the function w/o the default value was called.
Added a few exceptions for the linter, for `long` arguments that are used to pass value to be assigned to the `std::atomic_long` member of `TDataParser`, and for the non-constant pointer for the …
> Improvement to GainDrift program and linter fixes

- examples/AngularCorrelationHelper.cxx
- include/TDetector.h
- libraries/TFormat/TDetector.cxx
This option is "a", which solves an issue with a memory leak in the SimulationAngularCorrelations program. Since the default option is empty, this won't affect any existing code, but I will check if we can change other codes in a similar way and maybe reduce memory usage of grsisort that way.
Also changed the way we loop over the second hit in the AngularCorrelationHelper, might make it a bit faster?
> Added option to delete all hits in TDetector, not just clearing the vector containing them
